### ISSUE TITLE
[Bug] alpaca_tokenizer.py数据处理问题：ass_s[14:]截断错误？

### ISSUE THREAD

**Issue by angelOnly** [InternLM/InternLM#101]
### 描述该错误

数据Tokenizer的问题，对ass_s进行截断最前面14个字符的时候，我打印了结果，发现截断后的文本是错误的、。
如下图所示：
![8061689656773_ pic](https://github.com/InternLM/InternLM/assets/18018532/d343d873-559c-4283-b364-c0eeb28b63a2)
![8071689656773_ pic](https://github.com/InternLM/InternLM/assets/18018532/df6c0145-30f7-4e2d-9dc3-c55cb9b9d624)

我数了一下，刚好<|Assistant|>:的长度是14，但这里截断的ass_s，把原来的文本截断错误了，文本最前面的字被截没了
我不理解的是，既然要把<|Bot|>:的对话替换成<|Assistant|>:，那为啥还要再这里拼接一次，把原来的Bot截断，这是干嘛？
为什么不直接用Assistant替换前面的Bot，为啥要在这里进行截断拼接，本身就是要把<|Assistant|>:的Token+ass_s的token，直接将Bot替换再Tokenizer不对吗

还有，我想要微调，是用alpaca_tokenizer进行数据处理吗？

### 环境信息

略

**Comment by MeowZheng** [comment]
Thanks for your bug reporting, we are working on fixing it.
