### ISSUE TITLE
[Bug] 请问jsonl格式文件直接对每行json数据进行tokenize是正确的吗?

### ISSUE THREAD

**Issue by Poeroz** [InternLM/InternLM#103]
### Describe the bug

https://github.com/InternLM/InternLM/blob/efbf5335709a8c8faeac6eaf07193973ff1d56a1/tools/tokenizer.py#L113

这里直接将jsonl的每一行进行tokenize，没有从json里提取text，请问这种做法是正确的吗？谢谢！

### Environment

N/A

**Comment by gaoyang07** [comment]
Thanks for asking. For training purposes, we only require the textual input data to be in string format. The specific structure or formatting of the data is not our concern - it is up to the user to organize their data. As a result, our tokenizer simply processes each line of text input individually and encodes it, irrespective of the overall input format. The tokenizer does not need to handle different input formats differently during encoding. Its job is to encode each line of textual data into tensors, agnostic to the input style.
