### ISSUE TITLE
[QA] 预训练阶段的数据处理

### ISSUE THREAD

**Issue by www516717402** [InternLM/InternLM#104]
### 描述问题

有计划增加预训练阶段的数据处理和清洗的功能吗？

**Comment by yhcc** [comment]
目前这部分代码由于和我们环境中的基础设施融合比较紧密，之后将技术细节抽离出来之后会开源一些我们的处理逻辑的~

**Comment by www516717402** [comment]
@yhcc 有具体的时间计划表吗？

**Comment by yhcc** [comment]
目前还没有~如果有的话我们会第一时间更新到internlm的
