### ISSUE TITLE
[Bug] ModuleNotFoundError: No module named 'internlm'

### ISSUE THREAD

**Issue by fyubang** [InternLM/InternLM#107]
### Describe the bug

> python tools/transformers/convert2hf.py --src_folder origin_ckpt/ --tgt_folder hf_ckpt/ --tokenizer ./tools/V7_sft.model

when I tried to use this command to convert the weight, it reported an error as:

> Traceback (most recent call last):
> File "tools/transformers/convert2hf.py", line 141, in
> model_config = load(os.path.join(folder, "model_config.pt"))
> File "tools/transformers/convert2hf.py", line 136, in load
> pt_data = torch.load(f, map_location="cpu")
> File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 789, in load
> return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
> File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 1131, in _load
> result = unpickler.load()
> File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 1124, in find_class
> return super().find_class(mod_name, name)
> ModuleNotFoundError: No module named 'internlm'

### Environment

installed as instructions

**Comment by x54-729** [comment]
Could you please provide more information? Where did you execute this command?

**Comment by fyubang** [comment]
> 

I have got the ckpt after SFT and saved it in the folder as:
![image](https://github.com/InternLM/InternLM/assets/25549892/921e258b-a0e8-4d56-b7b0-f9a55d7a2029)
I execute this command in the folder of InternLM.

**Comment by fyubang** [comment]
> Could you please provide more information? Where did you execute this command?

python tools/transformers/convert2hf.py --src_folder output/xxx/1000/ --tgt_folder output/xxx/1000/ --tokenizer ./tools/V7_sft.model

**Comment by kkscilife** [comment]
Try export the path: export PYTHONPATH=$PWD:$PYTHONPATH in root dir of the item

**Comment by fyubang** [comment]
> Try export the path: export PYTHONPATH=$PWD:$PYTHONPATH in root dir of the item

Thanks. It works.

**Comment by fyubang** [comment]
> Try export the path: export PYTHONPATH=$PWD:$PYTHONPATH in root dir of the item

Another bug. I found that after converting the weight, the AutoModel map in the config file is wrong, I think it should be `InternLMForCausalLM` instead of `InternLMModel`.

**Comment by x54-729** [comment]
> > Try export the path: export PYTHONPATH=$PWD:$PYTHONPATH in root dir of the item
> 
> Another bug. I found that after converting the weight, the AutoModel map in the config file is wrong, I think it should be `InternLMForCausalLM` instead of `InternLMModel`.

Yes it should be `InternLMForCausalLM`, we will fix it soon.
