### ISSUE TITLE
[Bug] ModuleNotFoundError: No module named 'torch._six'

### ISSUE THREAD

**Issue by angelOnly** [InternLM/InternLM#109]
### Describe the bug

ModuleNotFoundError: No module named 'torch._six'

<img width="958" alt="image" src="https://github.com/InternLM/InternLM/assets/18018532/331c89f7-4f67-400b-836a-4ff2d2c83dec">
将这个文件里面的torch._six改成torch就好，pytorch2.0没有six这个包，就是torch包

### Environment

下载的这个torch版本
conda install pytorch==2.0.0 torchvision==0.15.0 torchaudio==2.0.0 pytorch-cuda=11.8 -c pytorch -c nvidia

torch              2.0.0
torch-scatter      2.1.1+pt113cu117
torchaudio         2.0.0
torchvision        0.15.0

**Comment by li126com** [comment]
是的pytorch2.0改了，from torch._six import inf 改成 from torch import inf
