### ISSUE TITLE
[QA] 多轮对话数据怎么处理？

### ISSUE THREAD

**Issue by angelOnly** [InternLM/InternLM#113]
### Describe the question.

多轮对话的输入数据应该怎么处理
现在看到的官方案例中，要么是单轮，要么轮数很少

我这边有一个多轮对话的数据集，是这样的格式
Q1->A1
Q1,A1,Q2->A2
Q1,A1,Q2,A2,Q3->A3
Q1,A1,Q2,A2,Q3,A3,Q4->A4
...

我想问下，我是不是只需要输入最后的一条Q1,A1,Q2,A2,Q3,A3,Q4->A4，其他的数据都删掉，因为其他的数据跟最后一条数据是重复的，会让模型重复学习

是不是我这样理解的？还是说，每一个都是一条，全部都输入到模型中

**Comment by angelOnly** [comment]
`def tokenize(sample, sp_model):
    """Tokenize input dataset

    Args:
        sample (dict): Input data sample.
        sp_model (str): Path of tokenizer.

    Returns:
        tuple: dumped processed data sample and length of tokens.
    """
    special_tokens_map = {"<eoh>": 103167, "<eoa>": 103166, "nl_id": 13}
    token_ids = [sp_model.bos_id()]
    """
    "求助者:我最近感到很迷茫。高三后的我，不仅感到高考前的恐惧，还感到从自己出生以来就是多余的，毫无意义。我没有朋友，只能一个人默默承受。您能给我一些建议吗？
    支持者:看到你的话，我感到你很焦虑，这是常见的高中生活状态。首先想说的是，我看到了你的决心。这点是很多人没有的。高考最重要的是心态，你需要具备必胜的心态！
    求助者:谢谢你的鼓励！我真的很想放松一下，但是也觉得自己不能失去目标和动力。
    支持者:",
    """
    human_s = sample["user"]
    ass_s = sample["bot"]
    print("human_s:", human_s)
    # print("ass_s:", ass_s)

    print("<|Bot|> token---:", sp_model.encode("<|Bot|>:"))
    print("<|User|> token---:", sp_model.encode("<|User|>:"))
    # 使用正则表达式将对话分成求助者和支持者的对话
    pattern = r"(求助者|支持者)：(.*?)\s*(?=求助者|支持者|$)"
    matches = re.findall(pattern, human_s, re.DOTALL)
    human_ids = []
    al_human_s = ""
    for match in matches:
        speaker, message = match
        if not message:
            continue
        if "求助者" in speaker:
            al_human_s += "<|User|>:" + message
            sub_human_ids = sp_model.encode("<|User|>:" + message) + [special_tokens_map["<eoh>"],
                                                                      special_tokens_map["nl_id"]]
        else:
            al_human_s += "<|Bot|>:" + message
            sub_human_ids = sp_model.encode("<|Bot|>:" + message) + [special_tokens_map["<eoa>"],
                                                                     special_tokens_map["nl_id"]]
        # print("speaker, message :", speaker, message)
        # print("sub_human_ids:", sub_human_ids)
        human_ids.extend(sub_human_ids)

    print("al_human_s:", al_human_s)
    print("human_ids:", human_ids)
    # human_ids [333, 352, 1621, 352, 330, 642, 69557, 78467, 67628, 69229, 71374, 98899, 60360, 82357, 99050, 103167, 13]
    human_ids_ignore = [-token_id for token_id in human_ids]
    print("human_ids_ignore:", human_ids_ignore)
    ass_template_ids = sp_model.encode("<|Bot|>:")
    ass_template_ids_ignore = [-token_ids for token_ids in ass_template_ids]
    print("ass_template_ids_ignore:", ass_template_ids_ignore)
    ass_ids = (
            ass_template_ids_ignore
            + sp_model.encode(ass_s)
            + [special_tokens_map["<eoa>"], special_tokens_map["nl_id"]]
    )
    print("ass_s:", ass_s)
    print("ass_ids:", ass_ids)
    token_ids += human_ids_ignore + ass_ids
    if len(token_ids) > 2047:
        token_ids = token_ids[:2047]
    token_ids += [sp_model.eos_id()]
    print("token_ids:", token_ids)
    line = str.encode(json.dumps({"tokens": token_ids}) + "\n")
    return line, len(token_ids)`

我的多轮对话，我最后的tokenizer是这样处理的
Q: User: xxx, Bot: xxx  我把整个Q当成一句话进行tokenzier，最后这一句话都是负数的token，不过这里面，User和Bot还是会按照正常的进行Token，我还在User后面加上结束符号<eoa>和nl_id的token_idx，Bot结尾加上<eoh>和nl_id的token_idx
A: Bot:xxx 这个跟原来的处理一样

token案例：
humans_ids: -[tokenizer("<|User|>:") + tokenizer("input") +  tokenizer("<eoa>") + tokenizer("nl_id") + tokenizer("<|Bot|>:") + tokenizer("input") +  tokenizer("<eoh>") + tokenizer("nl_id") + ...]
bot_ids: [tokenizer("<|Boy|>:") + tokenizer("input") +  tokenizer("<eoa>") + tokenizer("nl_id")]
ass_ids: [sp_model.eos_id()] + humans_ids + bot_ids

最后出来的就是这样，最后是
<img width="1402" alt="image" src="https://github.com/InternLM/InternLM/assets/18018532/740598a4-bc2d-4a37-b479-dae00e53c428">
这里只是一个案例，我是多轮对话，最后的结果会更长一点

**Comment by ZwwWayne** [comment]
Yes you can use Q1,A1,Q2,A2,Q3,A3,Q4->A4. You can also concat the whole chat history and let the model learn A1/A2/A3/A4 in one sample by masking the Q1/Q2/Q3/Q4

**Comment by angelOnly** [comment]
请问你说的mask是数据处理层面的还是要改模型结构，还有就是要mask的话，我的数据输入是不是这样

数据层Mask:
全部输入的数据格式：
Q1,A1,Q2,A2,Q3,A3,Q4->A4
mask的数据格式：
""->A1
Q1,A1,""->A2
Q1,A1,Q2,""->A3
Q1,A1,Q2,A2,""->A4

模型层Mask:
如果是在模型层做mask，请问是在哪一层网络进行mask，我还没仔细研究过这个模型结构，还麻烦告知一下，谢谢

**Comment by MeowZheng** [comment]
The data samples, I think, should be like
```
[Q1, A1, Q2, A2,....Qn, An]
[Q'1, A'1,..., Q'n, A'n]
```
for each data sample, there is a whole chat history.

In InternLM, the loss function automatically ignores tokens less than 0, and we utilize an autoregressive objective and ignore the loss on tokens from user prompt, i.e. `Q`, so we set tokens of `Q` to negative.

**Comment by angelOnly** [comment]
你的意思是，Q都是负数，A都是正数吗？
但现在的tokenizer已经是这样的结果了？跟之前有什么区别？
还有就是你说的这个，我其实还没有完全理解，如果是按照我那样理解的，更不太懂了

**Comment by yangjianxin1** [comment]
可以参考文章，充分高效地训练多轮对话：[一文看懂：如何充分高效训练多轮对话大模型](https://mp.weixin.qq.com/s/KsbgRNTwXE86kCGTJhu0WQ)
