### ISSUE TITLE
[Bug] SFT之后模型推理乱码问题

### ISSUE THREAD

**Issue by fyubang** [InternLM/InternLM#118]
### Describe the bug

我尝试了一遍SFT，并在训练结束后用tools/transformers/convert2hf.py转了权重，然后利用huggingface load完，用model.chat推理。但是结果出来是这样的utf-8码："\x0c\r\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19"

### Environment

as instructed

**Comment by fyubang** [comment]
训练数据格式为：
```
{"instruction": "给定的句子为：“您与我们的合同1.1合同订立“长城附加福康人生两全保险保险合同”（以下简称“本附加险合同”）由主保险合同（以下简称“主险合同”）投保人提出申请，经我们同意而订立。1.2合同成立与生效本附加险合同应与主险合同同时投保，本附加险合同的成立日、生效日与主险合同的成立日、生效日相同。1.3投保年龄指投保时被保险人的年龄，投保年龄以周岁（见9.1）计算，本附加险合同接受的投保年龄为0周岁（指出生满30日且已健康出院的婴儿）至65周岁。”\n\n给定的实体类型列表为：疾病分类、等待期、意外免等待期、费用报销范围、公立医院等级、费用类别、保障期类型、最高投保年龄、最低投保年龄、事故场景、豁免原因、生效类型、赔付比例、赔付限额、赔付次数、续保免等待期、津贴计算方式、单次事故免赔额、赔付间隔期、累计天数上限、医院类型、延长住院天数、未成年人赔付规则\n\n在这个句子中，可能包含了哪些实体片段及实体类型？你的输出格式如下：“(实体片段1,实体类型1)\n(实体片段2,实体类型2)\n...”", "input": "", "output": "(30日,最低投保年龄)\n(65周岁,最高投保年龄)"}
```
日志为：

> 
![image](https://github.com/InternLM/InternLM/assets/25549892/b8ae89c4-e3ea-44fd-8308-43e128d5ebe5)

**Comment by ZwwWayne** [comment]
You might need to check the encoding/decoding protocol of your file, for example, change it to ASCII
