### ISSUE TITLE
[QA] 不需要chat的能力，只需要few-shot来分类的话，使用普通版还是chat版

### ISSUE THREAD

**Issue by miiiiiko** [InternLM/InternLM#119]
### 描述问题

只需要in-context learning的能力执行分类任务而不需要chat，是把few-shot的输入输出拆成user和assistant的对话形式放到history然后加载chat模型后chat比较好，还是加载普通模型，直接把fewshot拼在前面比较好？

**Comment by ZwwWayne** [comment]
If you use chat model, you need to form the user/assistant format. 
Since the current chat model is significantly better than the pre-trained model. I suggest you to directly use InternLM-Chat
