### ISSUE TITLE
The inference process is too slow when using 'transformers'. Is this normal?

### ISSUE THREAD

**Issue by LiamTTT** [InternLM/InternLM#12]
Example provided in https://github.com/InternLM/InternLM#import-from-transformers toke more than 40s to finish at V100. Why?

**Comment by lvhan028** [comment]
You can try https://github.com/InternLM/lmdeploy, which is a very efficient and high-throughput LLM deployment toolkit for InternLM, LLaMA, vicuna etc.

**Comment by LiamTTT** [comment]
Will more general model inference optimization be done in the future?

**Comment by lvhan028** [comment]
> Will more general model inference optimization be done in the future?

Yes, it can be found in [LMDeploy](https://github.com/InternLM/lmdeploy)
