### ISSUE TITLE
[QA] Prompt for Chinese English translation

### ISSUE THREAD

**Issue by zzhanghub** [InternLM/InternLM#122]
### Describe the question.

Thank you for your awesome work. 
I now want to use internLM-chat-7b-8k to achieve English to Chinese translation.

The prompt I am using is
``` python
f"<s><|User|>:请你把下面的英文翻译成中文，请直接返回结果，不要说额外的话，待翻译的文本是“{en}”<eoh>\n"
```
The configs for `generate` I am using is

``` python
      output = model.module.generate(
          input_ids=input_ids, 
          max_new_tokens=50,  # Increase max_new_tokens as needed
          eos_token_id=[2, 103028],
          attention_mask=attention_mask,
          top_p=0.8, 
          temperature=0.8, 
          do_sample=True, 
          repetition_penalty=1.0
      )
```

Do you have any better suggestions?

**Comment by ZwwWayne** [comment]
Hi @zzhanghub ,
'<s>' seems to be unnecessary. You could refer to https://github.com/InternLM/InternLM/blob/main/web_demo.py#L180 as a reference to see what is really sent to the model without the terminal. If you want to obtain a better prompt, you could try prompt engineering https://lilianweng.github.io/posts/2023-03-15-prompt-engineering/#external-apis
