### ISSUE TITLE
[QA] Open LLM Leaderboard performance

### ISSUE THREAD

**Issue by eshoyuan** [InternLM/InternLM#129]
### 描述问题

InternLM demonstrates impressive performance in your report and benchmark. However, I didn't notice any scores on the Open LLM Leaderboard. Are there any plans to participate in this globally recognized benchmark?

**Comment by tonysy** [comment]
[OpenCompass ](https://opencompass.org.cn/) is a open-source evaluation platform, we also supported many datasets. Prompts and evaluation strategies are all public. Feel free to try OpenCompass. We believe more diverse datasets will make the evaluation more reliable.
