### ISSUE TITLE
what is the prompt used in chat model?

### ISSUE THREAD

**Issue by egrcc** [InternLM/InternLM#13]
I want to finetune the chat model using an instruction dataset.

can you give me the prompt used in your chat model?

`
USER: <instruction>\nASSISTANT: <output>
`
is this right?

**Comment by ZwwWayne** [comment]
Hi @egrcc ,
You can refer to the example at https://github.com/InternLM/InternLM/blob/main/tools/alpaca_tokenizer.py.
