### ISSUE TITLE
执行web_demo.py 报 已杀死[Bug] 

### ISSUE THREAD

**Issue by vivounicorn** [InternLM/InternLM#130]
### 描述该错误

问题描述：
执行streamlit run web_demo.py，到load model的loading checkpoint shards:时进程直接被杀死。

日志：
(illm) leon@leon-Precision-7550:~/Github/InternLM$ streamlit run web_demo.py

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://10.168.65.73:8501

load model begin.
Loading checkpoint shards:   0%|                             |0/2 [00:00<?, ?it/s]
已杀死

### 环境信息

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

**Comment by zslhy** [comment]
我也遇到一样问题，
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.125.06   Driver Version: 525.125.06   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
|  0%   55C    P8    24W / 340W |      6MiB / 16376MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
内存：32G 
系统：ubuntu 22.4

**Comment by vivounicorn** [comment]
@yhcc 
显卡：NVIDIA Corporation TU104GLM [Quadro RTX 4000 Mobile / Max-Q] / Mesa Intel® UHD Graphics (CML GT2)
显存：8G 
内存：32G 
处理器：Intel® Core™ i7-10750H CPU @ 2.60GHz × 12
系统：Ubuntu 22.04

**Comment by sunpengsdu** [comment]
When inferring with FP16 precision, the InternLM-7B model requires at least 15.7G of GPU memory overhead on TurboMind. It is recommended to use NVIDIA cards such as 3090, V100, A100, etc.

8G GPU Memory is not enough in this case.

**Comment by vivounicorn** [comment]
@sunpengsdu ok, thank you!
