### ISSUE TITLE
[QA] Tokenize结果多个1

### ISSUE THREAD

**Issue by LiuZhihhxx** [InternLM/InternLM#131]
### 描述问题

参考https://github.com/InternLM/InternLM/blob/main/doc/usage.md 提供的微调和预训练教程，自创了raw_data.txt文件和相应内容：
感恩生活中的每一个细节，才能真正体会到幸福的滋味。
梦想是人生的动力源泉，努力追逐，才能实现自己的目标。
学会宽容和理解，才能建立真正和谐的人际关系。

终端运行后得到了.bin 和.meta文件，但.bin文件tokens的列表中总是多一个开头的1。即.bin文件预期内容为
{"tokens": [73075, 75302, 69522, 69022, 98899, 67713, 68015, 81269, 74637, 75445, 99157]}
{"tokens": [69469, 60355, 73026, 68524, 60846, 61844, 98899, 67775, 79241, 98899, 67713, 67800, 67453, 67838, 99157]}
{"tokens": [68057, 79017, 60378, 68014, 98899, 67713, 67990, 68015, 70381, 67428, 61003, 67622, 99157]}

实际得到的.bin文件内容为
{"tokens": [1, 73075, 75302, 69522, 69022, 98899, 67713, 68015, 81269, 74637, 75445, 99157]}
{"tokens": [1, 69469, 60355, 73026, 68524, 60846, 61844, 98899, 67775, 79241, 98899, 67713, 67800, 67453, 67838, 99157]}
{"tokens": [1, 68057, 79017, 60378, 68014, 98899, 67713, 67990, 68015, 70381, 67428, 61003, 67622, 99157]}

请问这是什么问题？多谢

**Comment by yhcc** [comment]
这个是由于我们的模型会加入一个bos token，这个token的id就是
