### ISSUE TITLE
[QA] 微调时加载的Tokenizer跟web demo中的tokenizer包不一样

### ISSUE THREAD

**Issue by angelOnly** [InternLM/InternLM#135]
### 描述问题

我想在[LLaMA-Efficient-Tuning](https://github.com/hiyouga/LLaMA-Efficient-Tuning)项目中微调InternLM的Lora模型
LLaMA-Efficient-Tuning这里面加载的是transformers的AutoTokenizer，与web demo中的tokenizer包是一样的
但InternLM给的微调的文档中，加载的tokenizer却是另一个包，和推理时不一样。
![企业微信截图_3b99a468-4715-4774-aeea-fe07cea14d30](https://github.com/InternLM/InternLM/assets/18018532/8dd51e29-9725-41c4-a3dd-adf8421d6108)
![企业微信截图_75f26e6c-89e0-4317-9870-5d89de8bfd36](https://github.com/InternLM/InternLM/assets/18018532/667a36c3-489c-4c69-9db7-c10bf2ec5f5c)

### 我有几点疑问：
1. LLaMA Lora微调的输入和GLM模型的输入是类似的，history是list结构，而InternLM无论是微调，还是demo，输入都是将上下文历史进行拼接输入，那么，Lora微调的脚本，为什么能成功进行训练
2. InternLM chat模型的Tokenizer结果，Q是负数，A是正数，是当成一条文本进行输入，而Lora微调是将history list进行解析，一轮一轮进行读取，两种加载模式完全不一样的情况下，我理解是会影响结果的
3. 我看了Lora的结构以及与大模型之间的关系，那么，在LLaMA的Lora微调中，lora输入的结果就和internLM中输入给大模型的结果不一样，是不是也会影响训练结果

我在LLaMA那边提了issue没有得到答案，说我对InternLM源码理解错误，希望您能回答一下

![35441690353332_ pic](https://github.com/InternLM/InternLM/assets/18018532/b7fb61cc-ef65-4e5c-90ed-cb2e33cb8579)
![35481690353358_ pic](https://github.com/InternLM/InternLM/assets/18018532/cf08f2c4-a7a5-4e50-a129-143ad79047ec)

**Comment by gaoyang07** [comment]
您好，如果您需要在[LLaMA-Efficient-Tuning](https://github.com/hiyouga/LLaMA-Efficient-Tuning)这个项目中微调InternLM的Lora模型，则:

1. 应该使用他们提供的数据格式（见[LLaMA-Efficient-Tuning/data/README_zh.md](https://github.com/hiyouga/LLaMA-Efficient-Tuning/blob/main/data/README_zh.md)）来组织原始文本
2. tokenize过程可直接参考[LLaMA-Efficient-Tuning/src/llmtuner/dsets/preprocess.py](https://github.com/hiyouga/LLaMA-Efficient-Tuning/blob/f5c2ccdde45bfa5648443a901b2ac397d532eceb/src/llmtuner/dsets/preprocess.py)

**Comment by angelOnly** [comment]
我找到原因了，少加了一个参数，谢谢你哈

**Comment by hyDududu** [comment]
我也遇到了这个问题，请问错因在哪啊，是少了什么参数？

**Comment by hyDududu** [comment]
> 我找到原因了，少加了一个参数，谢谢你哈

我也遇到了这个问题，请问错因在哪啊，是少了什么参数？
