### ISSUE TITLE
[QA] CUDA out of memory in training

### ISSUE THREAD

**Issue by ArslanTu** [InternLM/InternLM#137]
### Describe the question.

I follow the steps in [usage](https://github.com/InternLM/InternLM/blob/main/doc/usage.md) to finetune the model. But I can not load the model with 8 RTX3090 (24G). I have tried to set `zero1` in parallel config as [-1, 8].

The environment is the same to [install](https://github.com/InternLM/InternLM/blob/main/doc/install.md).

**Comment by sunpengsdu** [comment]
![image](https://github.com/InternLM/InternLM/assets/6859848/48a6293b-20be-465b-9c9a-b030284f9651)

It seems that 24G memory is not large enough for training. We will try some other methods to reduce the GPU memory consumption later.
