### ISSUE TITLE
[QA] Reported training performance mismatch

### ISSUE THREAD

**Issue by scenarios** [InternLM/InternLM#146]
### 描述问题

I evaluated the training performance on 1 node (8 a100 40G) and 3 nodes (3x8 a100 40G) using the official docker image you supplied.

launch command I used:
torchrun --master_addr=$MASTER_ADDR --master_port=$MASTER_PORT --nnodes=$WORLD_SIZE --node_rank=$RANK --nproc_per_node 8 train.py --config ./configs/7B_sft.py --launcher "torch"

Only zero1, pp, and tp value in config file are modified accordingly.

Severe performance drop is observed regards to TFLOPS and TGS.
below is the performance:

1 node 8 gpus, zero1=8 , pp=1, tp=1
<img width="1114" alt="image" src="https://github.com/InternLM/InternLM/assets/15104876/51d69c4f-b9a3-4d21-9488-329c8d47aad5">

3 node 24 gpus, zero1=24 , pp=1, tp=1
<img width="1109" alt="image" src="https://github.com/InternLM/InternLM/assets/15104876/5f65732d-b447-40a4-9214-b9153d5a55e4">

3 node 24 gpus, zero1=8 , pp=1, tp=1 is even slower than zero1=24 (which is not reasonable)

Any suggestion is appreciated.

**Comment by scenarios** [comment]
also tested
3 node 24 gpus, zero1=1 , pp=1, tp=8
<img width="1118" alt="image" src="https://github.com/InternLM/InternLM/assets/15104876/5a820060-78a5-4760-925d-eb479ee3acf2">

**Comment by sunpengsdu** [comment]
Hi @scenarios , can you provide the config file used for training? It seems that the training performance showed in your first picture is quite strange: the TGS value is much higher than ours.

**Comment by scenarios** [comment]
> Hi @scenarios , can you provide the config file used for training? It seems that the training performance showed in your first picture is quite strange: the TGS value is much higher than ours.

I use the official /configs/7B_sft.py but half the head number and channel number (everything else is kept the same) to fit in 40G A100. So it is expected to have higher TGS.

The problem now is that the performance does not scale up to multi-nodes.

**Comment by sunpengsdu** [comment]
In the docker image, we did not install any RDMA related packages. So it can work fine in single node. If you directly use the docker images for training across nodes, all NCCL traffic will be on Ethernet. 

So is there any RDMA network, such infiniband or RoCE, in your platfom?

**Comment by scenarios** [comment]
> In the docker image, we did not install any RDMA related packages. So it can work fine in single node. If you directly use the docker images for training across nodes, all NCCL traffic will be on Ethernet.
> 
> So is there any RDMA network, such infiniband or RoCE, in your platfom?

Yes my platform has RDMA network.
That said the released docker image is not the same with the one used for your performance benchmarking?

**Comment by sunpengsdu** [comment]
We have several testbeds in our platform, including slurm-based and k8s-based platform. The released docker images are mainly used for single-node development. Since the rdma package dependeds on the hardware and driver version (for example, the OFED), we did not install them in the docker image.

In our case, the performance evaluations are done on k8s. And we install the OFED based the hardware information in our private image repo.

If you are familiar with slurm, I recommend to try distributed training on slurm.

**Comment by scenarios** [comment]
> 

Thanks a lot for your clarification.

Actually I have build a compatible base image for my k8s platform. However, following your install instruction, every time I try to import rotary_emb it causes a core dump. So I switched to your image but did not realize it has no RDMA packages.

Do you have any suggestion on the rotary_emb core dump things?

**Comment by scenarios** [comment]
> Thanks a lot for your clarification.
> 
> Actually I have build a compatible base image for my k8s platform. However, following your install instruction, every time I try to import rotary_emb it causes a core dump. There is no error during building time. So I switched to your image but did not realize it has no RDMA packages.
> 
> Do you have any suggestion on the rotary_emb core dump things? <img alt="image" width="665" src="https://user-images.githubusercontent.com/15104876/256732203-aa9703b7-b798-45d6-a266-fb3fae4247a9.png">

I finally make it work.
Two changes are made. 1) Downgrade from torch 2.0.0-cuda171 to torch 1.3.1-cuda171. 2) Manually clone apex and flash_attn git repo and check out the corresponding commit for building. I do not use the submodule included in this repo.

Seems like there is compatibility issue with torch 2.0.0? Cause apex and flash_attn in this repo should be the same with the manually cloned one. There should be no difference, not so sure.

**Comment by sunpengsdu** [comment]
Hi @scenarios , I tried torch2.0 + flash-attention1.0.5 in the docker image (sunpengsdu/internlm:torch2.0.1-cuda11.8-flashatten1.0.5-centos), it works good. Not sure the compatibility issues come from torch2.0 or cuda or flashattention. I will try them later.

**Comment by scenarios** [comment]
> Hi @scenarios , I tried torch2.0 + flash-attention1.0.5 in the docker image (sunpengsdu/internlm:torch2.0.1-cuda11.8-flashatten1.0.5-centos), it works good. Not sure the compatibility issues come from torch2.0 or cuda or flashattention. I will try them later.

I tried again, it works. There might be something missed during my first attempt.
Thanks for your efforts. Cheers~
