### ISSUE TITLE
load_in_4bit support[Feature] 

### ISSUE THREAD

**Issue by kizunasunhy** [InternLM/InternLM#150]
### Describe the feature

It will be great to support load_in_4bit for the 
```
model = AutoModelForCausalLM.from_pretrained(model_id, device_map="auto", load_in_4bit=True)
```
in Huggingface. So far a calculation error occured.
Thank you.

### Will you implement it?

- [ ] I would like to implement this feature and create a PR!

**Comment by ZwwWayne** [comment]
Hi @kizunasunhy ,
Thanks for your feature request. We do have plans for that. Please stay tuned.

**Comment by lvhan028** [comment]
@kizunasunhy Are you looking forward to 4bit training or 4bit inference?
