### ISSUE TITLE
[Feature] 能否提供lora微调的fnlp/moss-moon-002-sft处理脚本和实验效果

### ISSUE THREAD

**Issue by xinlianglalala** [InternLM/InternLM#162]
### Describe the feature

当前仓上有lora配置示例，对数据集moss-moon的预处理和tokenize过程并未提供，能否给出脚本用于lora微调

### Will you implement it?

- [ ] I would like to implement this feature and create a PR!

**Comment by ZwwWayne** [comment]
For MOSS SFT data, we mask all user questions and tokenized it using the same code as that for alpaca.
