### ISSUE TITLE
[QA] How to convert pertained weight into different tp/pp settings

### ISSUE THREAD

**Issue by scenarios** [InternLM/InternLM#168]
### Describe the question.

The released internlm7b weight is model_tp0_pp0.pt.
What should I do to make it applicable for the training setting like tp=N>1, pp =M>1?

In your load_model_checkpoint method it says "If the tp is inconsistent with the saved one in the future use, the weight needs to be converted before loading.".  Where can we find the script for the conversion?

**Comment by sunpengsdu** [comment]
We will open this tool in our next version, which would support pp > 1

**Comment by scenarios** [comment]
Can you provide a simple script that converts the pre-trained weight accordingly?
