### ISSUE TITLE
[QA] README中的模型下载链接失效了

### ISSUE THREAD

**Issue by TTroia** [InternLM/InternLM#169]
### Describe the question.

README中的模型下载链接失效了

**Comment by ZwwWayne** [comment]
Hi @TTroia ,
Could you describe in detail which link you use is invalid?

**Comment by TTroia** [comment]
![WX20230803-100908](https://github.com/InternLM/InternLM/assets/9925150/b5131d84-467b-41c5-9bc3-05d4afde3c3d)
![WX20230803-100917](https://github.com/InternLM/InternLM/assets/9925150/1c703604-435f-4021-bcaa-552fa87d456d)
readme文件中的模型下载链接不能访问了。
