### ISSUE TITLE
[Bug] fatal: 正克隆到 'InternLM'... git@github.com: Permission denied (publickey). fatal: 无法读取远程仓库

### ISSUE THREAD

**Issue by tcexeexe** [InternLM/InternLM#179]
### Describe the bug

Hello~
     I try to install the InternLM follow the `doc/install.md`, but an error occurred when l input the order
     `git clone git@github.com:InternLM/InternLM.git --recurse-submodules`
![image](https://github.com/InternLM/InternLM/assets/28287196/49364c04-f985-4911-8abe-4c5599dd6364)
     Dose anybody know how to solove it?

### Environment

above

**Comment by ZwwWayne** [comment]
Please refer to https://docs.github.com/en/authentication/troubleshooting-ssh/error-permission-denied-publickey. There might be some issues in the configuration of your GitHub.
