### ISSUE TITLE
[Feature] Dockerfile for sunpengsdu/internlm:torch1.13-cuda11.7-flashatten1.0.5-centos

### ISSUE THREAD

**Issue by tiansiyuan** [InternLM/InternLM#187]
### Describe the feature

As I am using a environment in Docker, so I can not run docker inside. 

Is it possible to provide the Dockerfile for this image so that I can install required software without using Docker?

Thanks,

Tian

### Will you implement it?

- [ ] I would like to implement this feature and create a PR!

**Comment by sunpengsdu** [comment]
We will provide the dockerfile later.

**Comment by sunpengsdu** [comment]
hi @tiansiyuan , the dockerfile is ready now. You could check it according to the document https://github.com/InternLM/InternLM/blob/main/doc/en/install.md#environment-image

**Comment by tiansiyuan** [comment]
> hi @tiansiyuan , the dockerfile is ready now. You could check it according to the document https://github.com/InternLM/InternLM/blob/main/doc/en/install.md#environment-image

Thank you. I will have a try.

**Comment by tiansiyuan** [comment]
Following the Makefile & Dockerfile, I can make it run training.

There is some problem with the running, I will report in another issue.

in the install.md file, the following part is duplicate with the commands in the Docker file. which means, if the user chooses to use Docker, the following part is not needed.

It is recommended to build a Python-3.10 virtual environment using conda and install the required dependencies based on the requirements/ files:

conda create --name internlm-env python=3.10 -y
conda activate internlm-env
cd internlm
pip install -r requirements/torch.txt 
pip install -r requirements/runtime.txt 

Install flash-attention (version v1.0.5):

cd ./third_party/flash-attention
python setup.py install
cd ./csrc
cd fused_dense_lib && pip install -v .
cd ../xentropy && pip install -v .
cd ../rotary && pip install -v .
cd ../layer_norm && pip install -v .
cd ../../../../

Install Apex (version 23.05):

cd ./third_party/apex
pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
cd ../../
