### ISSUE TITLE
[Bug] sft后模型推理出现乱码

### ISSUE THREAD

**Issue by killandy** [InternLM/InternLM#191]
### 描述该错误

在internlm-7B基础上用自己的sft数据训练，并转化为hf格式，加载模型进行推理，结果出现乱码
![image](https://github.com/InternLM/InternLM/assets/44628671/470ab99a-ae95-48df-b706-54d456237955)

### 环境信息

```
response, history = model.chat(tokenizer, "please provide three suggestions about time management", history-history)
```

### 其他信息

sft数据是参考中的alpaca_tokenizer进行处理的，读取部分脚本为：
```
with open(dataset_path, "r", encoding="utf-8") as f:
        for line in f:
            data = json.loads(line)
            yield tokenize(data["messages"], sp_model)
```

在8A100上训练，参数参考7B_sft.py，仅修改了bsz和step部分：
```
    micro_num=16,
    micro_bsz=2,
    total_steps=8670,
```

**Comment by MeowZheng** [comment]
Please try to load the model weights that we released to check if there is a problem with string decoding.
Moreover, please try to decode the your model response like `response.decode('utf-8')`

**Comment by killandy** [comment]
1. 用官方release model可以正常运行，输出无乱码。
<img width="1120" alt="image" src="https://github.com/InternLM/InternLM/assets/44628671/eb2933ff-8ff0-43ae-8966-0b5923d36a91">

2. 关于response用```response.decode('utf-8')```解码，上面的response我已尝试多次，也无法正确decode。


3. 另外这次再尝试load微调的模型时，出现新的问题，会遇到错误
```
ImportError: This modeling file requires the following packages that were not found in your environment: configuration_internlm. Run `pip install configuration_internlm`
```
我通过export PYTHONPATH=$PWD:$PYTHONPATH，把模型所在目录加入了环境变量进行解决，但不知这个是否有影响。

并且，这次我load后，发现模型根本没有输出，response为空。
