### ISSUE TITLE
 'InternLMModel' object has no attribute 'chat'

### ISSUE THREAD

**Issue by vprelovac** [InternLM/InternLM#2]
The example does not work

response, history = model.chat(tokenizer, "hello", history=[])
>> AttributeError: 'InternLMModel' object has no attribute 'chat'

**Comment by 00INDEX** [comment]
@vprelovac Hi, The chat feature is only available for CausalLM. So you should use ``AutoModelForCausalLM`` instead of ``AutoModel``:

```python

from transformers import AutoModelForCausalLM
 model = AutoModelForCausalLM.from_pretrained("internlm/internlm-chat-7b", trust_remote_code=True).cuda()

```
