### ISSUE TITLE
[QA] 使用InternLM Chat 7B 8k模型有时候输出结果会一直重复

### ISSUE THREAD

**Issue by xxy012** [InternLM/InternLM#205]
### Describe the question.

使用InternLM Chat 7B 8k模型有时候输出结果会一直重复

**Comment by yhcc** [comment]
可以麻烦提供一些输入的prompt吗？这样也方便我们debug一些~

**Comment by kkscilife** [comment]
> 可以麻烦提供一些输入的prompt吗？这样也方便我们debug一些~

应该是会话内容超过Max Length了，比如使用web端方式，调整max length，超过之后会重复，如果清除历史记录，输入同样promt，回答比较正常
![image](https://github.com/InternLM/InternLM/assets/126147887/02e10aa8-348c-40e0-81d2-cf63f74efb6d)
web端log提示：
Input length of input_ids is 427, but `max_length` is set to 277. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.
Input length of input_ids is 447, but `max_length` is set to 277. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.
Input length of input_ids is 468, but `max_length` is set to 277. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.
Input length of input_ids is 489, but `max_length` is set to 277. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.

**Comment by xxy012** [comment]
> 可以麻烦提供一些输入的prompt吗？这样也方便我们debug一些~

prompt = """你是一名专业的智能客服，已知信息：{context} 根据上述已知信息，简洁和专业的来回答用户的问题。如果无法从中得到答案，请说 “根据已知信息无法回答该问题” 或 “没有提供足够的相关信息”，不允许在答案中添加编造成分，答案请使用中文。 问题是：{question}"""
