### ISSUE TITLE
internlm是否支持扩充词表

### ISSUE THREAD

**Issue by wuzeyuuu** [InternLM/InternLM#209]
### Describe the bug

我扩充了词表，从10万增加到11万左右，主要是一些专有领域名词，但是在训练的时候报 Assertion `srcIndex < srcSelectDimSize` failed.
![image](https://github.com/InternLM/InternLM/assets/67555631/15f84ff9-a8e2-4aa1-8bb0-c096ba563261)

### Environment

CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6 torchrun --nnodes=1 --nproc_per_node=7 train.py --config ./configs/my_7B_sft.py --launcher "torch" 2>&1 | tee -i "$src/train_log_$current_date_time.txt"

**Comment by gaoyang07** [comment]
Did you modify the variable `VOCAB_SIZE` in config accordingly? If so, please check your tokenized data further, I believe something goes wrong with your data.

**Comment by wuzeyuuu** [comment]
Thank you for your reply!I has solved this by your method. But when I go on I met another bug, and it confused me, the 'strict' parameters is already false, it shouldn't report this bug, why it occured?
Is that mean I cannot change the dimension of input? Or I need to train a new model instead of SFT?







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yang ***@***.***&gt;; 
发送时间: 2023年8月18日(星期五) 下午2:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [InternLM/InternLM] internlm是否支持扩充词表 (Issue #209)





 
Did you modify the variable VOCAB_SIZE in config accordingly? If so, please check your tokenized data further, I believe something goes wrong with your data.

**Comment by wuzeyuuu** [comment]
![image](https://github.com/InternLM/InternLM/assets/67555631/cd6048bf-0e86-4633-9d7d-c813f3c8f06c)
the bug after correct vocab size

**Comment by wuzeyuuu** [comment]
![image](https://github.com/InternLM/InternLM/assets/67555631/95f404b4-a8d5-4379-b0d1-e2f41f7c8b88)
the bug after correct vocab size

**Comment by wuzeyuuu** [comment]
I have an idea, there is many unused character tokens, can I replace them by my vocab

**Comment by obangw** [comment]
Could you please share the scripts you used to expand your vocabulary? I'm uncertain whether the issue is related to this.

**Comment by wuzeyuuu** [comment]
> Could you please share the scripts you used to expand your vocabulary? I'm uncertain whether the issue is related to this.

https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E8%AE%AD%E7%BB%83%E7%BB%86%E8%8A%82#%E5%87%86%E5%A4%87%E5%B7%A5%E4%BD%9C%E8%AF%8D%E8%A1%A8%E6%89%A9%E5%85%85
I use this guide

**Comment by obangw** [comment]
> I have an idea, there is many unused character tokens, can I replace them by my vocab
Of course. But it seems that the number of UNUSED_TOKEN is not enough, you may still need to add new tokens.

**Comment by obangw** [comment]
Maybe you can try this:
Add this line at line 43 of [merge_tokenizer.py.](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/75f89d3c056e76a986e5faffe5664e35ea107150/scripts/merge_tokenizer/merge_tokenizers.py#L43)
`llama_spm.trainer_spec.vocab_size = len(llama_spm.pieces)` 
I not sure whether this bug is caused by this.

> > Could you please share the scripts you used to expand your vocabulary? I'm uncertain whether the issue is related to this.
> 
> https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E8%AE%AD%E7%BB%83%E7%BB%86%E8%8A%82#%E5%87%86%E5%A4%87%E5%B7%A5%E4%BD%9C%E8%AF%8D%E8%A1%A8%E6%89%A9%E5%85%85 I use this guide

**Comment by wuzeyuuu** [comment]
> Maybe you can try this: Add this line at line 43 of [merge_tokenizer.py.](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/75f89d3c056e76a986e5faffe5664e35ea107150/scripts/merge_tokenizer/merge_tokenizers.py#L43) `llama_spm.trainer_spec.vocab_size = len(llama_spm.pieces)` I not sure whether this bug is caused by this.
> 
> > > Could you please share the scripts you used to expand your vocabulary? I'm uncertain whether the issue is related to this.
> > 
> > 
> > https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E8%AE%AD%E7%BB%83%E7%BB%86%E8%8A%82#%E5%87%86%E5%A4%87%E5%B7%A5%E4%BD%9C%E8%AF%8D%E8%A1%A8%E6%89%A9%E5%85%85 I use this guide

It means nothing...

**Comment by YWMditto** [comment]
You should not only expand your tokenizer's vocab, but also the embedding and the output head of the model.
For example, if your vocab size is 200,000, you should also expand the embedding, so that its size is [200,000, hidden_size] instead of [103168, hidden_size].

Your can use the following code to expand the embedding and head, the logic is very simple, if the token of your new tokenizer is in the old tokenizer(for example, internlm's), then we directly use the weight of the old embedding, otherwise, we can random initialize its weight.

```
import torch
from pathlib import Path
from sentencepiece import SentencePieceProcessor


def find_matched_vocab(old_vocab, new_vocab):
    reversed_old_vocab = dict((v, k) for k, v in old_vocab.items())
    matched_vocab = {}
    num_matched = 0
    num_mismatched = 0
    for new_idx, token in new_vocab.items():
        if token in reversed_old_vocab:
            old_idx = reversed_old_vocab[token]
            matched_vocab[token] = old_idx
            num_matched += 1
        else:
            num_mismatched += 1
            matched_vocab[token] = None

    print(f"num_matched: {num_matched}, num_mismatched: {num_mismatched}")
    return matched_vocab


def init_embedding_and_weight(matched_vocab, old_embeddings, old_heads):
    new_embeddings = []
    new_heads = []

    hidden_size = old_embeddings.shape[1]
    dtype = old_embeddings.dtype
    for _, (token, old_idx) in enumerate(matched_vocab.items()):
        if old_idx is None:
            new_embedding = torch.normal(mean=0, std=0.02, size=(1, hidden_size), dtype=dtype)
            new_head = torch.normal(mean=0, std=0.02, size=(1, hidden_size), dtype=dtype)
        else:
            new_embedding = old_embeddings[old_idx].view(1, -1).to(dtype)
            new_head = old_heads[old_idx].view(1, -1).to(dtype)
        new_embeddings.append(new_embedding)
        new_heads.append(new_head)

    new_embeddings = torch.cat(new_embeddings, dim=0).cpu()
    new_heads = torch.cat(new_heads, dim=0).cpu()
    return new_embeddings, new_heads


def expand_vocab(old_tokenizer_path, new_tokenizer_path, pretrained_model_cache_dir, save_dir):

    old_tokenizer: SentencePieceProcessor = SentencePieceProcessor(old_tokenizer_path)
    new_tokenizer: SentencePieceProcessor = SentencePieceProcessor(new_tokenizer_path)
    old_vocab = dict((i, old_tokenizer.id_to_piece(i)) for i in range(old_tokenizer.vocab_size()))
    new_vocab = dict((i, new_tokenizer.id_to_piece(i)) for i in range(new_tokenizer.vocab_size()))
    matched_vocab = find_matched_vocab(old_vocab, new_vocab)

    pretrained_model_cache_dir = Path(pretrained_model_cache_dir)

    embedding_split_weights = None
    head_split_weights = None

    for file_path in pretrained_model_cache_dir.iterdir():
        if file_path.name.endswith(".bin"):
            cur_split_weights = torch.load(file_path, map_location="cpu")
            if "model.embed_tokens.weight" in cur_split_weights:
                embedding_split_weights = (file_path.name, cur_split_weights)
            if "lm_head.weight" in cur_split_weights:
                head_split_weights = (file_path.name, cur_split_weights)
            if embedding_split_weights is not None and head_split_weights is not None:
                break

    new_embeddings, new_heads = init_embedding_and_weight(matched_vocab, embedding_split_weights[1]["model.embed_tokens.weight"], head_split_weights[1]["lm_head.weight"])

    save_dir = Path(save_dir)
    save_dir.mkdir(exist_ok=True, parents=True)
    embedding_split_weights[1]["model.embed_tokens.weight"] = new_embeddings
    head_split_weights[1]["lm_head.weight"] = new_heads

    torch.save(embedding_split_weights[1], save_dir.joinpath(embedding_split_weights[0]))
    torch.save(head_split_weights[1], save_dir.joinpath(head_split_weights[0]))

```

**Comment by YWMditto** [comment]
> > Maybe you can try this: Add this line at line 43 of [merge_tokenizer.py.](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/75f89d3c056e76a986e5faffe5664e35ea107150/scripts/merge_tokenizer/merge_tokenizers.py#L43) `llama_spm.trainer_spec.vocab_size = len(llama_spm.pieces)` I not sure whether this bug is caused by this.
> > > > Could you please share the scripts you used to expand your vocabulary? I'm uncertain whether the issue is related to this.
> > > 
> > > 
> > > https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E8%AE%AD%E7%BB%83%E7%BB%86%E8%8A%82#%E5%87%86%E5%A4%87%E5%B7%A5%E4%BD%9C%E8%AF%8D%E8%A1%A8%E6%89%A9%E5%85%85 I use this guide
> 
> It means nothing...



> You should not only expand your tokenizer's vocab, but also the embedding and the output head of the model. For example, if your vocab size is 200,000, you should also expand the embedding, so that its size is [200,000, hidden_size] instead of [103168, hidden_size].
> 
> Your can use the following code to expand the embedding and head, the logic is very simple, if the token of your new tokenizer is in the old tokenizer(for example, internlm's), then we directly use the weight of the old embedding, otherwise, we can random initialize its weight.
> 
> ```
> import torch
> from pathlib import Path
> from sentencepiece import SentencePieceProcessor
> 
> 
> def find_matched_vocab(old_vocab, new_vocab):
>     reversed_old_vocab = dict((v, k) for k, v in old_vocab.items())
>     matched_vocab = {}
>     num_matched = 0
>     num_mismatched = 0
>     for new_idx, token in new_vocab.items():
>         if token in reversed_old_vocab:
>             old_idx = reversed_old_vocab[token]
>             matched_vocab[token] = old_idx
>             num_matched += 1
>         else:
>             num_mismatched += 1
>             matched_vocab[token] = None
> 
>     print(f"num_matched: {num_matched}, num_mismatched: {num_mismatched}")
>     return matched_vocab
> 
> 
> def init_embedding_and_weight(matched_vocab, old_embeddings, old_heads):
>     new_embeddings = []
>     new_heads = []
> 
>     hidden_size = old_embeddings.shape[1]
>     dtype = old_embeddings.dtype
>     for _, (token, old_idx) in enumerate(matched_vocab.items()):
>         if old_idx is None:
>             new_embedding = torch.normal(mean=0, std=0.02, size=(1, hidden_size), dtype=dtype)
>             new_head = torch.normal(mean=0, std=0.02, size=(1, hidden_size), dtype=dtype)
>         else:
>             new_embedding = old_embeddings[old_idx].view(1, -1).to(dtype)
>             new_head = old_heads[old_idx].view(1, -1).to(dtype)
>         new_embeddings.append(new_embedding)
>         new_heads.append(new_head)
> 
>     new_embeddings = torch.cat(new_embeddings, dim=0).cpu()
>     new_heads = torch.cat(new_heads, dim=0).cpu()
>     return new_embeddings, new_heads
> 
> 
> def expand_vocab(old_tokenizer_path, new_tokenizer_path, pretrained_model_cache_dir, save_dir):
> 
>     old_tokenizer: SentencePieceProcessor = SentencePieceProcessor(old_tokenizer_path)
>     new_tokenizer: SentencePieceProcessor = SentencePieceProcessor(new_tokenizer_path)
>     old_vocab = dict((i, old_tokenizer.id_to_piece(i)) for i in range(old_tokenizer.vocab_size()))
>     new_vocab = dict((i, new_tokenizer.id_to_piece(i)) for i in range(new_tokenizer.vocab_size()))
>     matched_vocab = find_matched_vocab(old_vocab, new_vocab)
> 
>     pretrained_model_cache_dir = Path(pretrained_model_cache_dir)
> 
>     embedding_split_weights = None
>     head_split_weights = None
> 
>     for file_path in pretrained_model_cache_dir.iterdir():
>         if file_path.name.endswith(".bin"):
>             cur_split_weights = torch.load(file_path, map_location="cpu")
>             if "model.embed_tokens.weight" in cur_split_weights:
>                 embedding_split_weights = (file_path.name, cur_split_weights)
>             if "lm_head.weight" in cur_split_weights:
>                 head_split_weights = (file_path.name, cur_split_weights)
>             if embedding_split_weights is not None and head_split_weights is not None:
>                 break
> 
>     new_embeddings, new_heads = init_embedding_and_weight(matched_vocab, embedding_split_weights[1]["model.embed_tokens.weight"], head_split_weights[1]["lm_head.weight"])
> 
>     save_dir = Path(save_dir)
>     save_dir.mkdir(exist_ok=True, parents=True)
>     embedding_split_weights[1]["model.embed_tokens.weight"] = new_embeddings
>     head_split_weights[1]["lm_head.weight"] = new_heads
> 
>     torch.save(embedding_split_weights[1], save_dir.joinpath(embedding_split_weights[0]))
>     torch.save(head_split_weights[1], save_dir.joinpath(head_split_weights[0]))
> ```

@wuzeyuuu

**Comment by wuzeyuuu** [comment]
> You should not only expand your tokenizer's vocab, but also the embedding and the output head of the model. For example, if your vocab size is 200,000, you should also expand the embedding, so that its size is [200,000, hidden_size] instead of [103168, hidden_size].
> 
> Your can use the following code to expand the embedding and head, the logic is very simple, if the token of your new tokenizer is in the old tokenizer(for example, internlm's), then we directly use the weight of the old embedding, otherwise, we can random initialize its weight.
> 
> ```
> import torch
> from pathlib import Path
> from sentencepiece import SentencePieceProcessor
> 
> 
> def find_matched_vocab(old_vocab, new_vocab):
>     reversed_old_vocab = dict((v, k) for k, v in old_vocab.items())
>     matched_vocab = {}
>     num_matched = 0
>     num_mismatched = 0
>     for new_idx, token in new_vocab.items():
>         if token in reversed_old_vocab:
>             old_idx = reversed_old_vocab[token]
>             matched_vocab[token] = old_idx
>             num_matched += 1
>         else:
>             num_mismatched += 1
>             matched_vocab[token] = None
> 
>     print(f"num_matched: {num_matched}, num_mismatched: {num_mismatched}")
>     return matched_vocab
> 
> 
> def init_embedding_and_weight(matched_vocab, old_embeddings, old_heads):
>     new_embeddings = []
>     new_heads = []
> 
>     hidden_size = old_embeddings.shape[1]
>     dtype = old_embeddings.dtype
>     for _, (token, old_idx) in enumerate(matched_vocab.items()):
>         if old_idx is None:
>             new_embedding = torch.normal(mean=0, std=0.02, size=(1, hidden_size), dtype=dtype)
>             new_head = torch.normal(mean=0, std=0.02, size=(1, hidden_size), dtype=dtype)
>         else:
>             new_embedding = old_embeddings[old_idx].view(1, -1).to(dtype)
>             new_head = old_heads[old_idx].view(1, -1).to(dtype)
>         new_embeddings.append(new_embedding)
>         new_heads.append(new_head)
> 
>     new_embeddings = torch.cat(new_embeddings, dim=0).cpu()
>     new_heads = torch.cat(new_heads, dim=0).cpu()
>     return new_embeddings, new_heads
> 
> 
> def expand_vocab(old_tokenizer_path, new_tokenizer_path, pretrained_model_cache_dir, save_dir):
> 
>     old_tokenizer: SentencePieceProcessor = SentencePieceProcessor(old_tokenizer_path)
>     new_tokenizer: SentencePieceProcessor = SentencePieceProcessor(new_tokenizer_path)
>     old_vocab = dict((i, old_tokenizer.id_to_piece(i)) for i in range(old_tokenizer.vocab_size()))
>     new_vocab = dict((i, new_tokenizer.id_to_piece(i)) for i in range(new_tokenizer.vocab_size()))
>     matched_vocab = find_matched_vocab(old_vocab, new_vocab)
> 
>     pretrained_model_cache_dir = Path(pretrained_model_cache_dir)
> 
>     embedding_split_weights = None
>     head_split_weights = None
> 
>     for file_path in pretrained_model_cache_dir.iterdir():
>         if file_path.name.endswith(".bin"):
>             cur_split_weights = torch.load(file_path, map_location="cpu")
>             if "model.embed_tokens.weight" in cur_split_weights:
>                 embedding_split_weights = (file_path.name, cur_split_weights)
>             if "lm_head.weight" in cur_split_weights:
>                 head_split_weights = (file_path.name, cur_split_weights)
>             if embedding_split_weights is not None and head_split_weights is not None:
>                 break
> 
>     new_embeddings, new_heads = init_embedding_and_weight(matched_vocab, embedding_split_weights[1]["model.embed_tokens.weight"], head_split_weights[1]["lm_head.weight"])
> 
>     save_dir = Path(save_dir)
>     save_dir.mkdir(exist_ok=True, parents=True)
>     embedding_split_weights[1]["model.embed_tokens.weight"] = new_embeddings
>     head_split_weights[1]["lm_head.weight"] = new_heads
> 
>     torch.save(embedding_split_weights[1], save_dir.joinpath(embedding_split_weights[0]))
>     torch.save(head_split_weights[1], save_dir.joinpath(head_split_weights[0]))
> ```

niubi
