### ISSUE TITLE
Installation per requirements/torch.txt error

### ISSUE THREAD

**Issue by happy15** [InternLM/InternLM#21]
Hi, I tried to install per requirements/torch.txt and got following errors. Anything did I miss?

```
 ➜  InternLM git:(main) pip install -r requirements/torch.txt 
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu117
ERROR: Could not find a version that satisfies the requirement torch==1.13.1+cu117 (from versions: 2.0.0, 2.0.1)
ERROR: No matching distribution found for torch==1.13.1+cu117
```

My environment is:
- macOS 13.4.1
- python 3.11
- venv

**Comment by BUPT-NingXinyu** [comment]
Perhaps macOS does not support cuda, you can try installing a version that supports OSX

`pip install torch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1`

**Comment by cicada0007** [comment]
Hi @happy15 ✋ 

I came across this issue and fixed it  You can review it

Thank you

#44

**Comment by happy15** [comment]
> Perhaps macOS does not support cuda, you can try installing a version that supports OSX
> 
> `pip install torch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1`

Thanks for the suggestion. Turns out your solution works with python 3.10 but not 3.11.

**Comment by happy15** [comment]
> Hi @happy15 ✋
> 
> I came across this issue and fixed it You can review it
> 
> Thank you
> 
> #44

Thanks for the suggestion. I'll stick with the solution via @BUPT-NingXinyu for now.

**Comment by happy15** [comment]
> > Perhaps macOS does not support cuda, you can try installing a version that supports OSX
> > `pip install torch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1`
> 
> Thanks for the suggestion. Turns out your solution works with python 3.10 but not 3.11.

Turns out, 16GB ram is far from enough to run.
