### ISSUE TITLE
[Feature] 希望支持：启动训练前自动寻找可用端口

### ISSUE THREAD

**Issue by kkscilife** [InternLM/InternLM#235]
### 描述该功能

训练时会碰到端口已占用问题，需要换端口重新提交，如果新端口也被占用仍需要再次尝试，使用体验不好，希望增加自动寻找可用端口的功能；若用户指定了端口，可以先校验端口是否已被占用，若已被占用可自动寻找新端口
<img width="710" alt="企业微信截图_16929299678512" src="https://github.com/InternLM/InternLM/assets/126147887/a8ab3d01-1e80-445d-af82-b009805b39ea">

### 是否希望自己实现该功能？

- [ ] 我希望自己来实现这一功能，并向 InternLM 贡献代码！

**Comment by sunpengsdu** [comment]
这个问题，我建议还是不要自动搜寻了。因为Internlm主要是服务大规模训练的，在集群上出现这个问题，基本是因为有资源竞争，或者有残留任务没有清理干净。默认端口有冲突，其实算是一种自我保护了

**Comment by kkscilife** [comment]
保持现状吧
