### ISSUE TITLE
建议换个docker image名称

### ISSUE THREAD

**Issue by kkscilife** [InternLM/InternLM#236]
### 描述该功能

![image](https://github.com/InternLM/InternLM/assets/126147887/527e6488-85f8-4e57-8956-de0a150109ab)
镜像名称最好是非个人的

### 是否希望自己实现该功能？

- [ ] 我希望自己来实现这一功能，并向 InternLM 贡献代码！

**Comment by sunpengsdu** [comment]
fixed in https://github.com/InternLM/InternLM/pull/220

**Comment by kkscilife** [comment]
当前最新为internlm
