### ISSUE TITLE
[Bug] position embedding 在进入buffer后会跟随model 改为bfloat16 

### ISSUE THREAD

**Issue by ngc7292** [InternLM/InternLM#237]
### 描述该错误

position embedding 在进入buffer后会跟随model 改为bfloat16 

<img width="791" alt="截屏2023-08-25 22 47 05" src="https://github.com/InternLM/InternLM/assets/25836491/db14dad1-d4c1-4282-aed9-f38b46c46099">

运行结果

<img width="605" alt="截屏2023-08-25 22 46 08" src="https://github.com/InternLM/InternLM/assets/25836491/b195acb1-7f84-4be3-a83e-144fa38eef4b">

### 环境信息

```
>>> import torch
>>> torch.__version__
'1.13.1+cu117'
```

**Comment by gaoyang07** [comment]
Submit a PR to change the percision type to fp32 in `RotaryEmbedding`.
