### ISSUE TITLE
[Feature] Support openai 兼容脚本

### ISSUE THREAD

**Issue by vansin** [InternLM/InternLM#244]
### Describe the feature

像 ChatGLM2-6B 这样提供一个 openai 兼容脚本

https://github.com/THUDM/ChatGLM2-6B/blob/main/openai_api.py

![image](https://github.com/InternLM/InternLM/assets/25839884/325b2c95-a641-48f9-a44a-5981ed647b26)

https://github.com/Yidadaa/ChatGPT-Next-Web/issues/2723

### Will you implement it?

- [ ] I would like to implement this feature and create a PR!

**Comment by gaoyang07** [comment]
Done.
