### ISSUE TITLE
[question] A100 8card when profile_serving only 95% or 96% Volatile GPU-Util

### ISSUE THREAD

**Issue by changxiaodongTHU** [InternLM/InternLM#248]
### Describe the question.

[question] A100 8card when profile_serving only 95% or 96% Volatile GPU-Util
1.model:turbomind-v0.2.9,v0.2.10-turbomind
2.lmdeploy version: https://github.com/InternLM/lmdeploy/actions/runs/5963312475
 lmdeploy-0.0.5-cp310-cp310-manylinux2014_x86_64.whl
3.benchmark test
python profile_serving.py 10.140.0.187:33337 tokenizer.model ShareGPT_V3_unfiltered_cleaned_split.json --concurrency 48

4.log:
 +-------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-SXM...  On   | 00000000:25:00.0 Off |                    0 |
| N/A   39C    P0   278W / 400W |  70148MiB / 81920MiB |     96%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA A100-SXM...  On   | 00000000:50:00.0 Off |                    0 |
| N/A   40C    P0   276W / 400W |  70148MiB / 81920MiB |     95%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA A100-SXM...  On   | 00000000:55:00.0 Off |                    0 |
| N/A   39C    P0   262W / 400W |  70148MiB / 81920MiB |     95%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   4  NVIDIA A100-SXM...  On   | 00000000:8E:00.0 Off |                    0 |
| N/A   38C    P0   277W / 400W |  70136MiB / 81920MiB |     95%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   5  NVIDIA A100-SXM...  On   | 00000000:93:00.0 Off |                    0 |
| N/A   40C    P0   278W / 400W |  70142MiB / 81920MiB |     95%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   6  NVIDIA A100-SXM...  On   | 00000000:CA:00.0 Off |                    0 |
| N/A   40C    P0   250W / 400W |  70148MiB / 81920MiB |     95%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   7  NVIDIA A100-SXM...  On   | 00000000:D0:00.0 Off |                    0 |
| N/A   38C    P0   280W / 400W |  70014MiB / 81920MiB |     96%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+

model:v0.2.10-turbomind

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.86.01    Driver Version: 515.86.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-SXM...  On   | 00000000:1F:00.0 Off |                    0 |
| N/A   40C    P0   274W / 400W |  56034MiB / 81920MiB |     97%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-SXM...  On   | 00000000:25:00.0 Off |                    0 |
| N/A   42C    P0   270W / 400W |  56156MiB / 81920MiB |     97%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA A100-SXM...  On   | 00000000:50:00.0 Off |                    0 |
| N/A   42C    P0   256W / 400W |  56156MiB / 81920MiB |     97%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA A100-SXM...  On   | 00000000:55:00.0 Off |                    0 |
| N/A   41C    P0   276W / 400W |  56156MiB / 81920MiB |     97%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   4  NVIDIA A100-SXM...  On   | 00000000:8E:00.0 Off |                    0 |
| N/A   40C    P0   259W / 400W |  56144MiB / 81920MiB |     97%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   5  NVIDIA A100-SXM...  On   | 00000000:93:00.0 Off |                    0 |
| N/A   43C    P0   283W / 400W |  56150MiB / 81920MiB |     97%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   6  NVIDIA A100-SXM...  On   | 00000000:CA:00.0 Off |                    0 |
| N/A   42C    P0   272W / 400W |  56156MiB / 81920MiB |     97%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   7  NVIDIA A100-SXM...  On   | 00000000:D0:00.0 Off |                    0 |
| N/A   39C    P0   273W / 400W |  56022MiB / 81920MiB |     97%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+

**Comment by sunpengsdu** [comment]
Hi @changxiaodongTHU , can you open a new issue in the lmdeploy project？ https://github.com/InternLM/lmdeploy/issues

**Comment by changxiaodongTHU** [comment]
ok
