### ISSUE TITLE
[Feature Request] Support llama.cpp deploy

### ISSUE THREAD

**Issue by vansin** [InternLM/InternLM#258]
### Describe the feature

Support llama.cpp deploy

**Comment by AsakusaRinne** [comment]
Has this issue been solved? I'd like to help with it if no one has been working on it now.

**Comment by yanite** [comment]
no  llama.cpp  convert.py missing vocab.json file, @ @

**Comment by CausalLM** [comment]
see https://github.com/ggerganov/llama.cpp/pull/4283

**Comment by ZwwWayne** [comment]
Resolved in https://github.com/InternLM/InternLM/pull/627 after converting the model to llama format.
