### ISSUE TITLE
[Bug] ImportError: This modeling file requires the following packages that were not found in your environment: configuration_internlm. Run `pip install configuration_internlm`

### ISSUE THREAD

**Issue by QichangZheng** [InternLM/InternLM#270]
### Describe the bug

This bug rises recently when running the code provided on huggingface, which was not in previous version.

ImportError: This modeling file requires the following packages that were not found in your environment: configuration_internlm. Run `pip install configuration_internlm`

### Environment

python=3.8
transformers=4.31.0

**Comment by QichangZheng** [comment]
Unless I pass revision='' to fix a previous version. So it seems that there is something wrong with the latest version.

**Comment by fairyshine** [comment]
同样的问题
