### ISSUE TITLE
复读严重

### ISSUE THREAD

**Issue by l15y** [InternLM/InternLM#28]
![image](https://github.com/InternLM/InternLM/assets/11372524/f5c6cc00-4251-43e2-a060-d974de80d750)
是参数不对，还是我调用程序（https://github.com/wenda-LLM/wenda/blob/main/llms/llm_internlm.py ）有问题？

**Comment by ZwwWayne** [comment]
You should set repetition penalty to 1.05 in your program.

**Comment by l15y** [comment]
成功解决

**Comment by xu-song** [comment]
请问怎么解决的？

**Comment by riverind** [comment]
> 成功解决

同样的问题，重复回答，repetition penalty to 1.05，已经设置是1.05了，感谢
