### ISSUE TITLE
[QA] InternLM Chat 7B v1.1和InternLM Chat 7B的区别

### ISSUE THREAD

**Issue by jiangtann** [InternLM/InternLM#288]
### 描述问题

可以看到，InternLM Chat 7B v1.1的修改日期是更加新的，但是并没有介绍InternLM Chat 7B v1.1和InternLM Chat 7B的区别。在[OpenCompass](https://github.com/internLM/OpenCompass/)上也只能看到InternLM Chat 7B的performance但是没有InternLM Chat 7B v1.1的。

InternLM Chat 7B v1.1的整体性能会更优吗？还说是v1.1仅仅是多了code interpreter and function calling能力，其他表现和InternLM Chat 7B基本一致？

**Comment by ZwwWayne** [comment]
Hi @jiangtann ,
You are right. InternLM Chat 7B v1.1 has almost the same (slightly better) overall performance than InternLM Chat 7B. The most important functionality is its code interpreter and function call capability.
