### ISSUE TITLE
why it is different: modeling_internlm.py on hugging face and on github

### ISSUE THREAD

**Issue by forrestsocool** [InternLM/InternLM#31]
The hugging face modeling file: [https://huggingface.co/internlm/internlm-7b/blob/main/modeling_internlm.py](https://huggingface.co/internlm/internlm-7b/blob/main/modeling_internlm.py)

if I train SFT from base model， which modeling file should I use?

thank you!

**Comment by ZwwWayne** [comment]
You can directly use this one. The base model and SFT model share the same model architecture but simply have different parameters.
