### ISSUE TITLE
13b啥时候发布呢？

### ISSUE THREAD

**Issue by xxm1668** [InternLM/InternLM#316]
### 描述该功能

11

### 是否希望自己实现该功能？

- [ ] 我希望自己来实现这一功能，并向 InternLM 贡献代码！

**Comment by Xu-Chen** [comment]
格局大一些，我看之前的财报，说是要开源 20b 的

**Comment by gaoyang07** [comment]
InternLM系列模型的发布时间请以官方更新时间为主～
