### ISSUE TITLE
[QA] 为AccumulateGrad注册一个hook的目的是什么？

### ISSUE THREAD

**Issue by stbianxu** [InternLM/InternLM#323]
### Describe the question.
这部分代码看起来是找到叶子节点的AccumulateGrad，并添加一个hook，应该是为了做完梯度累加之后做梯度的allreduce操作。但是我在跑测的过程中发现并没有执行这个_store_and_try_reduce_grads_by_bucket函数。而在step中显示的执行了grad的all reduce。请问这个hook有什么作用呢？

`        
#
    def _define_and_attach(param, reduce_rank=None):

                        # get the AccumulateGrad object of the param itself
                        # If these objects are not kept, reduction hooks may not be attached successfully.
                        accum_grad_obj = get_grad_accumulate_object(param)
                        self._grad_store.add_accumulate_grad_object(accum_grad_obj)
                        reduction_func = partial(
                            self._store_and_try_reduce_grads_by_bucket,
                            param=param,
                            reduce_rank=reduce_rank,
                        )

                        # define hook
                        # NOT IMPORTANT BUT GOOD TO KNOW:
                        # args here is not grad, but allow_unreacable and accumulate_grad
                        def reduce_grad_hook(*args):  # pylint: disable=W0613
                            if self.skip_grad_reduce is False:
                                reduction_func()
                        accum_grad_obj.register_hook(reduce_grad_hook)
                    _define_and_attach(param, reduce_rank)
`

**Comment by sunpengsdu** [comment]
这部分代码就是为了做backward和grad的allreduce的overlap，可以尝试在reduce_grad_hook里加个print("test reduce_grad_hook is executed", flush=True)验证是否执行

**Comment by sunpengsdu** [comment]
另外它生效需要overlap_sync_grad的配置为true

**Comment by sunpengsdu** [comment]
因为backward阶段触发的allreduce是按照bucket粒度的（grad会先存在bucket里，累积到一定程度触发allreduce），所以说在backward计算结束后，会有遗留的grad还没有触发allreduce，因此需要对这些grad额外一次独立的allreduce，保证全部grad都被通信过了

**Comment by stbianxu** [comment]
好的学习了。多谢

**Comment by QZJ-2003** [comment]
在deepspeed中也存在类似的操作（deepspeed/runtime/zero/stage_1_and_2中），感谢分享讲解
    def create_reduce_and_remove_grad_hooks(self):
        self.grad_accs = []
        for i, param_group in enumerate(self.bit16_groups):
            for param in param_group:
                if param.requires_grad:

                    def wrapper(param, i):
                        # param_tmp is a non-leaf node, so we need to get the grad_fn of the next node
                        param_tmp = param.expand_as(param)
                        # first 0 point to `expand`, second 0 point to `param`'s grad_fn `AccumulateGrad`
                        grad_acc = param_tmp.grad_fn.next_functions[0][0]

                        def reduce_partition_and_remove_grads(*notneeded):
                            self.reduce_ready_partitions_and_remove_grads(param, i)

                        self._grad_acc_hooks.append(grad_acc.register_hook(reduce_partition_and_remove_grads))
                        self.grad_accs.append(grad_acc)

                    wrapper(param, i)
