### ISSUE TITLE
[Feature] add dynamic ntk rope 

### ISSUE THREAD

**Issue by YWMditto** [InternLM/InternLM#327]
### Describe the feature

The extrapolation capabilities of large models can take effect directly in the form of interpolation without requiring more training.
Refer to this blog:
https://www.reddit.com/r/LocalLLaMA/comments/14mrgpr/dynamically_scaled_rope_further_increases/

Reference implementation:
https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/modeling_llama.py#L147

### Will you implement it?

- [X] I would like to implement this feature and create a PR!

**Comment by gaoyang07** [comment]
https://github.com/InternLM/InternLM/pull/339
