### ISSUE TITLE
多卡部署[QA] 

### ISSUE THREAD

**Issue by lelegogo26** [InternLM/InternLM#332]
### Describe the question.

GPU 的显存大小都不足以容纳完整的模型，可以将模型切分在多张GPU上吗，如何实现？

**Comment by lvhan028** [comment]
使用模型并行：tensor parallel，pipeline parallel
目前，[lmdeploy](https://github.com/InternLM/lmdeploy) 在部署 LLM 模型时，使用的是 tensor parallel

**Comment by hwang824** [comment]
> 使用模型并行：tensor parallel，pipeline parallel 目前，[lmdeploy](https://github.com/InternLM/lmdeploy) 在部署 LLM 模型时，使用的是 tensor parallel

能否给出示例代码？比如如何在两个24G显存的消费级显卡上运行20B模型的推理?

**Comment by lvhan028** [comment]
https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/w4a16.md

**Comment by hwang824** [comment]
> https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/w4a16.md

这个示例代码是对模型量化和加载量化模型进行推理的，请问有对原始模型多卡加载推理的示例代码吗？

**Comment by lvhan028** [comment]
@sunpengsdu

**Comment by zhudongwork** [comment]
> > https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/w4a16.md
> 
> 这个示例代码是对模型量化和加载量化模型进行推理的，请问有对原始模型多卡加载推理的示例代码吗？

老哥找到解决方案了吗

**Comment by JinProton** [comment]
老哥，他们这好像不支持多卡推理啊
