### ISSUE TITLE
[QA] InterLM 20B模型原生长度（预训练时长度，非推理时扩展）是多少？

### ISSUE THREAD

**Issue by xyfZzz** [InternLM/InternLM#337]
### Describe the question.

InterLM 20B模型原生长度（预训练时长度，非推理时扩展）是多少？

以及在哪能看到更多的技术细节报告？比如attention方法、位置编码方法等？

**Comment by gaoyang07** [comment]
We trained the 20B model with `SEQ_LEN = 4096`. More details will be released soon. Stay tuned～

**Comment by xyfZzz** [comment]
> We trained the 20B model with `SEQ_LEN = 4096`. More details will be released soon. Stay tuned～

谢谢，但是从你们公众号上看到说“在训练过程中，模型的语境长度分阶段从2K拓展到8K。”，请问到底是4K还是8K长度呀？还是说预训练模型是4K，chat模型是8K吗？
