### ISSUE TITLE
20B-chat目前有量化版吗

### ISSUE THREAD

**Issue by Mr-IT007** [InternLM/InternLM#343]
### Describe the question.

请问20B-chat目前有量化版吗

**Comment by franklyd** [comment]
希望能有小显存卡推理的方案，感谢！

**Comment by lvhan028** [comment]
希望 [lmdeploy](https://github.com/InternLM/lmdeploy) 能够帮到你:)

https://github.com/InternLM/lmdeploy/blob/main/docs/en/w4a16.md
https://github.com/InternLM/lmdeploy/blob/main/docs/en/kv_int8.md
