### ISSUE TITLE
[Bug] internlm-chat-20b部署进行格式转换的时候报错

### ISSUE THREAD

**Issue by rockmecd** [InternLM/InternLM#348]
### 描述该错误

执行命令python -m lmdeploy.serve.turbomind.deploy internlm-chat-20b /internlm-chat-20b时报/internlm-chat-20b\tokenizer.model does not exist，但是文件夹下是有这个文件的

### 环境信息

![image](https://github.com/InternLM/InternLM/assets/8734604/ed954799-2598-4838-914c-1fc10effccea)

![image](https://github.com/InternLM/InternLM/assets/8734604/d4b629d3-672e-4eda-ad4b-fe72a5035363)

**Comment by lvhan028** [comment]
@rockmecd 可以把这个问题提到 https://github.com/InternLM/lmdeploy/issues 下

**Comment by irexyc** [comment]
你传的路径有问题

python -m lmdeploy.serve.turbomind.deploy internlm-chat-20b /internlm-chat-20b

-> 

python -m lmdeploy.serve.turbomind.deploy internlm-chat-20b internlm-chat-20b
