### ISSUE TITLE
[QA] 为什么load model 需要1分钟左右

### ISSUE THREAD

**Issue by XksA-me** [InternLM/InternLM#349]
### Describe the question.

显卡：A4000

运行日志：
![image](https://github.com/InternLM/InternLM/assets/43670614/ead332eb-2830-4b66-9090-71313a5d88c4)

求解答和优化

其他没问题，模型推理速度蛮快的，显存占用 14g+ 
![image](https://github.com/InternLM/InternLM/assets/43670614/8c159063-a338-48a9-be16-49b70dd6c221)
内存好像是读到显存后就释放了，启动后只有不到1g
![image](https://github.com/InternLM/InternLM/assets/43670614/df5579b6-dd55-4f3e-91a0-0e8bf6c4f53f)

**Comment by XksA-me** [comment]
模型加载的时候内存最高可以到30g
![image](https://github.com/InternLM/InternLM/assets/43670614/f586c93d-b73b-48f8-be3a-2133856d897b)

**Comment by chidaodebianyuan** [comment]
请问推理速度有多快呢，我在A10显卡上加载模型和推理大概都在1min，有什么办法加速吗

**Comment by ZwwWayne** [comment]
We suggest using [LMDeploy](https://github.com/InternLM/lmdeploy).

**Comment by lvhan028** [comment]
@XksA-me 是用 transformers load 模型的吗？
@chidaodebianyuan 可以使用 lmdeploy 4bit 模型量化和推理。参考文档：https://github.com/InternLM/lmdeploy/blob/main/docs/en/w4a16.md
社区部署了一个4bit推理demo：https://huggingface.co/spaces/BridgeEight/internlm-20B-chat-w4-turbomind，可以体验下推理效率。

**Comment by hunter-xue** [comment]
我用4张A10，在text-generation-webui中加载也是差不多的时间，个人理解，这个应该是没法加速的。毕竟加载一次之后，不再需要频繁的重复加载吧。
