### ISSUE TITLE
Some documentation is missing

### ISSUE THREAD

**Issue by ZwwWayne** [InternLM/InternLM#35]
1. Do we need documentation in the readthedocs of this repository?
2. The contributing guideline such as https://github.com/InternLM/opencompass/blob/main/docs/en/notes/contribution_guide.md is missing, community may have issue in contributing to this project.
3. A better documentation structure following https://github.com/internlm/opencompass/tree/main/docs is more helpful to users.

**Comment by hellock** [comment]
These should be prepared in the next few days.

**Comment by sunpengsdu** [comment]
We are doing this one in https://github.com/InternLM/InternLM/pull/245
