### ISSUE TITLE
[Bug] lmdeploy部署的internlm-20b推理的胡言乱语

### ISSUE THREAD

**Issue by mumuszhang** [InternLM/InternLM#350]
### 描述该错误

lmdeploy部署的internlm-20b推理的胡言乱语

### 环境信息

<img width="1468" alt="1" src="https://github.com/InternLM/InternLM/assets/13376020/6ca9d098-85ab-4cde-8b5f-dc7850eea743">

**Comment by lvhan028** [comment]
@mumuszhang issue请提到 https://github.com/InternLM/lmdeploy/issues 吧。
麻烦写一下复现路径。

**Comment by lvhan028** [comment]
@ZwwWayne This issue can be closed since @mumuszhang has posted it to lmdeploy
