### ISSUE TITLE
[QA] 预训练数据

### ISSUE THREAD

**Issue by ii35322** [InternLM/InternLM#355]
### Describe the question.

您好，请问有提供internLM7B或者internLM20B的预训练数据吗？

**Comment by gaoyang07** [comment]
你好～我们在持续开源模型训练的各类语料，可以关注OpenDataLab获取更多信息，语料库请参考：https://opendatalab.org.cn/?mediaTypes=5

**Comment by ii35322** [comment]
您好～我知道目前有這個WanJuan1.0開源数据集，請問internLM-7B、internLM-20B是用這個数据訓練嗎？還是另外還有預訓練数据集會開源？

**Comment by ZwwWayne** [comment]
InternLM is trained on data more than Wanjuan 1.0. The data will be released in the future, please stay tuned.
