### ISSUE TITLE
怎么进行 8bit 量化加载？ 

### ISSUE THREAD

**Issue by hanswang73** [InternLM/InternLM#357]
### Describe the question.

怎么进行 8bit 量化加载？

**Comment by ZwwWayne** [comment]
Invite @lvhan028 to take a look.

**Comment by syan2018** [comment]
安装bitsandbytes，然后 AutoModelForCausalLM.from_pretrained("", load_in_8bit=True)

**Comment by lvhan028** [comment]
lmdeploy还不支持8bit权重量化

**Comment by hanswang73** [comment]
> lmdeploy还不支持8bit权重量化

那能用上面说的 bitsandbytes / load_in_8bit=True 的方法吗？

**Comment by lvhan028** [comment]
> > lmdeploy还不支持8bit权重量化
> 
> 那能用上面说的 bitsandbytes / load_in_8bit=True 的方法吗？

还不行
