### ISSUE TITLE
模型乱说话[QA] 

### ISSUE THREAD

**Issue by liyunhan** [InternLM/InternLM#361]
### Describe the question.

使用Huggingface加载的模型，调用官方示例。
query = '你好'
response, history = model.chat(tokenizer, query, max_new_tokens=200)
print(response)
query = '介绍下北京'
response, history = model.chat(tokenizer, query, history, max_new_tokens=200)
print(response)

模型给出的回答：
你好！有什么可以帮到你的吗？ 需要 提供 1 到 3 个 有 关 本 题 的 上 下 文 或 内 容 ， 我 会 以 最 快 的 速 度 给 你  回 答 。 1 、 1 5 年 1 2 月 1 1 日 ， 1 2 月 1 1 日 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
1 、 1 5 年 1 2 月 1 1 日 ， 1 2 月 1 1 日 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1

**Comment by 00INDEX** [comment]
您好，可否给出更详细的加载代码？根据观察到的现象，您可能是使用了base model。当使用`model.chat()`功能时，应该使用chat model而不是base model，也就是应当使用`internlm/internlm-chat-20b`而不是`internlm/internlm-20b`。

**Comment by liyunhan** [comment]
`import os.path

import torch
from modelscope import AutoModelForCausalLM, AutoTokenizer

model_dir = os.path.abspath('internlm-chat-20b')
tokenizer = AutoTokenizer.from_pretrained(model_dir, trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained(model_dir, device_map="auto", torch_dtype=torch.bfloat16, trust_remote_code=True).eval()

while True:
    query = input("请输入问题：")
    chat_generator = model.stream_chat(tokenizer, query, temperature=0.3, top_p=0.90)
    print("回答：", end='', flush=True)
    print_idx = 0
    for response, history in chat_generator:
        print(response[print_idx:], end='', flush=True)
        print_idx = len(response)
    print()
`
我下载的是chat模型，温度系数等等都设置的默认。

**Comment by ericg108** [comment]
我这边的测试发现，和internlm7b-chat一样，20b-chat仍然会有 生成重复问题，是不是repetition_penalty的参数默认值不大合适啊？
