### ISSUE TITLE
[Bug] ImportError: cannot import name 'CodeLlamaTokenizerFast' from 'transformers' 

### ISSUE THREAD

**Issue by rayqi36** [InternLM/InternLM#364]
### Describe the bug

 我的环境是python3.10，transformer的环境是 4.30.2，执行python -m lmdeploy.serve.gradio.app ./workspace/ --tp 2 的时候，报了下面的错，请问是哪里有问题吗
 
Traceback (most recent call last):
  File "/data/miniconda3/envs/internlm/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/miniconda3/envs/internlm/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data/miniconda3/envs/internlm/lib/python3.10/site-packages/lmdeploy/serve/gradio/app.py", line 541, in <module>
    fire.Fire(run)
  File "/data/miniconda3/envs/internlm/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/data/miniconda3/envs/internlm/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/data/miniconda3/envs/internlm/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/data/miniconda3/envs/internlm/lib/python3.10/site-packages/lmdeploy/serve/gradio/app.py", line 536, in run
    run_local(model_path_or_server, server_name, server_port, batch_size,
  File "/data/miniconda3/envs/internlm/lib/python3.10/site-packages/lmdeploy/serve/gradio/app.py", line 461, in run_local
    InterFace.async_engine = AsyncEngine(model_path=model_path,
  File "/data/miniconda3/envs/internlm/lib/python3.10/site-packages/lmdeploy/serve/async_engine.py", line 36, in __init__
    tokenizer = Tokenizer(tokenizer_model_path)
  File "/data/miniconda3/envs/internlm/lib/python3.10/site-packages/lmdeploy/turbomind/tokenizer.py", line 243, in __init__
    self.model = HuggingFaceTokenizer(model_folder)
  File "/data/miniconda3/envs/internlm/lib/python3.10/site-packages/lmdeploy/turbomind/tokenizer.py", line 114, in __init__
    from transformers import (AutoTokenizer, CodeLlamaTokenizerFast,
ImportError: cannot import name 'CodeLlamaTokenizerFast' from 'transformers' (/data/miniconda3/envs/internlm/lib/python3.10/site-packages/transformers/__init__.py)

### Environment

accelerate                0.23.0
addict                    2.4.0
aiofiles                  23.2.1
aiohttp                   3.8.5
aiosignal                 1.3.1
altair                    5.1.1
annotated-types           0.5.0
anyio                     3.7.1
async-timeout             4.0.3
attrs                     23.1.0
blinker                   1.6.2
Brotli                    1.1.0
cachetools                5.3.1
certifi                   2023.7.22
charset-normalizer        3.2.0
click                     8.1.7
cmake                     3.27.5
contourpy                 1.1.1
cuda-python               12.2.0
cycler                    0.11.0
Cython                    3.0.2
datasets                  2.14.5
dill                      0.3.7
exceptiongroup            1.1.3
fastapi                   0.103.1
ffmpy                     0.3.1
filelock                  3.12.4
fire                      0.5.0
fonttools                 4.42.1
frozenlist                1.4.0
fsspec                    2023.6.0
furnace                   0.0.10
gevent                    23.9.1
geventhttpclient          2.0.2
gitdb                     4.0.10
GitPython                 3.1.37
gradio                    3.44.4
gradio_client             0.5.1
greenlet                  2.0.2
grpcio                    1.58.0
h11                       0.14.0
httpcore                  0.18.0
httpx                     0.25.0
huggingface-hub           0.17.2
idna                      3.4
importlib-metadata        6.8.0
importlib-resources       6.1.0
Jinja2                    3.1.2
jsonschema                4.19.1
jsonschema-specifications 2023.7.1
kiwisolver                1.4.5
lit                       16.0.6
lmdeploy                  0.0.9
markdown-it-py            3.0.0
MarkupSafe                2.1.3
matplotlib                3.8.0
mdurl                     0.1.2
mmengine                  0.8.4
mpmath                    1.3.0
multidict                 6.0.4
multiprocess              0.70.15
networkx                  3.1
numpy                     1.26.0
nvidia-cublas-cu11        11.10.3.66
nvidia-cuda-cupti-cu11    11.7.101
nvidia-cuda-nvrtc-cu11    11.7.99
nvidia-cuda-runtime-cu11  11.7.99
nvidia-cudnn-cu11         8.5.0.96
nvidia-cufft-cu11         10.9.0.58
nvidia-curand-cu11        10.2.10.91
nvidia-cusolver-cu11      11.4.0.1
nvidia-cusparse-cu11      11.7.4.91
nvidia-nccl-cu11          2.14.3
nvidia-nvtx-cu11          11.7.91
opencv-python             4.8.0.76
orjson                    3.9.7
packaging                 23.1
pandas                    2.1.1
Pillow                    9.5.0
pip                       23.2.1
platformdirs              3.10.0
protobuf                  3.20.3
psutil                    5.9.5
pyarrow                   13.0.0
pybind11                  2.11.1
pydantic                  2.3.0
pydantic_core             2.6.3
pydeck                    0.8.1b0
pydub                     0.25.1
Pygments                  2.16.1
Pympler                   1.0.1
pyparsing                 3.1.1
python-dateutil           2.8.2
python-multipart          0.0.6
python-rapidjson          1.11
pytz                      2023.3.post1
pytz-deprecation-shim     0.1.0.post0
PyYAML                    6.0.1
referencing               0.30.2
regex                     2023.8.8
requests                  2.31.0
rich                      13.5.3
rpds-py                   0.10.3
safetensors               0.3.3
semantic-version          2.10.0
sentencepiece             0.1.99
setuptools                68.0.0
shortuuid                 1.0.11
six                       1.16.0
smmap                     5.0.1
sniffio                   1.3.0
starlette                 0.27.0
streamlit                 1.24.0
sympy                     1.12
tenacity                  8.2.3
termcolor                 2.3.0
tiktoken                  0.5.1
tokenizers                0.13.3
toml                      0.10.2
tomli                     2.0.1
toolz                     0.12.0
torch                     2.0.1
tornado                   6.3.3
tqdm                      4.66.1
transformers              4.30.2
triton                    2.0.0
tritonclient              2.37.0.9383150
typing_extensions         4.8.0
tzdata                    2023.3
tzlocal                   4.3.1
urllib3                   2.0.5
uvicorn                   0.23.2
validators                0.22.0
watchdog                  3.0.0
websockets                11.0.3
wheel                     0.38.4
xxhash                    3.3.0
yapf                      0.40.2
yarl                      1.9.2
zipp                      3.17.0
zope.event                5.0
zope.interface            6.0

**Comment by kietoljw** [comment]
尝试`pip install transformers==4.33.2`可能有效，希望能帮助到你
