### ISSUE TITLE
chat-20b-4bit模型加载部分权重未初始化对模型推理有没有影响

### ISSUE THREAD

**Issue by qianyue76** [InternLM/InternLM#365]
### Describe the question.

加载internlm-chat-20b-4bit模型时提示部分权重未初始化，有两三屏，只截了一屏。这会影响模型推理吗？这个warning是不是有点太长了
![image](https://github.com/InternLM/InternLM/assets/103345381/113dfb1d-3909-4ebc-a1dd-e4d40a60e326)

**Comment by lvhan028** [comment]
可以看一下internlm-chat-20b-4bit的model card：https://huggingface.co/internlm/internlm-chat-20b-4bit
它不能用transformers加载
得下载下来，用 lmdeploy 转换和推理。步骤都在model card上了。

**Comment by ltm920716** [comment]
hello @lvhan028 ,
请教一下，看了官方readme，确实说用lmdeploy加载，但如果用Transformer加载会有影响么，lmdeploy只是为了更好的加速？了解的不多，请教一下
