### ISSUE TITLE
20b-4bit部署疑问[QA] 

### ISSUE THREAD

**Issue by ltm920716** [InternLM/InternLM#366]
### Describe the question.

![image](https://github.com/InternLM/InternLM/assets/12007227/389699fb-cdd5-4a74-8661-d158f116476f)

如上图所示
1、安装lmdeploy
2、git clone https://huggingface.co/internlm/internlm-chat-20b-4bit
3、Convert internlm-chat-20b

所以转换实际要用原始20b模型？那4bit模型下载下来到底在哪里用，确实没看懂，麻烦指点，谢谢

**Comment by ltm920716** [comment]
我知道了，--model_path的路径就是4bit

**Comment by macomzzl** [comment]
<img width="761" alt="image" src="https://github.com/InternLM/InternLM/assets/7599290/48b7fc44-9665-4499-861f-b035384f1846">
model_path改为4bit还是报错...
