### ISSUE TITLE
[QA] 模型阅读理解QA能力差

### ISSUE THREAD

**Issue by YbugY** [InternLM/InternLM#369]
### 描述问题

为什么提供已知信息的prompt的情况下，感觉模型的回答没有信息量，是不是阅读理解能力比较差？
![e93c77b7c957f56e0b326121f4d2044](https://github.com/InternLM/InternLM/assets/104674296/509d124a-6a5d-4790-9f06-eb6a9de375ce)
![c11499f35f9319c7680854471831fe7](https://github.com/InternLM/InternLM/assets/104674296/168d93aa-3933-4850-9c30-712ce753af12)

**Comment by zhudongwork** [comment]
> ### 描述问题
> 为什么提供已知信息的prompt的情况下，感觉模型的回答没有信息量，是不是阅读理解能力比较差？ ![e93c77b7c957f56e0b326121f4d2044](https://user-images.githubusercontent.com/104674296/270559211-509d124a-6a5d-4790-9f06-eb6a9de375ce.png) ![c11499f35f9319c7680854471831fe7](https://user-images.githubusercontent.com/104674296/270559239-168d93aa-3933-4850-9c30-712ce753af12.png)

我也发现了这个问题，充分给足了上下文，但就是回答不了

**Comment by ZwwWayne** [comment]
Thanks for your kind report. It seems to be a bad case of the model in reading comprehension tasks. We will refine the model's capability in the next version.
