### ISSUE TITLE
[Bug] 如何评测internLM的基础模型，使用评测百川模型的5-few-shot时，internLM无法正确输出答案

### ISSUE THREAD

**Issue by expresschen** [InternLM/InternLM#37]
### Describe the bug

none

### Environment

none

**Comment by tonysy** [comment]
We use [OpenCompass](https://github.com/InternLM/opencompass) for model evaluation. You can follow this [config](https://github.com/InternLM/opencompass/blob/main/configs/eval_internlm_7b.py) for evaluating InternLM-7B. 
- For base model, we use ppl for multi-choice questions. 
- For chat model, we use generation method for multi-choice questions.

All prompts are released, and welcome to try OpenCompass for model evauation(also support ChatGLM2-6B, Baichuan-7B). Feel free to raise issue in OpenCompass for evaluation problems.

**Comment by expresschen** [comment]
很好奇internLM的怎么没有few-shot的能力

**Comment by tonysy** [comment]
The evaluation setting of C-Eval and MMLU are both 5-shots. Please follow the instruction and configuration in OpenCompass for more details.
