### ISSUE TITLE
[QA] 调用工具的例子

### ISSUE THREAD

**Issue by heibaidaolx123** [InternLM/InternLM#370]
### 描述问题

Hi，看到[这里](https://mp.weixin.qq.com/s/wPni3LTg3vhh-j0Uz9mBNw)说InternLM 20B有很强的工具调用能力，有例子可以体验吗？

**Comment by ericg108** [comment]
同问

**Comment by heibaidaolx123** [comment]
使用工具时，模型的输入输出格式是什么样的呢？跟openai 的function calling一样吗？哪里有文档可以参考？

**Comment by gaoyang07** [comment]
Hi all, you can check [InternLM/lagent](https://github.com/InternLM/lagent) for more details about using LLM as tools.

**Comment by dyabel** [comment]
> Hi all, you can check [InternLM/lagent](https://github.com/InternLM/lagent) for more details about using LLM as tools.

您好，请问有使用toolbench的例子吗
