### ISSUE TITLE
[QA] 使用text-generation-webui加载模型进行推理时内容不完整，出现<eoa>结束

### ISSUE THREAD

**Issue by TianYifan-Vincent** [InternLM/InternLM#390]
### Describe the question.

使用text-generation-webui加载internlm_internlm-chat-20b进行推理时内容不完整，出现<eoa>结束。请问有人遇到相同情况吗？

**Comment by ZwwWayne** [comment]
Could you provide your case in this issue so that we could re-produce it?

**Comment by TianYifan-Vincent** [comment]
> Could you provide your case in this issue so that we could re-produce it?
Thank's for your attention.
This is my request parameters. 
    request = {
        'prompt': prompt,
        'max_new_tokens': 200,
        'auto_max_new_tokens': False,
        'preset': 'None',
        'do_sample': True,
        'temperature': 1.0,
        'top_p': 0.7,
        'typical_p': 1,
        'epsilon_cutoff': 0,  # In units of 1e-4
        'eta_cutoff': 0,  # In units of 1e-4
        'tfs': 1,
        'top_a': 0,
        'repetition_penalty': 1.15,
        'repetition_penalty_range': 0,
        'top_k': 20,
        'min_length': 0,
        'no_repeat_ngram_size': 0,
        'num_beams': 1,
        'penalty_alpha': 0,
        'length_penalty': 1,
        'early_stopping': False,
        'mirostat_mode': 0,
        'mirostat_tau': 5,
        'mirostat_eta': 0.1,
        'guidance_scale': 1,
        'negative_prompt': '',
        'seed': -1,
        'add_bos_token': True,
        'truncation_length': 2048,
        'ban_eos_token': False,
        'skip_special_tokens': True,
        'stopping_strings': [],
    }
 prompt = """System: Please classify the traffic accident based on the following types:
                    ......(keep secret)
                    User: Based on the given case summary, which type does the accident belong to? Respond once as Assistant, providing the Type Number and a brief justification."""+structured_data+"Assistant:"

I ask the model chat-7b to classify the traffic accident based on the given types on webui. But incomplete content during reasoning. Should i add some stopping_strings because of the same situation when using qwen?
![image](https://github.com/InternLM/InternLM/assets/72920835/36627c23-9a9b-416d-9b8b-c61f78109e0a)

**Comment by TianYifan-Vincent** [comment]
> Could you provide your case in this issue so that we could re-produce it?

Thank's for your attention.
This is my request parameters.
request = {
'prompt': prompt,
'max_new_tokens': 200,
'auto_max_new_tokens': False,
'preset': 'None',
'do_sample': True,
'temperature': 1.0,
'top_p': 0.7,
'typical_p': 1,
'epsilon_cutoff': 0, # In units of 1e-4
'eta_cutoff': 0, # In units of 1e-4
'tfs': 1,
'top_a': 0,
'repetition_penalty': 1.15,
'repetition_penalty_range': 0,
'top_k': 20,
'min_length': 0,
'no_repeat_ngram_size': 0,
'num_beams': 1,
'penalty_alpha': 0,
'length_penalty': 1,
'early_stopping': False,
'mirostat_mode': 0,
'mirostat_tau': 5,
'mirostat_eta': 0.1,
'guidance_scale': 1,
'negative_prompt': '',
'seed': -1,
'add_bos_token': True,
'truncation_length': 2048,
'ban_eos_token': False,
'skip_special_tokens': True,
'stopping_strings': [],
}
prompt = """System: Please classify the traffic accident based on the following types:
......(keep secret)
User: Based on the given case summary, which type does the accident belong to? Respond once as Assistant, providing the Type Number and a brief justification."""+structured_data+"Assistant:"

I ask the model chat-7b to classify the traffic accident based on the given types on webui. But incomplete content during reasoning. Should i add some stopping_strings because of the same situation when using qwen?
![image](https://github.com/InternLM/InternLM/assets/72920835/3d05a74e-7c80-4443-b6f0-554ae46c78ea)

**Comment by ZwwWayne** [comment]
The repetition penalty is a bit high. You may try 1.05.
