### ISSUE TITLE
[QA] internlm-chat-7b和internlm-chat-7b-8k在模型结构上有区别吗？还是仅仅权重不同？

### ISSUE THREAD

**Issue by katitizhou** [InternLM/InternLM#394]
### 描述问题

internlm-chat-7b和internlm-chat-7b-8k在模型结构上有区别吗？还是仅仅权重不同？
您推荐使用哪个模型来做对话任务？

**Comment by ZwwWayne** [comment]
Only the fine-tuning data so as the model weights have difference. The architectures are the same.
