### ISSUE TITLE
[QA] 提供的克隆连接会失败，提示没有下载权限，疑似子模块没有权限，因为直接http克隆项目是可以的

### ISSUE THREAD

**Issue by zzfer** [InternLM/InternLM#401]
### Describe the question.

![image](https://github.com/InternLM/InternLM/assets/35950240/90db0b30-2e74-474f-a932-db2da2e99af9)
![image](https://github.com/InternLM/InternLM/assets/35950240/c53b126b-c172-4bbb-bc48-f85cee72f47b)

**Comment by Pryest** [comment]
请尝试以下命令并重试：
git clone git@github.com:InternLM/InternLM.git --recursive
