### ISSUE TITLE
[Feature] 目前的 web_demo.py 不支持 dynamic ntk 的使用。

### ISSUE THREAD

**Issue by YWMditto** [InternLM/InternLM#406]
### Describe the feature

因为 web_demo.py 是直接使用的 transformers 版本的模型，而目前 transformers 版本的 internlm 代码中没有支持 dynamic ntk。

### Will you implement it?

- [ ] I would like to implement this feature and create a PR!

**Comment by gaoyang07** [comment]
https://github.com/InternLM/InternLM/pull/470
https://github.com/InternLM/InternLM/pull/478
https://github.com/InternLM/InternLM/pull/480
