### ISSUE TITLE
[Bug] InternLM-20b-4bit说自己是小度...

### ISSUE THREAD

**Issue by RobinYanZG** [InternLM/InternLM#409]
### 描述该错误

有一次，我问internlm20b-4bit，你是谁， 他回答说叫小度，后来重启api_server就没在发生过。但是每次问他是不是小度，都会说自己是小度。

截图是api request
![image](https://github.com/InternLM/InternLM/assets/61536155/06f1281a-fa1f-46ac-816a-b74a3f4b058b)

### 环境信息

```
# 运行命令行启动api服务器
python -m lmdeploy.serve.openai.api_server .\workspace\ 0.0.0.0 8888 --instance_num 32 --tp 1
```

![image](https://github.com/InternLM/InternLM/assets/61536155/b15df079-49ee-4b26-bafb-32e57ea30688)

**Comment by lvhan028** [comment]
用一下 lmdeploy == 0.0.10 试试。对话模板中的meta instruction 加上了

**Comment by RobinYanZG** [comment]
0.0.10 问了10个类似问题， 没再出现过，不过推理速度变慢了很多很多。这个问题貌似就没出现过了，就先关了。

**Comment by lvhan028** [comment]
> 0.0.10 问了10个类似问题， 没再出现过，不过推理速度变慢了很多很多。这个问题貌似就没出现过了，就先关了。

你是和哪个版本比的呢？我这边测试0.0.10，速度和0.0.9没差
