### ISSUE TITLE
[Bug] class FullyShardedDataParallel 缺失参数 use_orig_params

### ISSUE THREAD

**Issue by JiaoPL** [InternLM/InternLM#414]
### 描述该错误

wrap_FSDP_model 调用`FullyShardedDataParallel`传参use_orig_params，未在FullyShardedDataParallel  class初始化，导致pylint检查未通过。

![image](https://github.com/InternLM/InternLM/assets/44927264/b9137925-c575-4921-a6f6-bca9aed2fc2b)

![image](https://github.com/InternLM/InternLM/assets/44927264/e235cc16-aa7f-4341-a0b4-34f94e00d5f3)

### 环境信息

torch1.13
cuda11.7

**Comment by huangting4201** [comment]
这个参数得在torch2.0.1及以上才有
