### ISSUE TITLE
[Feature] support use_flash_attn in modeling_internlm.py

### ISSUE THREAD

**Issue by swaggy-TN** [InternLM/InternLM#415]
### Describe the feature

It is convenient that the modeling_internlm.py file in the HF model hub or Modelscope support use_flash_attn. In this way, people can directly train(w/ flash-attn) internlm by simply initializing the model using transformers.AutoModel.from_pretrained(). ☺️

### Will you implement it?

- [ ] I would like to implement this feature and create a PR!

**Comment by ZwwWayne** [comment]
Thanks for your feature request. We will consider it in the following releases.

**Comment by gaoyang07** [comment]
Check the new training codebase [InternLM/InternEvo](https://github.com/InternLM/InternEvo) for more details.
