### ISSUE TITLE
[QA] question about repetition_penalty

### ISSUE THREAD

**Issue by laserwave** [InternLM/InternLM#416]
### 描述问题

The code in web_demo.py imports 'generate_interactive' function from interface.py. 

And the length of logits_processor is zero as the parameter is not passed into the generate_interactive in web_demo.py. 

How will the parameter repetition_penalty work if it is set to a value other than 1.0?

**Comment by YWMditto** [comment]
You can achieve this function by modifying the function prepare_generation_config in web_demo.py, which is similar to the setting of hyperparameters such as Temperature.

**Comment by laserwave** [comment]
Setting the repetition_penalty to 1.05, encounter the following exception in transformers/generation/utils.py using the model.generate() directly. Any idea.
`next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: invalid multinomial distribution (sum of probabilities <= 0)`
