### ISSUE TITLE
[QA] Could you explain why “pad_token_id” in config.json is 0 and “pad_token” in tokenizer_config.json is </s>

### ISSUE THREAD

**Issue by laserwave** [InternLM/InternLM#431]
### Describe the question.

token id of \</s\> is 2, which is not matching

**Comment by x54-729** [comment]
Sorry, this is a mistake when convert the checkpoint from `InternLM` to huggingface. We have found the reason recently and are going to fix it soon

**Comment by laserwave** [comment]
Could you describe how to make a quick fix？Thanks

**Comment by x54-729** [comment]
> Could you describe how to make a quick fix？Thanks

Just change `pad_token_id` `bos_token_id` and `eos_token_id` in `config.json` according to tokenizer

**Comment by laserwave** [comment]
By the way，`pad_token_id` in `generation_config.json` should also be corrected.
