### ISSUE TITLE
[QA] internlm-20b-4bit在两卡或者三卡3090上的部署问题

### ISSUE THREAD

**Issue by venxzw** [InternLM/InternLM#433]
### 描述问题

请问各位大佬，我在autodl上租了三张3090来部署internlm-20b-4bit，用transformers命令行的形式进行推理时，出现显存不够的情况，如下是运行过程中三张卡的显存使用情况和报错：
![image](https://github.com/InternLM/InternLM/assets/138442712/e087feb0-fb74-46f1-b366-202c13bae3e8)
![image](https://github.com/InternLM/InternLM/assets/138442712/b410deab-18bb-440d-9023-81bece4fde23)
我想知道是我部署方式有问题还是？

**Comment by lvhan028** [comment]
如果4bit模型是通过 lmdeploy 得到的话，那么目前只能用 lmdeploy 推理。还不支持 transformers 推理

**Comment by lvhan028** [comment]
我们会修改internlm/internlm-chat-20b-4bit中的internlm_modeling.py，提示用户使用 lmdeploy 进行推理。
https://huggingface.co/internlm/internlm-chat-20b-4bit/discussions/11/files
适配 transformers的工作计划在11月份完成，敬请期待。

**Comment by venxzw** [comment]
> 我们会修改internlm/internlm-chat-20b-4bit中的internlm_modeling.py，提示用户使用 lmdeploy 进行推理。 https://huggingface.co/internlm/internlm-chat-20b-4bit/discussions/11/files 适配 transformers的工作计划在11月份完成，敬请期待。

好的，非常感谢你们的付出。
