### ISSUE TITLE
是否会考虑出cpu运行的模型？

### ISSUE THREAD

**Issue by animalong** [InternLM/InternLM#434]
### 描述该功能

是否会考虑出cpu运行的模型？

### 是否希望自己实现该功能？

- [ ] 我希望自己来实现这一功能，并向 InternLM 贡献代码！

**Comment by vansin** [comment]
https://github.com/intel-analytics/BigDL/tree/main/python/llm/example/CPU/HF-Transformers-AutoModels/Model/internlm
