### ISSUE TITLE
The prompt template seems not correct

### ISSUE THREAD

**Issue by BIGWangYuDong** [InternLM/InternLM#438]
The prompt template in web_demo.py seems not correct.

https://github.com/InternLM/InternLM/blob/7b1b892084c7c841263fca78703e3060e213b80d/web_demo.py#L49

the prompt does not have `<eoh>`. i.e. it should be 
```python
user_prompt = "<|User|>:{user}\n"
```

Need have a check

**Comment by ZwwWayne** [comment]
Closed by https://github.com/InternLM/InternLM/pull/440
