### ISSUE TITLE
[QA] 可以基于这个仓库重新预训练internlm嘛？

### ISSUE THREAD

**Issue by happened** [InternLM/InternLM#441]
### 描述问题

这个文档介绍了预训练数据的处理方式 `https://github.com/InternLM/InternLM/blob/main/doc/usage.md`
那是不是我们有足够大的数据就可以重新预训练Internlm，还是只能做个微调

**Comment by gaoyang07** [comment]
可以的，我们的仓库同时支持预训练与sft微调

**Comment by gaoyang07** [comment]
Check https://internlm.readthedocs.io/zh-cn/latest/?badge=latest for more details.
