### ISSUE TITLE
[Tool] 我们提供了openai的api接口文件

### ISSUE THREAD

**Issue by lewisliuyi** [InternLM/InternLM#442]
### Describe the feature

能不能写个openai的api接口文件？本来很想用，但是由于没有openai的api接口文件，导致我不知道怎么包裹成api接到其他应用程序。

### Will you implement it?

- [ ] I would like to implement this feature and create a PR!

**Comment by AllentDan** [comment]
请考虑 [lmdeploy](https://github.com/InternLM/lmdeploy)

**Comment by gaoyang07** [comment]
We implemented it. Please check https://github.com/InternLM/InternLM/blob/develop/tools/openai_api.py for usage.
