### ISSUE TITLE
[QA] about config 

### ISSUE THREAD

**Issue by happened** [InternLM/InternLM#447]
### 描述问题

![image](https://github.com/InternLM/InternLM/assets/20530955/9cd52c84-6295-42d7-8b33-8e67ed5275fb)
i want to finetune internlm-chat-7b ,  but I can't find a detailed answer about the configuration file items。 can you provide it ?
by the way, There are some errors in the 7B_sft.py

**Comment by gaoyang07** [comment]
Thanks for raising this question. If you want to finetune `internlm-chat-7b`, you can set `load_ckpt_info = dict(path="/your/internlm-7b-chat/model/path", content=["model"], ckpt_type="internlm")`

**Comment by gaoyang07** [comment]
Are there any bugs when loading the sft model?

**Comment by happened** [comment]
no,it works well. but i think the annotations should be modified

**Comment by gaoyang07** [comment]
> no,it works well. but i think the annotations should be modified

Thanks for the reminder. We will update it soon.
