### ISSUE TITLE
关于 InternLM 通用工具调用能力 的疑问

### ISSUE THREAD

**Issue by leehommlee** [InternLM/InternLM#45]
### 描述该功能

在ReadMe中提到了 模型的特点
“3. 提供了一个多功能工具集，让用户灵活构建自己的工作流程。”
请问 这里的工作流程是什么意思，是指的LLM调用外部工具吗

### 是否希望自己实现该功能？

- [ ] 我希望自己来实现这一功能，并向 InternLM 贡献代码！

**Comment by hwang824** [comment]
同问，chatgpt的API已经实现了function调用，这个功能确实很有用，不知道InternLM的“通用工具调用”是不是指的同样的意思，如果是的话，代码中该怎么用呢？如果不是的话，我觉得这个功能非常有价值，希望有机会一起来开发此功能

**Comment by felixstander** [comment]
这个有官方的答复吗，能调用各种工具的能力很是刚需

**Comment by ZwwWayne** [comment]
We will support it in the following weeks. 
Yes, the interface is consistent with chatgpt. We will support to use system call and make it inference with PAL first.

**Comment by franklyd** [comment]
期待

**Comment by hwang824** [comment]
> 

有什么进展吗？

**Comment by ZwwWayne** [comment]
Thanks for your attention. We are preparing the script for PAL this week and it will be released soon. Please stay tuned.

**Comment by hwang824** [comment]
> Thanks for your attention. We are preparing the script for PAL this week and it will be released soon. Please stay tuned.

太棒了，感谢你们团队的工作！

**Comment by ZwwWayne** [comment]
https://github.com/InternLM/InternLM/pull/163

**Comment by hwang824** [comment]
能够给出一些文档吗？具体该怎么使用呢？

**Comment by BIGWangYuDong** [comment]
> 能够给出一些文档吗？具体该怎么使用呢？

https://github.com/InternLM/InternLM/tree/main/tools#pal_inferencepy
