### ISSUE TITLE
The issue template of documentation doesn't exists

### ISSUE THREAD

**Issue by kkscilife** [InternLM/InternLM#46]
### Describe the bug

click the link: https://internlm.readthedocs.io/en/latest/
the result is 404

### Environment

any browser

**Comment by kkscilife** [comment]
The link of 'Explore InternLM (官网)' also dones't exitst. Current result is: https://https//internlm.org/
There are double https

**Comment by hellock** [comment]
Thanks for the feedback. It is fixed in #65.
