### ISSUE TITLE
[Bug] There are redundant loss info in train log

### ISSUE THREAD

**Issue by kkscilife** [InternLM/InternLM#483]
### Describe the bug

Please click link for more information: https://github.com/InternLM/InternLM/actions/runs/6786429220/job/18447288893
<img width="1045" alt="企业微信截图_16995205052460" src="https://github.com/InternLM/InternLM/assets/126147887/46eb1ac1-14a0-4dd6-891c-85e1c7622ff7">

We can see there are many loss about code files which are not expected

### Environment

Branch: develop

**Comment by gaoyang07** [comment]
Fixed in https://github.com/InternLM/InternLM/pull/489
