### ISSUE TITLE
[Bug]  huggingface上的最新modeling代码逻辑疑似有问题。

### ISSUE THREAD

**Issue by wqh17101** [InternLM/InternLM#487]
### 描述该错误

huggingface上的最新modeling代码逻辑疑似有问题。
原来的逻辑是先做rope再cat，最新的代码变成了先cat再做rope，这块是有什么特殊的设计么

huggingface上的commitID：c8f2f9979075c3ccd0399d042823ac719d545840 

https://huggingface.co/internlm/internlm-20b/commit/c8f2f9979075c3ccd0399d042823ac719d545840

### 环境信息

NA

**Comment by x54-729** [comment]
这个是因为要先存kv cache，因为ntk超出seqlen后每一个新的位置的q都有一个新的位置编码，kv需要用对应的新的位置编码，所以kv cache需要是没有经过位置编码的版本；
这样的改动不会影响生成，顺序调换前后得到的q和k都是经过位置编码后的

**Comment by x54-729** [comment]
> @x54-729 另外想问下，多卡推理的要怎么写，加载模型

请问是用huggingface模型进行多卡推理吗？
