### ISSUE TITLE
[QA] 4090能进行微调吗

### ISSUE THREAD

**Issue by testmurk** [InternLM/InternLM#494]
### Describe the question.

flash-attn 对GPU架构有要求，老GPU架构的显卡如何进行微调，比如 v100、a40之类的，另外 4090 并行做微调能跑不

**Comment by li126com** [comment]
> ### Describe the question.
> flash-attn 对GPU架构有要求，老GPU架构的显卡如何进行微调，比如 v100、a40之类的，另外 4090 并行做微调能跑不

目前 RTX 4090 是支持 flashattenrion 的，应当可以直接按照 redeme 进行微调训练，或者使用 LoRA 进行微调这个我们之前做过实验是行得通的。v100、a40之类目前并不支持 flashattention ，可以尝试在关闭 flashattention 情况下进行微调，开关在 config 文件下的 model.use_flash_attn。
