### ISSUE TITLE
[QA] about use_swiglu & ParallelFusedMLP

### ISSUE THREAD

**Issue by FL77N** [InternLM/InternLM#509]
### Describe the question.

你好，我在代码中看到 mlp 可以使用[两种不同的模式](https://github.com/InternLM/InternLM/blob/3028f07cb79e5b1d7342f4ad8d11efad3fd13d17/internlm/model/modeling_internlm.py#L105) 如果我训练的时候使用 FeedForward 进行训练，推理的时候权重可以加载到 ParallelFusedMLP 里面吗？

**Comment by Pryest** [comment]
不行，如果实在有需求的话需要手动更改一下权重里的key_name。
