### ISSUE TITLE
[QA] flash-attention依赖问题

### ISSUE THREAD

**Issue by wzzju** [InternLM/InternLM#511]
### flash-attention依赖问题

[环境安装](https://github.com/InternLM/InternLM/blob/main/doc/install.md)文档中指出需要编译flash-attention，但因为某些原因我们使用不了flash-attention。请问书生大模型有不依赖flash-attention的版本吗？

**Comment by wzzju** [comment]
@sunpengsdu 您好！麻烦请尽快回复一下哈～

**Comment by wzzju** [comment]
<img width="1133" alt="image" src="https://github.com/InternLM/InternLM/assets/17102274/76dfe396-dbd7-4c0a-a7ce-b5ed2f9a18b2">
即使我在[configs/7B_sft.py](https://github.com/InternLM/InternLM/blob/main/configs/7B_sft.py)这里设置`use_flash_attn=False`仍然会出现`ModuleNotFoundError: No module named 'fused_dense_lib'`错误。换言之，即使在config中关闭flash_attn，还是会依赖flash_attn中的fused_dense_lib库。

**Comment by yingtongxiong** [comment]
你好，我们config文件中的use_flash_attn这个参数只是用于表明model中使用的attention的实现方式是否采用flash-attention的实现。在model的其他部分，比如ColumnParallelLinear、RowParallelLinear、rotary_embedding等算子里面均使用了flash-attention的实现。因此，我们的model暂时还无法完全脱离flash-attention。

**Comment by wzzju** [comment]
请教一下，如果我这边手动改去除flash-attn的依赖，是不是只需要改动`internlm/model`目录下的内容就可以了呢？按照我的理解，InternLM是一个自包含的分布式训练框架，不依赖Megatron-LM或者Megatron-Deepspeed，但借鉴了ColossalAI的思想实现数据并行、流水线并行和张量并行，对吗？如果去除对flash-attn的依赖，需要改动model以外的框架部分吗？

**Comment by yingtongxiong** [comment]
不需要的，flash-attn主要还是在model内使用的。不过有一些在utils目录下的，例如model_checkpoint.py里面也有用到。但大体上还是在model内部的。

**Comment by wzzju** [comment]
> 不需要的，flash-attn主要还是在model内使用的。不过有一些在utils目录下的，例如model_checkpoint.py里面也有用到。但大体上还是在model内部的。

好的，感谢～另外，「InternLM是一个自包含的分布式训练框架，不依赖Megatron-LM或者Megatron-Deepspeed，但借鉴了ColossalAI的思想实现数据并行、流水线并行和张量并行」，请问这里我理解的对吗？

**Comment by yingtongxiong** [comment]
目前的实现主要是参考Megatron-LM的3D并行架构，实现过程中一部分代码借鉴了ColossalAI的，一部分代码借鉴了Megatron-LM的，具体哪些使用，我们在源码中均有标注。

**Comment by wzzju** [comment]
好的，非常感谢您的耐心回复。
