### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by huajinghua** [InternLM/InternLM#53]
### Describe the bug

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 25401: invalid start byte
The above exception was the direct cause of the following exception:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /data/llm/anaconda3/envs/llm/lib/python3.9/site-packages/transformers/modeling_utils.py:457 in   │
│ load_state_dict                                                                                  │
│                                                                                                  │
│    454 │   │   │   │   │   │   "you cloned."                                                     │
│    455 │   │   │   │   │   )                                                                     │
│    456 │   │   │   │   else:                                                                     │
│ ❱  457 │   │   │   │   │   raise ValueError(                                                     │
│    458 │   │   │   │   │   │   f"Unable to locate the file {checkpoint_file} which is necessary  │
│    459 │   │   │   │   │   │   "model. Make sure you have saved the model properly."             │
│    460 │   │   │   │   │   ) from e                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: Unable to locate the file /data/llm/internlm-chat-7b/pytorch_model-00001-of-00002.bin which is
necessary to load this pretrained model. Make sure you have saved the model properly.

### Environment

python3.9

**Comment by hellock** [comment]
Please describe the issue in detail.
