### ISSUE TITLE
找不到rotary_emb类[Bug] 

### ISSUE THREAD

**Issue by zkrzkr** [InternLM/InternLM#54]
### 描述该错误

在尝试torchrun微调时，运行遇到找不到rotary_emb类
![11](https://github.com/InternLM/InternLM/assets/19923097/f91a66a8-bd95-4f26-82ce-274ac150ba5b)

### 环境信息

CUDA Version: 12.1 
torch                    1.13.1

**Comment by yingtongxiong** [comment]
Hello, It seems that you don't install the flash_attn successfully. You can check your environment to ensure the flash_attn has been installed successfully.

**Comment by yingtongxiong** [comment]
这个问题看起来像是你没有正确安装flash_attn。你可以再确认一下你当前的运行环境中是否已经安装了flash_attn。

**Comment by fyubang** [comment]
> 这个问题看起来像是你没有正确安装flash_attn。你可以再确认一下你当前的运行环境中是否已经安装了flash_attn。

什么版本啊，我装了1.0.5，还是报同样的错

**Comment by yingtongxiong** [comment]
你运行import flash_attn能成功吗？这个rotary_emb是flash_attn里面的cuda扩展算子，这个应该和版本是没有关系的。理论上，flash_attn安装成功后，这个包是可以import成功的。

**Comment by yingtongxiong** [comment]
安装flash_attn可以参考[这个](https://github.com/InternLM/InternLM/blob/main/doc/en/install.md)
