### ISSUE TITLE
[Bug] Python3.10环境运行加载模型错误

### ISSUE THREAD

**Issue by exceedzhang** [InternLM/InternLM#55]
### 描述该错误

按照官方文档进行环境安装并使用Python3.10环境进行加载模型，模型加载失败如下图所示：
<img width="1120" alt="image" src="https://github.com/InternLM/InternLM/assets/4583537/b62241c8-c14a-414b-8437-521eb2790903">
模型加载到内存中，内存快速增长到21GB之后，进程被killed了，导致模型加载失败
<img width="1512" alt="image" src="https://github.com/InternLM/InternLM/assets/4583537/2c4298cf-958d-45cd-8fb3-13f89a45b8ce">

### 环境信息

<img width="1116" alt="image" src="https://github.com/InternLM/InternLM/assets/4583537/4479c020-8c1e-4854-8528-f4034ff94455">

**Comment by exceedzhang** [comment]
GPU 英伟达A5000 24GB内存

**Comment by huajinghua** [comment]
3090也是out-of-memory：
OutOfMemoryError: CUDA out of memory. Tried to allocate 172.00 MiB (GPU 0; 23.69 GiB total capacity; 23.33 GiB
already allocated; 66.94 MiB free; 23.33 GiB reserved in total by PyTorch) If reserved memory is >> allocated
memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and
PYTORCH_CUDA_ALLOC_CONF

24G显存不够？？？

**Comment by XieLipeng0830** [comment]
遇到同样的问题，加载模型中，32G内存爆掉。

**Comment by huangbaichao** [comment]
> 3090也是out-of-memory： OutOfMemoryError: CUDA out of memory. Tried to allocate 172.00 MiB (GPU 0; 23.69 GiB total capacity; 23.33 GiB already allocated; 66.94 MiB free; 23.33 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> 
> 24G显存不够？？？

我3090也爆显存了。准备换卡试下。
不知道模型加载能不能带参数加载半精度等降低设备门槛。目前没发现量化版本。

**Comment by huangbaichao** [comment]
> 3090也是out-of-memory： OutOfMemoryError: CUDA out of memory. Tried to allocate 172.00 MiB (GPU 0; 23.69 GiB total capacity; 23.33 GiB already allocated; 66.94 MiB free; 23.33 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> 
> 24G显存不够？？？

我运行起来占用快29G显存了，可以参考下。

**Comment by jamiechoi1995** [comment]
内存不够的话可以增大交换空间
显存不够的话加载完了模型以后可以加个.to(torch.bfloat16)
https://github.com/wenda-LLM/wenda/blob/aa1c7b212973cacd585b1b3eae0e76d6c8f2c2ae/llms/llm_internlm.py#L47C52-L47C70

**Comment by sunpengsdu** [comment]
@exceedzhang .to(torch.bfloat16)后是否还会OOM?

**Comment by exceedzhang** [comment]
使用FastChat bfloat16 加载模型启动成功了

**Comment by kizunasunhy** [comment]
.cuda()前面加个.half()就可以了

**Comment by laserwave** [comment]
> 内存不够的话可以增大交换空间

请问这个如何增大呢
