### ISSUE TITLE
[QA] 20b模型微调

### ISSUE THREAD

**Issue by laserwave** [InternLM/InternLM#552]
### Describe the question.

请问20b模型微调需要多少内存（非显存）呢，模型还没有加载到显存中，就由于内存占用过多崩掉

**Comment by laserwave** [comment]
另外一个issue中提到可以增大交换空间，具体需要怎么做呢

**Comment by lixinpeng16** [comment]
embedding.py import rotary_emb
rotary_emb是一个实现旋转式位置嵌入的类吧，这个是不是自己写的，我找不到这个方法，请问您怎么解决的

**Comment by laserwave** [comment]
> embedding.py import rotary_emb
> rotary_emb是一个实现旋转式位置嵌入的类吧，这个是不是自己写的，我找不到这个方法，请问您怎么解决的

 用的hugging face上的code，没遇到这个问题

**Comment by lixinpeng16** [comment]
您是在hugging face上拉的model 然后跑的推理嘛，我是进行finetune过程中，遇到的这个问题

**Comment by laserwave** [comment]
> 您是在hugging face上拉的model 然后跑的推理嘛，我是进行finetune过程中，遇到的这个问题

跑的lora微调
