### ISSUE TITLE
[Bug] 7Bfinetnue找不到rotary_emb

### ISSUE THREAD

**Issue by lixinpeng16** [InternLM/InternLM#556]
### Describe the bug

我在进行7Bfinetune时，embedding.py文件中 有一行import rotary_emb 但是我找不到这个方法，这应该是一个进行旋转嵌入的方法，但是项目中并没有找到，我无法根据调用的函数将方法自己复现出来，请问有解决方法嘛？

### Environment

python 3.10

**Comment by gaoyang07** [comment]
您好，您需要编译flash-attention之后得到对应package，参考：https://github.com/InternLM/InternLM/blob/ac7509389b85425ebc3900fa5c51637bdfa444c2/doc/en/install.md?plain=1#L49
