### ISSUE TITLE
[QA] 如何使用InternLMForSequenceClassification？

### ISSUE THREAD

**Issue by YinHan-Zhang** [InternLM/InternLM#559]
### Describe the question.

我想做二分类任务，将modeling_internlm.InternLMForCausalLM 更换为modeling_internlm.InternLMForSequenceClassification，但是不知道在config中如何设置，小白上路，非常希望能够帮助一下我，感激不尽

**Comment by Pryest** [comment]
You could just add it to `from_pretrained` function as a keyword argument, like this:
```
from modeling_internlm import InternLMForSequenceClassification
model = InternLMForSequenceClassification.from_pretrained("internlm/internlm-7b", num_labels=2)
```
