### ISSUE TITLE
[QA] convert2hf.py 转化成hf格式的时候报错了

### ISSUE THREAD

**Issue by zhangjunyi111** [InternLM/InternLM#574]
### Describe the question.

执行指令
 python3  tools/transformers/convert2hf.py --src_folder output_model/sft_CoT_ckpt_internlm_chat_7B_lr1e-4_step1082_0102_v1/snapshot/1/  --tgt_folder hf_ckpt/ --tokenizer ./tools/V7_sft.model 

报错：
size mismatch for model.layers.24.self_attn.k_proj.weight: copying a param with shape torch.Size([256, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).

**Comment by x54-729** [comment]
请问保存的 checkpoint 是tp_size=8 的吗？

**Comment by zhangjunyi111** [comment]
分布式训练的 用了16张卡，不太清楚 save的时候checkpoint的大小在哪里看？

**Comment by x54-729** [comment]
噢噢，这是因为目前main分支的转换脚本只支持 tp=1 的情况，所以会报错；
您看下develop分支的 `convert2hf.py`，那个可以处理多tp和pp并行的情况

**Comment by zhangjunyi111** [comment]
请问下，tp1 pp16应该使用的是main分支的那个还是说develop分支的那个？

**Comment by zhangjunyi111** [comment]
另外，我当时的处理办法是，因为用main分支那个脚本转换我的文件，最后还有个提示	You may consider adding `ignore_mismatched_sizes=True` in the model `from_pretrained` method.

所以我根据这个设置了ignore_mismatched_sizes=True，然后他生成了，但我不知道道有没有什么隐藏的风险

**Comment by x54-729** [comment]
tp1 pp16的话两个都可以，不过推荐使用 develop 分支的，develop分支更加严谨一些，添加了对 bos eos 的设置；ignore_mismatch_sizes=True 会忽视这些形状不匹配的张量，这样会有大量的权重没有被加载到模型里，不要设置这个参数

**Comment by zhangjunyi111** [comment]
develop的分支处理还是报这个错,不知道为什么

**Comment by zhangjunyi111** [comment]
**克隆develop分支**
git clone -b develop  https://github.com/InternLM/InternLM.git

**develop分支**
root@node1:~/zhangjunyi/InternLM# ls
CHANGE_LOG.md  docker		internlm	 README-zh-Hans.md	   third_party	web_demo_internlm.py
ci_scripts     docker.Makefile	LICENSE		 requirements		   tools	web_demo.py
configs        experiment	README-ja-JP.md  sonar-project.properties  train.py
doc	       hf_ckpt_0108_15	README.md	 tests			   version.txt

**执行指令**
root@node1:~/zhangjunyi/InternLM# python3  tools/transformers/convert2hf.py  --src_folder /home/huawei/workspace/shiyan/InternLM-main/output_model/sft_CoT_ckpt_internlm_chat_7B_lr1e-4_step1082_0102_v1/snapshot/1/  --tgt_folder hf_ckpt_0108_15/ --tokenizer ./tools/V7_sft.model


错误日志：
from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for model.layers.28.self_attn.q_proj.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([4096]).
	size mismatch for model.layers.28.self_attn.k_proj.weight: copying a param with shape torch.Size([256, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for model.layers.28.self_attn.k_proj.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([4096]).
	size mismatch for model.layers.28.self_attn.v_proj.weight: copying a param with shape torch.Size([256, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for model.layers.28.self_attn.v_proj.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([4096]).
	size mismatch for model.layers.28.self_attn.o_proj.weight: copying a param with shape torch.Size([4096, 256]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for model.layers.28.mlp.gate_proj.weight: copying a param with shape torch.Size([688, 4096]) from checkpoint, the shape in current model is torch.Size([11008, 4096]).
	size mismatch for model.layers.28.mlp.down_proj.weight: copying a param with shape torch.Size([4096, 688]) from checkpoint, the shape in current model is torch.Size([4096, 11008]).
	size mismatch for model.layers.28.mlp.up_proj.weight: copying a param with shape torch.Size([688, 4096]) from checkpoint, the shape in current model is torch.Size([11008, 4096]).
	size mismatch for model.layers.29.self_attn.q_proj.weight: copying a param with shape torch.Size([256, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for model.layers.29.self_attn.q_proj.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([4096]).
	size mismatch for model.layers.29.self_attn.k_proj.weight: copying a param with shape torch.Size([256, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for model.layers.29.self_attn.k_proj.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([4096]).
	size mismatch for model.layers.29.self_attn.v_proj.weight: copying a param with shape torch.Size([256, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for model.layers.29.self_attn.v_proj.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([4096]).
	size mismatch for model.layers.29.self_attn.o_proj.weight: copying a param with shape torch.Size([4096, 256]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for model.layers.29.mlp.gate_proj.weight: copying a param with shape torch.Size([688, 4096]) from checkpoint, the shape in current model is torch.Size([11008, 4096]).
	size mismatch for model.layers.29.mlp.down_proj.weight: copying a param with shape torch.Size([4096, 688]) from checkpoint, the shape in current model is torch.Size([4096, 11008]).
	size mismatch for model.layers.29.mlp.up_proj.weight: copying a param with shape torch.Size([688, 4096]) from checkpoint, the shape in current model is torch.Size([11008, 4096]).
	size mismatch for model.layers.30.self_attn.q_proj.weight: copying a param with shape torch.Size([256, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for model.layers.30.self_attn.q_proj.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([4096]).
	size mismatch for model.layers.30.self_attn.k_proj.weight: copying a param with shape torch.Size([256, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for model.layers.30.self_attn.k_proj.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([4096]).
	size mismatch for model.layers.30.self_attn.v_proj.weight: copying a param with shape torch.Size([256, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for model.layers.30.self_attn.v_proj.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([4096]).
	size mismatch for model.layers.30.self_attn.o_proj.weight: copying a param with shape torch.Size([4096, 256]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for model.layers.30.mlp.gate_proj.weight: copying a param with shape torch.Size([688, 4096]) from checkpoint, the shape in current model is torch.Size([11008, 4096]).
	size mismatch for model.layers.30.mlp.down_proj.weight: copying a param with shape torch.Size([4096, 688]) from checkpoint, the shape in current model is torch.Size([4096, 11008]).
	size mismatch for model.layers.30.mlp.up_proj.weight: copying a param with shape torch.Size([688, 4096]) from checkpoint, the shape in current model is torch.Size([11008, 4096]).
	size mismatch for model.layers.31.self_attn.q_proj.weight: copying a param with shape torch.Size([256, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for model.layers.31.self_attn.q_proj.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([4096]).
	size mismatch for model.layers.31.self_attn.k_proj.weight: copying a param with shape torch.Size([256, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for model.layers.31.self_attn.k_proj.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([4096]).
	size mismatch for model.layers.31.self_attn.v_proj.weight: copying a param with shape torch.Size([256, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for model.layers.31.self_attn.v_proj.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([4096]).
	size mismatch for model.layers.31.self_attn.o_proj.weight: copying a param with shape torch.Size([4096, 256]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for model.layers.31.mlp.gate_proj.weight: copying a param with shape torch.Size([688, 4096]) from checkpoint, the shape in current model is torch.Size([11008, 4096]).
	size mismatch for model.layers.31.mlp.down_proj.weight: copying a param with shape torch.Size([4096, 688]) from checkpoint, the shape in current model is torch.Size([4096, 11008]).
	size mismatch for model.layers.31.mlp.up_proj.weight: copying a param with shape torch.Size([688, 4096]) from checkpoint, the shape in current model is torch.Size([11008, 4096]).
	size mismatch for lm_head.weight: copying a param with shape torch.Size([6448, 4096]) from checkpoint, the shape in current model is torch.Size([103168, 4096]).
	You may consider adding `ignore_mismatched_sizes=True` in the model `from_pretrained` method.

**Comment by x54-729** [comment]
不好意思，刚刚查看了一下相应的改动还没有合入到 develop 分支里
https://github.com/InternLM/InternLM/pull/536
麻烦按照这个 PR 的代码再试下呢

**Comment by zhangjunyi111** [comment]
新的PR执行效果如下：

**Comment by zhangjunyi111** [comment]
没有问题了，感谢你的帮助 @x54-729
