### ISSUE TITLE
[QA] ，RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1

### ISSUE THREAD

**Issue by zhangjunyi111** [InternLM/InternLM#575]
### Describe the question.

执行model.chat（）的时候报错了，RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1，请问下是什么原因？

在命令行中执行的指令如下：
>>> import torch
>>> from transformers import AutoTokenizer,AutoModelForCausalLM
>>> tokenizer = AutoTokenizer.from_pretrained("hf_ckpt_0108", trust_remote_code=True)
>>> model = AutoModelForCausalLM.from_pretrained('hf_ckpt_0108',trust_remote_code=True,torch_dtype=torch.float16).cuda()
>>>response, history = model.chat(tokenizer, "xxxxxxx", history=[])

**Comment by x54-729** [comment]
能麻烦提供一下完整的报错 Traceback 吗？

**Comment by zhangjunyi111** [comment]
你好，完整的traceback如下：
>>> response, history = model.chat(tokenizer, "帮我做个去上海的旅游攻略", history=[])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/huawei/.cache/huggingface/modules/transformers_modules/hf_ckpt_0108/modeling_internlm.py", line 806, in chat
    outputs = self.generate(
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/generation/utils.py", line 1565, in generate
    return self.sample(
  File "/usr/local/lib/python3.8/dist-packages/transformers/generation/utils.py", line 2612, in sample
    outputs = self(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/huawei/.local/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/huawei/.cache/huggingface/modules/transformers_modules/hf_ckpt_0108/modeling_internlm.py", line 704, in forward
    outputs = self.model(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/huawei/.cache/huggingface/modules/transformers_modules/hf_ckpt_0108/modeling_internlm.py", line 592, in forward
    layer_outputs = decoder_layer(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/huawei/.local/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/huawei/.cache/huggingface/modules/transformers_modules/hf_ckpt_0108/modeling_internlm.py", line 302, in forward
    hidden_states = self.input_layernorm(hidden_states)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/huawei/.local/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/huawei/.cache/huggingface/modules/transformers_modules/hf_ckpt_0108/modeling_internlm.py", line 103, in forward
    return self.weight * hidden_states

**Comment by x54-729** [comment]
这个问题有点奇怪，我没有复现成功，从报错来看应该是在进入 decoder layer 之前、word embedding 之后，模型的 hidden states 被转移到了另一个 GPU 上，可能需要麻烦您在 `/home/huawei/.cache/huggingface/modules/transformers_modules/hf_ckpt_0108/modeling_internlm.py` 文件中打印一下 hiddenstates 的 device 看一下是什么时候发生了设备的变动

**Comment by zhangjunyi111** [comment]
![image](https://github.com/InternLM/InternLM/assets/67990935/78090748-82d6-4703-8731-646519792ee5)

调试代码：

**Comment by zhangjunyi111** [comment]
调试代码如下：
![Snipaste_2024-01-08_22-12-53](https://github.com/InternLM/InternLM/assets/67990935/2ffd44f0-b978-4512-924e-1ae16895f79e)

**Comment by zhangjunyi111** [comment]
另外，我们是用的分布式训练的模型，2台机器，但是合并的时候是用的一台机器，把另外一台的拷贝过来，合并的。

**Comment by zhangjunyi111** [comment]
另外，我这个是在python命令行执行的

**Comment by x54-729** [comment]
第二次调用应该是进入了第二层，在 InternLMModel 的 forward 中循环遍历 layers 的时候 hiddenstates 的 device 变化是什么样的呀

**Comment by zhangjunyi111** [comment]
这里吗？
![image](https://github.com/InternLM/InternLM/assets/67990935/a4584134-02f0-4894-8add-066d73f30a21)

然后我们用py脚本可以调用，支持多卡，但是在python命令行却不行，不知道为什么

**Comment by zhangjunyi111** [comment]
类似这种函数的形式
import argparse
import time
import pandas as pd
import torch
from tqdm import tqdm
from transformers import AutoTokenizer, AutoModelForCausalLM

def load_model(model_path):
    _tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)

    # device_map='auto'可以实现多卡的训练，如果不加该参数，发现模型运行到cpu了。
    _model = AutoModelForCausalLM.from_pretrained(model_path, trust_remote_code=True, torch_dtype=torch.float16,
                                                  device_map="auto")

    #_model  = AutoModelForCausalLM.from_pretrained(model_path,trust_remote_code=True,torch_dtype=torch.float16)
    _model = _model.eval()
    return _tokenizer, _model
ef get_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--model_dir', default='hf_ckpt_0108', type=str, help='model path')
    parser.add_argument('--data_dir', default='data/four_scene_train_0109_CoT_test.json', type=str, help='input file path')
    parser.add_argument('--output_dir', default='data/four_scene_train_test.xlsx', type=str, help='output file path')
    argv = parser.parse_args()

    return argv
if __name__ == "__main__":
    args = get_args()

    tokenizer, model = load_model(args.model_dir）
    #单条数据测试
   # query = '我现在在华强北，帮我查找附近的加油站"'
   # prompt = get_prompt_new(query)
   # response, history = model.chat(tokenizer, prompt, history=[])
   # print(response)

**Comment by x54-729** [comment]
> 这里吗？ ![image](https://private-user-images.githubusercontent.com/67990935/295131602-a4584134-02f0-4894-8add-066d73f30a21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3ODU5MDUsIm5iZiI6MTcwNDc4NTYwNSwicGF0aCI6Ii82Nzk5MDkzNS8yOTUxMzE2MDItYTQ1ODQxMzQtMDJmMC00ODk0LThhZGQtMDY2ZDczZjMwYTIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDA3MzMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MGFmOGI0ZDQwOGIzYjBkZGI1YWJkMmE5YzJjOTNmODY3ZTA0ODg5NDlkYjdhNWFjZDNiNzUzMDkwMjVhMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fXUYwme29DSQe1l9K2-oVqVJIhajTgnT5edJ9Py03mQ)
> 
> 然后我们用py脚本可以调用，支持多卡，但是在python命令行却不行，不知道为什么

是的

**Comment by x54-729** [comment]
> ```
> 类似这种函数的形式
> ```
> 
> import argparse import time import pandas as pd import torch from tqdm import tqdm from transformers import AutoTokenizer, AutoModelForCausalLM
> 
> def load_model(model_path): _tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True) _model = AutoModelForCausalLM.from_pretrained(model_path, trust_remote_code=True, torch_dtype=torch.float16, device_map="auto")
> 
> ```
>     #_model  = AutoModelForCausalLM.from_pretrained(model_path,trust_remote_code=True,torch_dtype=torch.float16)
>   _model = _model.eval()
>    return _tokenizer, _model
> ```
> 
> ef get_args(): parser = argparse.ArgumentParser() parser.add_argument('--model_dir', default='hf_ckpt_0108', type=str, help='model path') parser.add_argument('--data_dir', default='data/fourest.json', type=str, help='input file path') parser.add_argument('--output_dir', default='data/fout.xlsx', type=str, help='output file path') argv = parser.parse_args() return argv
> 
> if **name** == "**main**": args = get_args() tokenizer, model = load_model(args.model_dir） query = 'xxxxxx"' prompt = get_prompt_new(query) response, history = model.chat(tokenizer, prompt, history=[]) print(response)

抱歉我没有看懂……意思是 python xxx.py 可以多卡，但是在cmd直接python进去加载模型没办法多卡吗

**Comment by zhangjunyi111** [comment]
对，不知道什么原因。
