### ISSUE TITLE
[QA] total steps设置了500个迭代，但是在目标文件夹只找到一个snapshot，里面标记了250.step

### ISSUE THREAD

**Issue by zhangjunyi111** [InternLM/InternLM#576]
### Describe the question.

![image](https://github.com/InternLM/InternLM/assets/67990935/1f966bfd-f0f8-4f21-8db7-9522c8de825f)

**Comment by zhangjunyi111** [comment]
![Snipaste_2024-01-09_12-39-39](https://github.com/InternLM/InternLM/assets/67990935/efb6bee7-393f-446b-93fd-7c369d0b5b9e)
想问下这个保存的是250个step的时候的checkpoint吗？那底00个保存在哪里？

**Comment by SolenoidWGT** [comment]
我猜测这个问题的原因估计是训练过程中有溢出，导致个别step被skip掉了，所以最终的step_count要小于total_step，所以导致第500个step没存下来，我这边提了个小[fix](https://github.com/InternLM/InternLM/pull/577)，会在训练结束的时候强制存一下ckpt，您可以试试用这个fix重跑一下

**Comment by zhangjunyi111** [comment]
好的

**Comment by SolenoidWGT** [comment]
> 好的

cc: @zhangjunyi111 pr刚更新了下，望知悉

**Comment by zhangjunyi111** [comment]
好的，你好，还有一个问题，我不太理解哈，total_steps=2500的时候。设置CHECKPOINT_EVERY = 2500  oss_snapshot_freq=int(CHECKPOINT_EVERY / 5) 这2个哪个才是checkpoint的保存频率
![image](https://github.com/InternLM/InternLM/assets/67990935/f11135aa-a679-44fa-aa7c-72ec023a6879)

**Comment by SolenoidWGT** [comment]
> 好的，你好，还有一个问题，我不太理解哈，total_steps=2500的时候。设置CHECKPOINT_EVERY = 2500 oss_snapshot_freq=int(CHECKPOINT_EVERY / 5) 这2个哪个才是checkpoint的保存频率 ![image](https://private-user-images.githubusercontent.com/67990935/295500490-f11135aa-a679-44fa-aa7c-72ec023a6879.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NjA3MzEsIm5iZiI6MTcwNDk2MDQzMSwicGF0aCI6Ii82Nzk5MDkzNS8yOTU1MDA0OTAtZjExMTM1YWEtYTY3OS00NGZhLWFhN2MtNzJlYzAyM2E2ODc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDA4MDcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3ZmY0MDY2OWFkZDliMjRjYjFjMmEyNDg3ZGY5YjY4YWFkYjEzYWRkNTZmZjU4NTg0MjJlNDZmNzUwMzllYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9G1YWJZUUjMoNbPgKuRbtfs_IVd2hOjq8A5f2Yzp4m4)

你可以理解为CHECKPOINT_EVERY 才是ckpt的保存频率。
oss_snapshot_freq是用来故障恢复的ckpt，他只会存两份，然后反复覆盖写，存储位置是以snapshot命名的目录。
CHECKPOINT_EVERY 是不会覆盖写的，每个ckpt的存储位置是一个以step id命名的独立的目录

**Comment by zhangjunyi111** [comment]
ok
