### ISSUE TITLE
[QA] convert2hf的时候加载model_config.pt报错

### ISSUE THREAD

**Issue by zhangjunyi111** [InternLM/InternLM#579]
### Describe the question.

![image](https://github.com/InternLM/InternLM/assets/67990935/acda3a4e-fd5d-44a0-9a5f-078bc041106c)

**Comment by zhangjunyi111** [comment]
但是通过在命令行中可以加载，但是必须要在InternLM-main目录下，不能进入子文件夹
![image](https://github.com/InternLM/InternLM/assets/67990935/15dfcbd7-4fec-4fe6-998b-7c263eb2c2c1)

**Comment by x54-729** [comment]
在文件开通使用sys.path.append把InternLM-main的路径加进去吧
sys.path.append("/home/huawei/workspace/shiyan/InternLM-main/")
然后建议您使用develop分支的转换脚本和模型，目前main分支的脚本会存在bos eos设置不当的问题~

**Comment by zhangjunyi111** [comment]
你好，在convert2hf的脚本中加入sys.path.append("/home/huawei/workspace/shiyan/InternLM-main/")就可以了，但是这个不应该做成参数，然后使用sys.path.append()去自动添加吗？我觉得是一个优化点~ 

最新已使用develop分支。

![Snipaste_2024-01-13_19-33-25](https://github.com/InternLM/InternLM/assets/67990935/b77870bb-954f-4d53-8288-d7c29cd8113d)
