### ISSUE TITLE
[Bug] ImportError: einops

### ISSUE THREAD

**Issue by kkscilife** [InternLM/InternLM#592]
### Describe the bug

according to requeirements and notes，run in my environment, there is a import errror:

transformers/dynamic_module_utils.py", line 151, in check_imports
    raise ImportError(
ImportError: This modeling file requires the following packages that were not found in your environment: einops. Run `pip install einops`

It's best to write the einops in requirements

### Environment

python 3.10

**Comment by ZwwWayne** [comment]
Simply pip install einops could solve your issue. Furthermore, this project no longer maintains the training functionality. You may be interested in [InternEvo](https://github.com/InternLM/InternEvo)

**Comment by navvye** [comment]
Had the same issue, installing einops doesn't work either.
