### ISSUE TITLE
模型自行进行多轮对话问题

### ISSUE THREAD

**Issue by dearchill** [InternLM/InternLM#60]
### 描述该错误

您好，我们在调用internlm-chat-7b这个模型的时候，发现模型针对一些prompt，会自行进行多轮对话。我看到官方提供的对话实例是model.chat，这个在内部实现是用response.split("<eoa>")[0]来保证了只返回第一个回复。但是如果要使用这个模型进行后续的实验如RLHF等，在调用model.generate时会输出后面的多轮内容，相关token也会加入到计算中，这个是不可接受的。请问有什么方式来避免输出多轮对话的内容吗？

### 环境信息

略

**Comment by xusenlinzy** [comment]
(api-for-open-llm](https://github.com/xusenlinzy/api-for-open-llm/blob/master/SCRIPT.md#internlm)提拱了internlm-chat-7b模型的openai形式的接口，模型在生成时如果遇到 "<eoa>" token，则会中止生成，不会继续输出

**Comment by smallflyingpig** [comment]
同样遇到了这个问题，这个怎么解决？

**Comment by ZwwWayne** [comment]
It will use EOA token to end the generation. For now, it seems that in some cases the model cannot chat well, we are in the progress of improving it.
