### ISSUE TITLE
[关于200K Context window的问题]

### ISSUE THREAD

**Issue by White-Friday** [InternLM/InternLM#600]
### 描述问题

1. 我看config.json里面是最高是32K，如何使用才能达到所说的200k？
2. 如果使用vllm的话，需要修改哪些参数来达到200k

**Comment by QipengGuo** [comment]
推荐配套LMdeploy使用，https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/advance/long_context.md
vllm设置dynamic NTK factor理论上也可以。

**Comment by gaoyang07** [comment]
btw推荐使用InternLM2-Chat-7B/20B模型进行验证

**Comment by White-Friday** [comment]
好的，谢谢
