### ISSUE TITLE
Llama Compatible InternLM2 Release [Feature] 

### ISSUE THREAD

**Issue by brucethemoose** [InternLM/InternLM#610]
### Describe the feature

Going to echo what I posted here: https://huggingface.co/internlm/internlm2-chat-20b/discussions/1

> I'm not sure how different the architecture actually is, but could you change the config to be llama compatible instead of requiring custom runtime/tokenizer code?

> Custom code is a huge blocker to the highly optimized llama architecture infrastructure the community already uses... To be blunt, I can run Yi 34B 200K with a fraction of the resources it takes to run this 20B model, for the moment, and finetune it just about as efficiently with llama focused frameworks.

> Yi itself already went through this ordeal, and "llamafied" their release for broader compatibility: https://huggingface.co/01-ai/Yi-34B/discussions/11

**Comment by brucethemoose** [comment]
On second thought, the internlm deployment framework is pretty interesting, albeit not quite right for my personal and work use cases.

**Comment by yhcc** [comment]
Thank you for your suggestion. We are planning to offer a script that facilitates conversion between InternLM2 and LLaMA. However, we recommend using InternLM2 when feasible, primarily for its enhanced efficiency. InternLM2, which is adapted from LLaMA, streamlines the process by integrating the Wq, Wk, Wv weight matrices into a single matrix. This integration leads to approximately a 5% speed increase during training. Given the substantial costs associated with pre-training, this efficiency boost can result in significant savings.

**Comment by yhcc** [comment]
https://github.com/InternLM/InternLM/pull/627 Add a convert2llama script, which can help to convert huggingface internlm2 into huggingface llama format.

**Comment by Hukongtao** [comment]
> #627 Add a convert2llama script, which can help to convert huggingface internlm2 into huggingface llama format.

https://github.com/InternLM/InternLM/issues/771
The inference results of the scripts before and after the conversion are not completely consistent

**Comment by mochgolf** [comment]
> > #627 Add a convert2llama script, which can help to convert huggingface internlm2 into huggingface llama format.
> 
> #771 The inference results of the scripts before and after the conversion are not completely consistent

Have you solved this problem yet?
