### ISSUE TITLE
[QA] chat/web_demo.py 缺少相应依赖

### ISSUE THREAD

**Issue by KMnO4-zx** [InternLM/InternLM#617]
### 描述问题

在仓库`chat/web_demo.py`文件的第14行`from tools.transformers.interface import GenerationConfig, generate_interactive`

导入函数，并没有在 requirements或仓库内找到相应文件

![image](https://github.com/InternLM/InternLM/assets/77671993/2747a12b-7596-492f-ab86-47784f9516b4)

**Comment by chenchun0629** [comment]
切换到其他分支，然后复制tools/transformers/interface.py文件出来就可以了。

![image](https://github.com/InternLM/InternLM/assets/3328490/5f427a3e-2ed5-4803-90d7-1c6a82679d9f)

**Comment by Skye0824** [comment]
请问interface.py文件在哪里下载

**Comment by KMnO4-zx** [comment]
> 切换到其他分支，然后复制tools/transformers/interface.py文件出来就可以了。
> 
> ![image](https://private-user-images.githubusercontent.com/3328490/297579558-5f427a3e-2ed5-4803-90d7-1c6a82679d9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NDU0MjcsIm5iZiI6MTcwNTU0NTEyNywicGF0aCI6Ii8zMzI4NDkwLzI5NzU3OTU1OC01ZjQyN2EzZS0yZWQ1LTQ4MDMtOTBkNy0xYzZhODI2NzlkOWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMThUMDIzMjA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTVmNTQwZjFhZDMxNGQyMTJlZGJlZTA3NWNmN2QwN2MxNzc3YzEzM2EyMGMzODBjZDFkODBhOTBhYzY1ODk5OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.D4VPeB4QBSWCNJCrOHC_vOFGiO45-uzXiP4EmZ_nwfY)

只有一个main分支，没有其他分支呀

![image](https://github.com/InternLM/InternLM/assets/77671993/021aaced-055b-4215-937c-823a226962b3)

**Comment by RangiLyu** [comment]
> > 切换到其他分支，然后复制tools/transformers/interface.py文件出来就可以了。
> > ![image](https://private-user-images.githubusercontent.com/3328490/297579558-5f427a3e-2ed5-4803-90d7-1c6a82679d9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NDU0MjcsIm5iZiI6MTcwNTU0NTEyNywicGF0aCI6Ii8zMzI4NDkwLzI5NzU3OTU1OC01ZjQyN2EzZS0yZWQ1LTQ4MDMtOTBkNy0xYzZhODI2NzlkOWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMThUMDIzMjA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTVmNTQwZjFhZDMxNGQyMTJlZGJlZTA3NWNmN2QwN2MxNzc3YzEzM2EyMGMzODBjZDFkODBhOTBhYzY1ODk5OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.D4VPeB4QBSWCNJCrOHC_vOFGiO45-uzXiP4EmZ_nwfY)
> 
> 只有一个main分支，没有其他分支呀
> 
> ![image](https://private-user-images.githubusercontent.com/77671993/297582189-021aaced-055b-4215-937c-823a226962b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NDczNDcsIm5iZiI6MTcwNTU0NzA0NywicGF0aCI6Ii83NzY3MTk5My8yOTc1ODIxODktMDIxYWFjZWQtMDU1Yi00MjE1LTkzN2MtODIzYTIyNjk2MmIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDAzMDQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjMWE4ZTcwZGY5NWI4MmJmN2Y5YzQxNjMzOGE0MmVhNmJmZTUyMDVlZTEzYjE3ZmYwY2I3MzU3NmIzMWFiMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ktC6ngysb_kqzvB1qaMbcXzIwnBWqAcfBG7zAfoBKBA)

可以在这里下载 https://github.com/InternLM/InternEvo/tree/main/tools/transformers

**Comment by chenchun0629** [comment]
> > 切换到其他分支，然后复制tools/transformers/interface.py文件出来就可以了。
> > ![image](https://private-user-images.githubusercontent.com/3328490/297579558-5f427a3e-2ed5-4803-90d7-1c6a82679d9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NDU0MjcsIm5iZiI6MTcwNTU0NTEyNywicGF0aCI6Ii8zMzI4NDkwLzI5NzU3OTU1OC01ZjQyN2EzZS0yZWQ1LTQ4MDMtOTBkNy0xYzZhODI2NzlkOWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMThUMDIzMjA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTVmNTQwZjFhZDMxNGQyMTJlZGJlZTA3NWNmN2QwN2MxNzc3YzEzM2EyMGMzODBjZDFkODBhOTBhYzY1ODk5OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.D4VPeB4QBSWCNJCrOHC_vOFGiO45-uzXiP4EmZ_nwfY)
> 
> 只有一个main分支，没有其他分支呀
> 
> ![image](https://private-user-images.githubusercontent.com/77671993/297582189-021aaced-055b-4215-937c-823a226962b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NDc1MDYsIm5iZiI6MTcwNTU0NzIwNiwicGF0aCI6Ii83NzY3MTk5My8yOTc1ODIxODktMDIxYWFjZWQtMDU1Yi00MjE1LTkzN2MtODIzYTIyNjk2MmIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDAzMDY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyMmQ0NGM3NTc4OWQ0ZmVhOTQyZjQ4MzUwOGY2YzM1NGM2MDljYmM3ODU1NjI1ZTVlYTZiYmU0MTE5MzJmODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uNvCyDjEtMUyMpJoHUt8VYoZlZTCM8KgpGNwPiGP3EA)

用词不当。其他tag里面
![image](https://github.com/InternLM/InternLM/assets/3328490/8e5ab5a6-98de-4106-8213-663080fafa8c)

**Comment by ZwwWayne** [comment]
Sorry for the inconvenience. We will update the code.

**Comment by ZwwWayne** [comment]
resolved in #617
