### ISSUE TITLE
你们公司是不是对  Apache-2.0 开源协议 有点误解？

### ISSUE THREAD

**Issue by jiangzhonglian** [InternLM/InternLM#62]
### 描述该功能

> 你们的开源许可证

本仓库的代码依照 Apache-2.0 协议开源。模型权重对学术研究完全开放，也可申请免费的商业使用授权（[申请表](https://wj.qq.com/s2/12725412/f7c1/)）。其他问题与合作请联系 [internlm@pjlab.org.cn](mailto:internlm@pjlab.org.cn)。

但 Apache-2.0 这个协议本身就支持商业化授权，是不需要再找你们申请的！

![image](https://github.com/InternLM/InternLM/assets/9199175/fe7d4780-751f-49d3-a365-2e965f52c2fb)

> 申请限制

而且你的申请表只支持公司，不支持个人，我没太懂：[彻底开源，免费商用，上海AI实验室把大模型门槛打下来](https://mp.weixin.qq.com/s/oTXnvWZJVdoOpFLHngbTYQ) 是什么意思。

能解释一下，你们是怎么做出这个决定？

### 是否希望自己实现该功能？

- [ ] 我希望自己来实现这一功能，并向 InternLM 贡献代码！

**Comment by hellock** [comment]
如文档所说，代码和模型权重是分开进行授权许可的，整个代码库采用标准的Apache 2.0协议，只要在遵守协议的前提下，可以进行任意商业和非商业的使用，由于目前相关政策和法律法规，大模型的使用有一定敏感性，所以我们针对模型权重会有专门的授权协议，它对学术研究完全开放，同时也可免费商用，只需要通过申请表提交基本信息，也不收取任何费用

**Comment by jiangzhonglian** [comment]
你的申请表只支持公司，不支持个人，是高层有什么考虑吗？

**Comment by hellock** [comment]
可以描述一下个人进行商用的场景吗
