### ISSUE TITLE
[QA] 200k原版大海捞针效果不对。推理方式是，32k内正常推，32k外dynamic ntk吗？

### ISSUE THREAD

**Issue by HaoshengZou** [InternLM/InternLM#623]
根据config.json，是32k内正常推，32k外dynamic ntk？

大海捞针200k的时候也是这么推理的吗？

初步用lightllm实现了“32k内正常推，32k外dynamic ntk”的推理方法，测了internlm2-chat-7b在原版大海捞针200k长度时的几个case，胡乱输出英文。是不是用错了模型或者推理setting有误？scaling_factor要额外设置吗？

如何复现公众号里7B-200k的大海捞针结果？

**Comment by yhcc** [comment]
感谢关注，我们正在准备详细的复现说明，应该在这周会发出来，里面比较关键的是超过一定长度之后需要调整rope alpha。发出来之后我们也会在这里update一下。

**Comment by ZwwWayne** [comment]
使用lmdeploy可以复现

**Comment by yhcc** [comment]
https://zhuanlan.zhihu.com/p/678784248 可以参考这个知乎文章精准复现
