### ISSUE TITLE
[Docs] 缺少Requirements描述

### ISSUE THREAD

**Issue by MING-ZCH** [InternLM/InternLM#628]
### 📚 描述文档中的错误

文档缺少Requirements描述，建议添加对应描述

### 📚 描述文档中的改进建议

⭐建议在readme中提供环境需要的安装包版本格式
* Example (https://github.com/QwenLM/Qwen)
<img width="484" alt="1705590458689" src="https://github.com/InternLM/InternLM/assets/119648793/8123d732-d994-404c-9af7-4688862afe15">

**Comment by ZwwWayne** [comment]
We are fully testing different pytorch versions. For now, we can confirm we should use transformers>=4.34
