### ISSUE TITLE
[QA] 请问InternLM2在SFT和RLHF时使用的system是什么？下游使用或微调时是否需要使用相同的system？

### ISSUE THREAD

**Issue by xyfZzz** [InternLM/InternLM#639]
### Describe the question.

有两个问题请教一下：
1、请问InternLM2在SFT和RLHF时使用的system是什么？
2、下游使用或微调时是否需要使用相同的system？如果不使用system或使用不同的system会造成效果不好吗？

**Comment by ZwwWayne** [comment]
For SFT, we use projects based on [InternEvo](https://github.com/InternLM/InternEvo). We also recommend [Xtuner](https://github.com/InternLM/xtuner/) as it is easier to get start with.
For RLHF, we use an internal project based on Ray and InternEvo.
You can choose different system prompt for your own needs. It will affect the performance slightly.

**Comment by RangiLyu** [comment]
> > For SFT, we use projects based on [InternEvo](https://github.com/InternLM/InternEvo). We also recommend [Xtuner](https://github.com/InternLM/xtuner/) as it is easier to get start with. For RLHF, we use an internal project based on Ray and InternEvo. You can choose different system prompt for your own needs. It will affect the performance slightly.
> 
> 不好意思，我可能没表达清楚，我想问的是InternLM2在sft和rlhf时chat template中使用的system内容是什么？

训练时的system prompt是不固定的，根据语料的情况而定。下游微调时可以按需修改system prompt.

**Comment by xyfZzz** [comment]
> > > For SFT, we use projects based on [InternEvo](https://github.com/InternLM/InternEvo). We also recommend [Xtuner](https://github.com/InternLM/xtuner/) as it is easier to get start with. For RLHF, we use an internal project based on Ray and InternEvo. You can choose different system prompt for your own needs. It will affect the performance slightly.
> > 
> > 
> > 不好意思，我可能没表达清楚，我想问的是InternLM2在sft和rlhf时chat template中使用的system内容是什么？
> 
> 训练时的system prompt是不固定的，根据语料的情况而定。下游微调时可以按需修改system prompt.

额，也就是说你们在sft或者rlhf时并不是固定使用的chat_format_zh-CN.md中所写的"你是书生浦语2，一个无害的人工智能助手"这个prompt，实际使用时不使用"你是书生浦语2，一个无害的人工智能助手"作为system也不会有影响对么？

**Comment by RangiLyu** [comment]
> 额，也就是说你们在sft或者rlhf时并不是固定使用的chat_format_zh-CN.md中所写的"你是书生浦语2，一个无害的人工智能助手"这个prompt，实际使用时不使用"你是书生浦语2，一个无害的人工智能助手"作为system也不会有影响对么？

对，system prompt可以按你的使用场景进行调整，比如你可以通过替换不同的system prompt让模型在对话时扮演不同的角色。

**Comment by xyfZzz** [comment]
> template



> > 额，也就是说你们在sft或者rlhf时并不是固定使用的chat_format_zh-CN.md中所写的"你是书生浦语2，一个无害的人工智能助手"这个prompt，实际使用时不使用"你是书生浦语2，一个无害的人工智能助手"作为system也不会有影响对么？
> 
> 对，system prompt可以按你的使用场景进行调整，比如你可以通过替换不同的system prompt让模型在对话时扮演不同的角色。

好的，感谢，我就是担心改了这个system的内容导致指令跟随能力变差。

> > 额，也就是说你们在sft或者rlhf时并不是固定使用的chat_format_zh-CN.md中所写的"你是书生浦语2，一个无害的人工智能助手"这个prompt，实际使用时不使用"你是书生浦语2，一个无害的人工智能助手"作为system也不会有影响对么？
> 
> 对，system prompt可以按你的使用场景进行调整，比如你可以通过替换不同的system prompt让模型在对话时扮演不同的角色。

好的，感谢，我就是担心改了这个system的内容导致指令跟随能力变差。

**Comment by xyfZzz** [comment]
> > 额，也就是说你们在sft或者rlhf时并不是固定使用的chat_format_zh-CN.md中所写的"你是书生浦语2，一个无害的人工智能助手"这个prompt，实际使用时不使用"你是书生浦语2，一个无害的人工智能助手"作为system也不会有影响对么？
> 
> 对，system prompt可以按你的使用场景进行调整，比如你可以通过替换不同的system prompt让模型在对话时扮演不同的角色。

好的，感谢，我就是担心改了这个system的内容导致指令跟随能力变差。
