### ISSUE TITLE
大致多久能收到商业授权反馈？[Feature] 

### ISSUE THREAD

**Issue by skykiseki** [InternLM/InternLM#64]
### 描述该功能

已按制式用公司信息填写申请表

### 是否希望自己实现该功能？

- [ ] 我希望自己来实现这一功能，并向 InternLM 贡献代码！

**Comment by huangbaichao** [comment]
请问申请表哪里下载？

**Comment by hellock** [comment]
> 请问申请表哪里下载？

可参考 https://github.com/InternLM/InternLM#license
