### ISSUE TITLE
[Bug] internlm2-chat-20b在回复时会有时会出现显式输出<|im_end|>，且不能正常停止的情况

### ISSUE THREAD

**Issue by wwewwt** [InternLM/InternLM#642]
### 描述该错误

在https://studio.intern-ai.org.cn/  的 A100 (1/4) * 2 配置的服务器上 运行
[web_demo.py](https://github.com/InternLM/InternLM/blob/main/chat/web_demo.py)

显式输出<|im_end|>
![image](https://github.com/InternLM/InternLM/assets/3361335/41deaf1c-d55f-4b2e-b4c8-34b79ffbac75)
显式输出<|im_end|>且没有停止输出
![image](https://github.com/InternLM/InternLM/assets/3361335/4703cab4-4dba-4cb5-8d1a-2ec3e163d1fa)

### 环境信息

| NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.2     |

Name: torch
Version: 2.0.1
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration

**Comment by RangiLyu** [comment]
我们昨天更新了对话模板，请确保InternLM仓库以及Huggingface模型都为最新的更新过对话模板的版本。
具体为确保使用的代码和模型都合入了以下PR
InternLM：https://github.com/InternLM/InternLM/pull/634
Huggingface：https://huggingface.co/internlm/internlm2-chat-20b/discussions/3

**Comment by del-zhenwu** [comment]
可以问下`transformers`版本吗

**Comment by del-zhenwu** [comment]
> > > 我们昨天更新了对话模板，请确保InternLM仓库以及Huggingface模型都为最新的更新过对话模板的版本。 具体为确保使用的代码和模型都合入了以下PR InternLM：#634 Huggingface：https://huggingface.co/internlm/internlm2-chat-20b/discussions/3
> > 
> > 
> > 修改后，<|im_start|>、<|im_end|>等prompt中特殊字符并不会分词为上述pr中指定的token_id
> 
> 请确保使用了最新的tokenizer_config.json，我这边测试是正常的： ![image](https://private-user-images.githubusercontent.com/12907710/299159371-50060360-325b-4a55-a18b-6d9745d5209b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNzk2NDcsIm5iZiI6MTcwNjA3OTM0NywicGF0aCI6Ii8xMjkwNzcxMC8yOTkxNTkzNzEtNTAwNjAzNjAtMzI1Yi00YTU1LWExOGItNmQ5NzQ1ZDUyMDliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA2NTU0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyN2UxZTk4NzEyODRmYmUyYTk1ZDJkY2IwOTliNTdmZTQzYTg3OGU0MTY5NWI0MzMxYWQwMzBkNmU4ZTM2NTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gC3XW1hxPnGbPsM_CHOfsBOvbuRp3-2RqH4BGjerIrM)

不同 transformers  版本 encode 出来的结果不一样；可能类似这个问题：https://github.com/InternLM/InternLM/issues/649

**Comment by Pevernow** [comment]
https://huggingface.co/bartowski/internlm2-chat-7b-llama-exl2
使用更新后的tokenizer_config.json，但还是停不下来。
或许还有别的问题？
