### ISSUE TITLE
Failed to use gradient_checkpointing with Transformers[Bug] 

### ISSUE THREAD

**Issue by Henrychur** [InternLM/InternLM#644]
### Describe the bug

When I tried to use `gradient_checkpointing` to finetune the internlm2 with `transformers`, the error occurs:
AttributeError: 'InternLM2ForCausalLM' object has no attribute '_set_gradient_checkpointing'

I think there's a lack of the code
```py
    def _set_gradient_checkpointing(self, module, value=False):
        if isinstance(module, InternLM2Model):
            module.gradient_checkpointing = value
```
in class `InternLM2PreTrainedModel` in `modeling_internlm2.py` on the huggingface . When I add this line of code, the program seems to run normally.

### Environment

pytorch=1.13.1
cuda=12.0
transformers=4.28.1

**Comment by x54-729** [comment]
`_set_gradient_checkpoint` is not necessary in the newest version of transformers(>= 4.35.0), see this PR for more information: https://github.com/huggingface/transformers/pull/27073, you can update your transformers if necessary.
Also, we will discuss this issue later to decide how to adapt to the version change.
