### ISSUE TITLE
v100，cuda11.7推理长文档出现乱码

### ISSUE THREAD

**Issue by datalee** [InternLM/InternLM#647]
### Describe the bug

`'#', '是，'是： '0,0, '资产', '是', 5, 资产, 是', '3, 资产, 是，'的，是'，'，0, '资产，是，是'，'的资产, 是，'的，是，是, '资产, 是，'，是'，是，资产, '是, 是， '是，'是，是，是，是，是，是，是，是，'的',是，是，资产,是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是，是
`

config：
`01/22 15:04:34 - turbomind - INFO - found tp=4 in config.ini.
model_config:

[llama]
model_name = internlm2-chat-7b
tensor_para_size = 4
head_num = 32
kv_head_num = 8
vocab_size = 92544
num_layer = 32
inter_size = 14336
norm_eps = 1e-05
attn_bias = 0
start_id = 1
end_id = 2
session_len = 80000
weight_type = fp16
rotary_embedding = 128
rope_theta = 1000000.0
size_per_head = 128
group_size = 0
max_batch_size = 128
max_context_token_num = 1
step_length = 1
cache_max_entry_count = 0.3
cache_block_seq_len = 128
cache_chunk_size = -1
num_tokens_per_iter = 0
max_prefill_iters = 1
extra_tokens_per_iter = 0
use_context_fmha = 1
quant_policy = 0
max_position_embeddings = 32768
rope_scaling_factor = 3.0
use_logn_attn = 0
`

### Environment

`torch：2.0.1
cuda：11.7
lmdeploy：0.2.1
`

**Comment by lvhan028** [comment]
I'll check this issue tomorrow

**Comment by lvhan028** [comment]
是第一轮对话结果就不对么？

**Comment by LeonG7** [comment]
> session_len = 80000，这里改成210000试试，上下文窗口长度，不过我加了还是不对...

我发现了，修改config.ini可能不生效，要在调用模型的时候设置session_len 和rope_scaling_factor 参数的值才有用

**Comment by datalee** [comment]
> > session_len = 80000，这里改成210000试试，上下文窗口长度，不过我加了还是不对...
> 
> 我发现了，修改config.ini可能不生效，要在调用模型的时候设置session_len 和rope_scaling_factor 参数的值才有用

没错，确实是没生效，我在调用代码里改了

**Comment by lvhan028** [comment]
@LeonG7 @datalee 可以分享下你们的代码吗？
