### ISSUE TITLE
[QA] 我部署了internlm2-chat模型，利用调api的形式来测试，但会出现重复输出很多的问题，我的prompt和输出如下

### ISSUE THREAD

**Issue by abc123456cxx** [InternLM/InternLM#653]
### Describe the question.

![2024-01-24 14-22-49屏幕截图](https://github.com/InternLM/InternLM/assets/150245861/e135bbf8-04e5-4ccd-a1da-f430988237de)
![2024-01-24 14-23-27屏幕截图](https://github.com/InternLM/InternLM/assets/150245861/8a94ec73-c78f-4038-bff1-711f6d987fae)

**Comment by ZwwWayne** [comment]
You may consider set the repeatition penalty to 1.02 and try again.
