### ISSUE TITLE
[Bug] internlm2-20B 推理时出现乱码；internlm2-7B能够正常推理。

### ISSUE THREAD

**Issue by zexuanqiu** [InternLM/InternLM#657]
### 描述该错误

当我利用Lmdeploy框架进行internlm2-20b模型的推理时，推理的似乎全是乱码；在使用internlm2-7b进行推理时则没有这种情况，一般都能产生符合预期的回复。我的输入是中文，tokenize后的长度在1k-2k之间。乱码一般有两种形式，第一种是一直循环”|“这个字符直到达到最大长度，第二种是一些无意义的文字组合如 ”地在旁边的中好好“。在单卡80G A100进行推理。我试了以下两种gen_config，都是乱码回复。

```
gen_config = GenerationConfig(top_p=0.8,top_k=40,temperature=0.8,max_new_tokens=max_tokens)
gen_config = (top_p=1.0, top_k=1, temperature=0.01, max_new_tokens=max_tokens)

# 用于生成文本的代码:
pipe = pipeline(model_path, backend_config=backend_config)
output = pipe(input_to_model, gen_config=gen_config)
```

两种不同gen_config的乱码回复分别如下：

![image-20240125172446580](https://github.com/InternLM/InternLM/assets/45207683/00980f12-ecae-4bd3-9046-747b8aee24a5)
![2](https://github.com/InternLM/InternLM/assets/45207683/ae8e785d-da00-46f9-b5e8-c75e8475a32f)

Turbomindengine的设置为如下：

```
backend_config = TurbomindEngineConfig(tp=1, cache_max_entry_count=0.2)
```

terminal的backend_config输出为：

```
[llama]
model_name = internlm2-20b
tensor_para_size = 1
head_num = 48
kv_head_num = 8
vocab_size = 92544
num_layer = 48
inter_size = 16384
norm_eps = 1e-05
attn_bias = 0
start_id = 1
end_id = 2
session_len = 32776
weight_type = bf16
rotary_embedding = 128
rope_theta = 1000000.0
size_per_head = 128
group_size = 0
max_batch_size = 128
max_context_token_num = 1
step_length = 1
cache_max_entry_count = 0.2
cache_block_seq_len = 128
cache_chunk_size = -1
num_tokens_per_iter = 0
max_prefill_iters = 1
extra_tokens_per_iter = 0
use_context_fmha = 1
quant_policy = 0
max_position_embeddings = 32768
rope_scaling_factor = 0.0
use_logn_attn = 0
__pydantic_initialised__ = True
```

请问这种问题一般该咋解决呢？是我哪里设置得不对吗？谢谢。

### 环境信息

torch="2.1.2+cuda11.8"
lmdeploy="0.2.1"
transformers="4.37.0"

**Comment by e06084** [comment]
试试这个生成参数呢？
`gen_config = {
    "top_p": 1.0, 
    "top_k": 10,
    "temperature": 1.0, 
    "do_sample": True, 
    "repetition_penalty": 1.0
}`

**Comment by zexuanqiu** [comment]
> 试试这个生成参数呢？ `gen_config = { "top_p": 1.0, "top_k": 10, "temperature": 1.0, "do_sample": True, "repetition_penalty": 1.0 }`

还是乱码。gen_config设置为：
GenerationConfig(n=1, max_new_tokens=50, top_p=1.0, top_k=10, temperature=1.0, repetition_penalty=1.0, ignore_eos=False, random_seed=42, stop_words=None, bad_words=None)

![image](https://github.com/InternLM/InternLM/assets/45207683/c83f5a78-518a-4df7-87f7-d08b71188a93)

**Comment by zexuanqiu** [comment]
我试了下internlm2-chat-20B，是可以的，有正常回复。但internlm2-20B就是乱码。感觉有点奇怪。
