### ISSUE TITLE
[Bug] internlm2-chat-20b转换成llama使用vllm后会输出[UNUSED_TOKEN_145]

### ISSUE THREAD

**Issue by dafen12** [InternLM/InternLM#662]
### Describe the bug

如题

### Environment

1、使用最新版1.24号更新的internlm2-chat-20b
2、使用transformers==4.36.0
3、使用vllm==0.26
4、GPU A100

**Comment by dafen12** [comment]
prompt=['小明的爸爸只有三个儿子，小明1992年出生，大儿子叫大毛，二儿子叫二毛，今年是2023年，请问三儿子今年多大了?']
sampling_params = SamplingParams(temperature=0.01, top_p=0.01,repetition_penalty=1.0, max_tokens=500,stop_token_ids=[92542,2])
output = llm.generate(prompt, sampling_params) 
for i in output:
    print(i.outputs[0].text)
![image](https://github.com/InternLM/InternLM/assets/125680339/57afc84f-5c3f-4a85-b0f5-0f436f21f13d)

**Comment by RangiLyu** [comment]
应该是转换后的llama tokenizer有问题，可以试一下这个转好的llama tokenizer https://huggingface.co/RangiLyu/InternLM2-tokenizer-llama
另外，prompt需要使用chatml格式的对话模板进行chat，如果问题为“小明的爸爸只有三个儿子，小明1992年出生，大儿子叫大毛，二儿子叫二毛，今年是2023年，请问三儿子今年多大了?”，那么让模型续写的文本应当为
```
"<s><|im_start|>user\n小明的爸爸只有三个儿子，小明1992年出生，大儿子叫大毛，二儿子叫二毛，今年是2023年，请问三儿子今年多大了?<|im_end|>\n<|im_start|>assistant\n"
```
关于对话模板详见https://github.com/InternLM/InternLM/blob/main/chat/chat_format_zh-CN.md
