### ISSUE TITLE
api_server无法添加--session-len参数[Bug] 

### ISSUE THREAD

**Issue by xxg98** [InternLM/InternLM#678]
### 描述该错误

/root/autodl-tmp/projects/LLM/LMDeploy/lmdeploy/lib/python3.10/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
usage: lmdeploy [-h] [-v] {chat,lite,serve,convert,list,check_env} ...
lmdeploy: error: unrecognized arguments: --session_len 200000

### 环境信息

python3.10
cuda11.8

**Comment by lvhan028** [comment]
lmdeploy cli工具从原来使用fire包，改成使用argument parser。不再是--session_len，而是--session-len。

可以使用 lmdeploy serve api_sever -h 查看命令详情

**Comment by xxg98** [comment]
> lmdeploy cli工具从原来使用fire包，改成使用argument parser。不再是--session_len，而是--session-len。
> 
> 可以使用 lmdeploy serve api_sever -h 查看命令详情
好的，谢谢您
