### ISSUE TITLE
[Bug] LMdeploy跑出来的demo有问题

### ISSUE THREAD

**Issue by duliangang** [InternLM/InternLM#684]
### Describe the bug

![image](https://github.com/InternLM/InternLM/assets/1728593/aae0bba6-f403-462c-a01c-9aa52cc8dafb)

### Environment

lmDeploy版本0.2.2

**Comment by lvhan028** [comment]
0.2.2 还没有推到 pypi 上去，因为 lmdeploy 在 pypi 上空间不足了

**Comment by lvhan028** [comment]
internlm2模型中间有一次更新，改了 special token。请把 internlm2 模型更新到最新。

**Comment by duliangang** [comment]
git拉了最新的代码
![image](https://github.com/InternLM/InternLM/assets/1728593/915437cd-a742-42ef-83ef-798bba1cfa97)

**Comment by zhulinJulia24** [comment]
查看下transformers的版本是不是高于4.34.0

`pip show transformers`

internlm2的模型依赖了transformers>=4.34.0版本 

详见https://github.com/InternLM/InternLM/issues/649

**Comment by duliangang** [comment]
已解决，感谢，因为用20B 必须降版本，导致7B出问题了
