### ISSUE TITLE
[QA] 如果想基于internLM使用领域数据微调出一个领域模型，应该使用internLM-20B-chat还是internLM-20B-sft？

### ISSUE THREAD

**Issue by honglianglv** [InternLM/InternLM#694]
### Describe the question.

我想基于internLM训练一个公文生成模型，手头上有一些公文领域的数据，应该使用internLM-20B-chat还是internLM-20B-sft作为微调的基础模型？ 哪个效果更好一些？ 多谢啦

**Comment by RangiLyu** [comment]
internLM-20B-chat相比internLM-20B-sft，在ppo之后写作能力有比较大的提升，我个人感觉可以基于20B-chat试一下

**Comment by honglianglv** [comment]
> internLM-20B-chat相比internLM-20B-sft，在ppo之后写作能力有比较大的提升，我个人感觉可以基于20B-chat试一下

好的，多谢，我使用 internLM-20B-cha试试
