### ISSUE TITLE
[QA] 如何提升推理速度？

### ISSUE THREAD

**Issue by luzhongyu** [InternLM/InternLM#697]
### Describe the question.

目前使用qlora微调后的internlm2-chat-7b模型跑推理任务，使用model.chat()接口逐条调用，单条推理约5s，由于有大批量数据需要批量推理，效率较低，想问下如何提升单条推理速度或者是否可以批量推理？

**Comment by lvhan028** [comment]
可以使用推理库 [LMDeploy](https://github.com/InternLM/lmdeploy) 来加速推理过程。
离线批处理方法可以参考[这里](https://github.com/InternLM/InternLM#deployment)
