### ISSUE TITLE
请问是否支持在MindSpore的910A或者910B上部署？

### ISSUE THREAD

**Issue by ChingKwanCheung** [InternLM/InternLM#698]
### 描述问题

在MindFormers的介绍中看到，目前支持internlm_7b, internlm_20b, internlm_7b_lora在MindSpore上部署，请问internlm2是否也可以在MindSpore上部署？

**Comment by ZwwWayne** [comment]
internlm2 目前我们没完全验证尝试过，可能有一定的适配工作量，我们去了解一下哈

**Comment by HarleysZhang** [comment]
想问下，internlm2模型的 attention q k v 权重是合并在一起了吗，类似baichuan 模型那样吗model.layers.0.self_attn.W_pack.weight":

**Comment by gaoyang07** [comment]
> 想问下，internlm2模型的 attention q k v 权重是合并在一起了吗，类似baichuan 模型那样吗model.layers.0.self_attn.W_pack.weight":

wqkv是合到一起的，可以看这里的说明：https://github.com/InternLM/InternLM/blob/67c5e9dba732bacc4743d73641a17c9be007ed8e/tools/README.md?plain=1#L13-L15
