### ISSUE TITLE
[Bug] 微调eval阶段使用generate的结果会出现</s>

### ISSUE THREAD

**Issue by AZYoung233** [InternLM/InternLM#701]
### 描述该错误

微调internlm2-7b的base模型，在eval阶段使用generate时几乎每一个结果都会出现</s>，按理说这个token是一个pad_token，他似乎不应该大量出现在generate的结果中，我不确定这是什么原因，希望您可以抽空对我的问题进行回复，感谢~

### 环境信息

python       3.10.13 
transformers        4.36.1 
modelscope         1.10.0

**Comment by AZYoung233** [comment]
已经解决，因为我在处理标签的时候是先tokenizer再与输入进行拼接，导致标签中因为padding的原因存在很多pad_token

**Comment by gaoyang07** [comment]
您好，可否提供下具体的config与代码片段？

**Comment by AZYoung233** [comment]
> 您好，可否提供下具体的config与代码片段？

您好，该bug已解决
