### ISSUE TITLE
[QA] Number of training tokens for Internlm2 1.8B, 7B, and 20B?

### ISSUE THREAD

**Issue by RicardoDominguez** [InternLM/InternLM#711]
### Describe the question.

Hi,

What is the number of training tokens for Internlm2 1.8B, 7B, and 20B models?

Thanks for the great work!

**Comment by yhcc** [comment]
1.8B about 2.2T
7B\20B about 2.6T

**Comment by RicardoDominguez** [comment]
Thank you!
