### ISSUE TITLE
一人血书求讲解怎么来洗数据！

### ISSUE THREAD

**Issue by Jianfeng777** [InternLM/InternLM#718]
### 描述该功能

![d48fd2b2bcab5b2f7493abed89d953f](https://github.com/InternLM/InternLM/assets/108343727/f3671d7b-3d5b-4b85-a98b-54a307744cbb)
希望讲解高质量数据集的清洗方法！

### 是否希望自己实现该功能？

- [ ] 我希望自己来实现这一功能，并向 InternLM 贡献代码！

**Comment by Hongru0306** [comment]
微臣附议！

**Comment by EnableAsync** [comment]
+1

**Comment by MING-ZCH** [comment]
We just found the news from: _https://mp.weixin.qq.com/s/Pt02LXlh2Uu_hgM0ZL5GGg_
Greatly eager to learn about data cleaning！

**Comment by KMnO4-zx** [comment]
臣附议！

**Comment by hellock** [comment]
Please refer to the technical report of WanJuan-CC: https://arxiv.org/abs/2402.19282
