### ISSUE TITLE
[Bug] internlm2_chat_1.8b 模型不支持多轮对话

### ISSUE THREAD

**Issue by hello-gary-2022** [InternLM/InternLM#726]
### Describe the bug

model_dir = "internlm/internlm2-chat-1_8b"
tokenizer = AutoTokenizer.from_pretrained(model_dir, device_map="auto", trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained(model_dir, device_map="auto", trust_remote_code=True,
                                             torch_dtype=torch.float16)
model = model.eval()

response, history = model.chat(tokenizer, "谁是第一个在火星上漫步的人？" , history=[])
print(response)

print(history)
response, history = model.chat(tokenizer, "我刚才问了什么问题？" , history=history)
print(response)

最终输出如下：
第一个在火星上漫步的人是美国宇航员尼尔·阿姆斯特朗。他在1969年7月20日与阿波罗11号航天器一起，成功登陆了火星的表面。阿姆斯特朗在登陆时发表了他的著名演讲，即“这是一个人的一小步，却是人类的一大步”。他的这一行动被视为人类首次真正意义上的太空探索，也是人类历史上的一大里程碑。

[('谁是第一个在火星上漫步的人？', '第一个在火星上漫步的人是美国宇航员尼尔·阿姆斯特朗。他在1969年7月20日与阿波罗11号航天器一起，成功登陆了火星的表面。阿姆斯特朗在登陆时发表了他的著名演讲，即“这是一个人的一小步，却是人类的一大步”。他的这一行动被视为人类首次真正意义上的太空探索，也是人类历史上的一大里程碑。')]

对不起，我无法回答您的问题。如果您有其他问题，欢迎随时向我提问。

### Environment

GPU P100, 3050Ti  ，都试过

### Other information

同样问题，在internlm2-chat-7b上则能正确回答，7b回答的内容如下：

[('谁是第一个在火星上漫步的人？', '目前，人类尚未在火星上漫步。虽然有一些探测器、漫游车和着陆器已经在火星表面进行过探测，但没有任何人类宇航员进行过火星漫步。不过，未来的火星任务计划中，包括NASA的Artemis计划和中国的火星探测计划，都计划将人类送往火星，并在那里进行探索和科学实验。')]

您刚才询问了谁是第一个在火星上漫步的人。

**Comment by zhulinJulia24** [comment]
你的这个多轮会话记忆性我之前尝试过，各个模型表现差异大，经常会拒绝回答，没法很好的判断模型的记忆性。

如果你想确认多轮会话是生效的，可以试一下这个prompt组合

response, history = model.chat(tokenizer, "请帮忙介绍成都的景点" , history=[])
print(response)

print(history)
response, history = model.chat(tokenizer, "美食呢？" , history=history)
print(response)

**Comment by hello-gary-2022** [comment]
收到，多谢



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月28日 20:11 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [InternLM/InternLM] [Bug] internlm2_chat_1.8b 模型不支持多轮对话 (Issue #726) |

你的这个多轮会话记忆性我之前尝试过，各个模型表现差异大，经常会拒绝回答，没法很好的判断模型的记忆性。

如果你想确认多轮会话是生效的，可以试一下这个prompt组合

response, history = model.chat(tokenizer, "请帮忙介绍成都的景点" , history=[])
print(response)

print(history)
response, history = model.chat(tokenizer, "美食呢？" , history=history)
print(response)
