### ISSUE TITLE
[Feature] convert2llama.py

### ISSUE THREAD

**Issue by bladeswill** [InternLM/InternLM#729]
### 描述该功能

The tool tools/convert2llama.py is no longer functional due to changes in the internlm2 series models, such as the conversion from .bin to .safetensors.

### 是否希望自己实现该功能？

- [ ] 我希望自己来实现这一功能，并向 InternLM 贡献代码！

**Comment by gaoyang07** [comment]
Thanks for the reminder. We will update it soon.
