### ISSUE TITLE
[Bug] safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

### ISSUE THREAD

**Issue by yuanphoenix** [InternLM/InternLM#731]
### Describe the bug

After converting using tools/convert2llama.py to LLama architecture, I encountered an error when loading with transformers.
`    
model = AutoModelForCausalLM.from_pretrained(model_dir, device_map="auto")
`

then throw an error

safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

### Environment

transformers-4.36.2
python 3.9.18

### Other information

Saving to intern2_llama/model-00009-of-00021.safetensors...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 36/36 [07:33<00:00, 12.59s/it]
Saving config and tokenizer...
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'InternLM2Tokenizer'. 
The class this function is called from is 'LlamaTokenizer'.
You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
Done!

**Comment by yuanphoenix** [comment]
My model file is  safetensors

**Comment by gaoyang07** [comment]
Based on the discussion in the linked issue, the problem is likely caused by a corrupted file: https://github.com/huggingface/transformers/issues/27923. You might want to try downloading it again.

**Comment by yuanphoenix** [comment]
I solve  it

**Comment by Ciao-CA** [comment]
> I solve it

excuse me but how did you solve it? I also meet this question and I have no idea now.
I have re-downloaded safetensors but it doesn't work.

**Comment by yuanphoenix** [comment]
> > I solve it
> 
> excuse me but how did you solve it? I also meet this question and I have no idea now. I have re-downloaded safetensors but it doesn't work.

https://github.com/InternLM/InternLM/pull/732
you can see this pull.But this may not be universal
