### ISSUE TITLE
[QA] 请问如何在昇腾910上进行模型微调？

### ISSUE THREAD

**Issue by rourouZ** [InternLM/InternLM#736]
### 描述问题

昇腾910 微调7B

**Comment by gaoyang07** [comment]
您好，InternLM 支持在开源仓库 [InternEvo](https://github.com/InternLM/InternEvo) 上使用 NPU 进行微调，只需要使用 torch2.1，且在 torchrun 启动时导入环境变量：`export INTERNLM_ACCELERATOR="npu"`即可（其余 NPU 启动命令请参考华为相关文档）

**Comment by rourouZ** [comment]
感谢！
请问lora微调支持吗

**Comment by gaoyang07** [comment]
InternEvo 暂时不支持 Lora 微调，不过未来这部分会考虑开源 :)
