### ISSUE TITLE
[Feature] 一个把internLM2 LoRA部分转换成llama风格的脚本

### ISSUE THREAD

**Issue by ChengYouFancy** [InternLM/InternLM#737]
### Describe the feature

为了解决多任务之间可能互相影响的问题，现在有一个成熟可用的基于LoRA路由的技术方案，详见https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/llama#run-llama-with-several-lora-checkpoints。
因此，需要将internLM2 LoRA部分转换成llama风格

### Will you implement it?

- [ ] I would like to implement this feature and create a PR!

**Comment by puffy310** [comment]
InternLM2 has already been Llamafied. https://huggingface.co/KnutJaegersberg/internlm-20b-llama/
This should hopefully be able to do what you need it to do.
