### ISSUE TITLE
[Bug] `rope_scaling` is `null`

### ISSUE THREAD

**Issue by pppppM** [InternLM/InternLM#743]
### Describe the bug

https://huggingface.co/internlm/internlm2-chat-7b/blob/main/config.json#L25

This issue will cause an error when using `lmdeploy` for long text extrapolation.

### Environment

The latest internlm model from HF Hub

**Comment by pppppM** [comment]
@lvhan028 Anything to add?

**Comment by lvhan028** [comment]
> @lvhan028 Anything to add?

This is what is needed when a long context is required
```
  "rope_scaling": {
    "factor": 2.0,
    "type": "dynamic"
  },
```

**Comment by gaoyang07** [comment]
Fixed in https://huggingface.co/internlm/internlm2-20b/commit/d431f9e4014c895663f30e8942d6e3c1adb6b562
