### ISSUE TITLE
按readme加载7B 只输出编码

### ISSUE THREAD

**Issue by hopeforus** [InternLM/InternLM#75]
### Describe the bug

from transformers import AutoTokenizer, AutoModelForCausalLM
tokenizer = AutoTokenizer.from_pretrained("internlm/internlm-7b", trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained("internlm/internlm-7b", trust_remote_code=True).cuda()
model = model.eval()
inputs = tokenizer(["A beautiful flower"], return_tensors="pt")
for k,v in inputs.items():
gen_kwargs = {"max_length": 128, "top_p": 0.8, "temperature": 0.8, "do_sample": True, "repetition_penalty": 1.1}
output = model.generate(**inputs, **gen_kwargs)
print(output)
按照这个代码运行只输出编码
<img width="698" alt="截屏2023-07-14 09 32 16" src="https://github.com/InternLM/InternLM/assets/65801925/effcf86e-66dd-404b-96a0-8e5fbda53e58">

### Environment

from transformers import AutoTokenizer, AutoModelForCausalLM
tokenizer = AutoTokenizer.from_pretrained("internlm/internlm-7b", trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained("internlm/internlm-7b", trust_remote_code=True).cuda()
model = model.eval()
inputs = tokenizer(["A beautiful flower"], return_tensors="pt")
for k,v in inputs.items():
gen_kwargs = {"max_length": 128, "top_p": 0.8, "temperature": 0.8, "do_sample": True, "repetition_penalty": 1.1}
output = model.generate(**inputs, **gen_kwargs)
print(output)

**Comment by yhcc** [comment]
Sorry, we forgot to add the decode part, please add the following code before the `print` function
```
output = tokenizer.decode(output[0].tolist(), skip_special_tokens=True)
```

**Comment by hopeforus** [comment]
谢谢！好了
