### ISSUE TITLE
[QA] 为什么使用internlm2-chat-7b模型，在实现流式输出时，使用model.chat和model.generate输出结果不一样

### ISSUE THREAD

**Issue by LKAMING97** [InternLM/InternLM#750]
### Describe the question.

在model.generate之前，我已经使用model.apply_chat_template转换成对话形式，但是还是重复输出，使用chat的话就不会
![image](https://github.com/InternLM/InternLM/assets/90093699/286a756e-f734-489d-81f9-405ddd7a8b48)
Transformers版本是最新的

**Comment by ZwwWayne** [comment]
感谢你的反馈，apply_chat_template 的实现不一定和 chat 接口的实现一致，我们排查一下。
以及，请问使用了 greedy decoding 么？

**Comment by RangiLyu** [comment]
请问你的generate代码是什么样子的呢？我用这种方式是可以正常停止的：

```python
import torch
from transformers import AutoModel, AutoTokenizer

# 准备语言模型和分词器
llm = AutoModel.from_pretrained(
    "internlm/internlm2-chat-1_8b",
    device_map="cuda", 
    torch_dtype=torch.float16, 
    trust_remote_code=True,
)
tokenizer = AutoTokenizer.from_pretrained("internlm/internlm2-chat-1_8b", trust_remote_code=True)


# 准备提示词
prompt = "你好!"
messages = [
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": prompt}
]
text = tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True
)
model_inputs = tokenizer([text], return_tensors="pt").to("cuda")



outputs = llm.generate(
    **model_inputs,
    max_new_tokens=512,
    pad_token_id=tokenizer.eos_token_id,
    do_sample=True,
    top_k=50,
    top_p=0.95,
    temperature=0.8,
)
outputs = outputs[:, model_inputs["input_ids"].shape[1]:]


print(tokenizer.decode(outputs[0], skip_special_tokens=False))
```

transformers版本是4.41.2

**Comment by LKAMING97** [comment]
> ```python
> e(outputs[0], 
> ```

![image](https://github.com/InternLM/InternLM/assets/90093699/e6478c1a-0f6c-4c8b-9336-6b62e7e2b281)
这是我的代码实现，然后下面是我的输出结果
使用apply_chat_template：
我是一个名叫书生·浦语的人工智能助手，由上海人工智能实验室开发。我致力于通过执行常见的基于语言的任务和提供建议来帮助人类。我能够回答问题、提供定义和解释、将文本从一种语言翻译成另一种语言、总结文本、生成文本、编写故事、分析情感、提供推荐、开发算法、编写代码以及其他任何基于语言的任务。不过，需要注意的是，我不能看、听、尝、触摸、闻、移动、与物理世界交互、感受情感或体验感官输入，也不能执行需要身体能力的任务。

```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
==================================================
使用chat：
我是书生·浦语，一个由上海人工智能实验室开发的AI助手。我的设计目标是能够通过执行常见的基于语言的任务和提供建议来帮助人类。我能够回答问题、提供定义和解释、将文本从一种语言翻译成另一种语言、总结文本、生成文本、编写故事、分析情感、提供推荐、开发算法、编写代码以及其他任何基于语言的任务。但我不能看、听、尝、触摸、闻、移动、与物理世界交互、感受情感或体验感官输入，也不能执行需要身体能力的任务。

**Comment by LKAMING97** [comment]
我的transformers版本也是4.41.2, 之前是greedy search，所以重复回答，现在改回sampling search,设置参数与chat内部默认参数之后，代码以及运行结果如下所示
![image](https://github.com/InternLM/InternLM/assets/90093699/97e80b6e-55cc-49d2-bc3a-56d66a31306d)
使用apply_chat_template：
我是一个名叫书生·浦语的人工智能助手，由上海人工智能实验室开发。我致力于通过执行常见的基于语言的任务和提供建议来帮助人类。我能够回答问题、提供定义和解释、将文本从一种语言翻译成另一种语言、总结文本、生成文本、编写故事、分析情感、提供推荐、开发算法、编写代码以及其他任何基于语言的任务。不过，需要注意的是，我不能看、听、尝、触摸、闻、移动、与物理世界交互、感受情感或体验感官输入，也不能执行需要身体能力的任务。

```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
==================================================
使用chat：
我是书生·浦语，一个由上海人工智能实验室开发的AI助手。我的设计目标是能够通过执行常见的基于语言的任务和提供建议来帮助人类。我能够回答问题、提供定义和解释、将文本从一种语言翻译成另一种语言、总结文本、生成文本、编写故事、分析情感、提供推荐、开发算法、编写代码以及其他任何基于语言的任务。但我不能看、听、尝、触摸、闻、移动、与物理世界交互、感受情感或体验感官输入，也不能执行需要身体能力的任务。

**Comment by LKAMING97** [comment]
我的transformers库也是4.41.2，代码实现以及结果如下所示
![image](https://github.com/InternLM/InternLM/assets/90093699/191f0835-801e-46ca-a03c-b1a8606aa345)
![image](https://github.com/InternLM/InternLM/assets/90093699/e39b97b0-e88c-4fa7-9782-4aa5a6287023)
![image](https://github.com/InternLM/InternLM/assets/90093699/75cc5ecf-5e35-4bba-bf5f-9d43bd18d9f5)

**Comment by LKAMING97** [comment]
> 感谢你的反馈，apply_chat_template 的实现不一定和 chat 接口的实现一致，我们排查一下。 以及，请问使用了 greedy decoding 么？

之前是因为greedy decoding引起的重复生成，后面改为sampling search之后还出现这样的问题，不知道是自己哪里操作出问题了

**Comment by RangiLyu** [comment]
检查一下你的模型文件夹下面的generation_config.json是不是长这样，
```
{
  "bos_token_id": 1,
  "eos_token_id": [
    2,
    92542
  ],
  "pad_token_id": 2,
  "transformers_version": "4.37.1"  # 这个可以忽略
}
```

这个文件之前因为transformers的版本变动更新过一次，不确定是不是因为你用的本地模型没有同步到最新的修改导致的

**Comment by LKAMING97** [comment]
> 检查一下你的模型文件夹下面的generation_config.json是不是长这样，
> 
> ```
> {
>   "bos_token_id": 1,
>   "eos_token_id": [
>     2,
>     92542
>   ],
>   "pad_token_id": 2,
>   "transformers_version": "4.37.1"  # 这个可以忽略
> }
> ```
> 
> 这个文件之前因为transformers的版本变动更新过一次，不确定是不是因为你用的本地模型没有同步到最新的修改导致的

嗯嗯，发现是eos_token_id少了
![image](https://github.com/InternLM/InternLM/assets/90093699/4122da93-0ad1-4ac3-8ba6-806de7e74741)
