### ISSUE TITLE
[Bug] ModuleNotFoundError: No module named 'transformers_modules.InternLM2'

### ISSUE THREAD

**Issue by ssgg-code** [InternLM/InternLM#756]
### 描述该错误

'''
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '6'
tokenizer = AutoTokenizer.from_pretrained("/nvme/models/InternLM2.5-7B", trust_remote_code=True)
# Set `torch_dtype=torch.float16` to load model in float16, otherwise it will be loaded as float32 and cause OOM Error.
model = AutoModelForCausalLM.from_pretrained("/nvme/models/InternLM2.5-7B", torch_dtype=torch.float16, trust_remote_code=True).cuda()
model = model.eval()
response, history = model.chat(tokenizer, "hello", history=[])
print(response)
# Hello! How can I help you today?
response, history = model.chat(tokenizer, "please provide three suggestions about time management", history=history)
print(response)
'''
我用官网的代码加载模型，transformers版本尝试了4.41.0和4.38.1，都是同样的错误，都没有InterLM2 Model

### 环境信息

transformers = 4.41.0

**Comment by RangiLyu** [comment]
如果是调用本地模型，最内层目录的名称中不能包含`.`的符号，这是transformers加载动态包时候的限制，你可以把路径重命名为`/nvme/models/InternLM2_5-7B`
