### ISSUE TITLE
[Feature] Is there any plan to merge the modeling_internlm2.py into the Transformers library?

### ISSUE THREAD

**Issue by iofu728** [InternLM/InternLM#757]
### Describe the feature

Hi InternLM Team,

Thanks for your great work and the powerful InternLM2.5 models. I'm currently conducting research on efficient long-context LLMs inference, [MInference](https://aka.ms/MInference) and am trying to implement our method in InternLM-2.5-1M. To reduce the effort, I wanted to ask if there are any plans to merge the modeling_internlm2.py into the Transformers library? This would greatly help our work and benefit the community. Thanks for your help!

### Will you implement it?

- [ ] I would like to implement this feature and create a PR!

**Comment by datalee** [comment]
期待

**Comment by gaoyang07** [comment]
It's on the upcoming roadmap. Stay tuned.
