### ISSUE TITLE
[Bug] internlm2_5-7b-chat使用lmdeploy serve api_server发布服务，调用出现重复生成现象

### ISSUE THREAD

**Issue by datalee** [InternLM/InternLM#758]
### 描述该错误

1、下载模型：https://huggingface.co/internlm/internlm2_5-7b-chat
2、发布服务：`lmdeploy serve api_server internlm2_5-7b-chat/ --server-port 11437 --cache-max-entry-count 0.2 --rope-scaling-factor 0.2 --session-len 32000 &`
3、调用服务：`
url:http://xxxxx:11437/v1/chat/completions
`
入参：`{
  "model": "internlm2_5-7b-chat/",
  "messages": [
    {
      "content": "请提取问题中的关键词，需要中英文均有，可以适量补充不在问题中但相关的关键词。关键词尽量切分为动词、名词、或形容词等单独的词，不要长词组（目的是更好的匹配检索到语义相关但表述不同的相关资料）。关键词以JSON的格式给出，比如{\"keywords_zh\": [\"关键词1\", \"关键词2\"], \"keywords_en\": [\"keyword 1\", \"keyword 2\"]}\n\nQuestion: 这篇文章的作者是谁？\nKeywords: {\"keywords_zh\": [\"作者\"], \"keywords_en\": [\"author\"]}\n\nQuestion: 解释下图一\nKeywords: {\"keywords_zh\": [\"图一\", \"图 1\"], \"keywords_en\": [\"Figure 1\"]}\n\nQuestion: 核心公式\nKeywords: {\"keywords_zh\": [\"核心公式\", \"公式\"], \"keywords_en\": [\"core formula\", \"formula\", \"equation\"]}\n\nQuestion: 2024年公司有哪些变革项目\nKeywords:\n",
      "role": "user"
    }
  ],
  "temperature": 0.7,
  "top_p": 1,
  "logprobs": false,
  "top_logprobs": 0,
  "n": 1,
  "max_tokens": null,
  "stop": null,
  "stream": false,
  "presence_penalty": 0,
  "frequency_penalty": 0,
  "user": "string",
  "repetition_penalty": 1,
  "session_id": -1,
  "ignore_eos": false,
  "skip_special_tokens": true,
  "top_k": 40
}`

出参：（因太长，手动删除后面一部分输出）
`{
  "id": "11",
  "object": "chat.completion",
  "created": 1720138845,
  "model": "internlm2_5-7b-chat/",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": "{\"keywords_zh\": [\"2024年\", \"公司变革项目\", \"变革项目\", \"项目\", \"变更\", \"公司\", \"2024年变革项目\", \"2024年公司项目变化\", \"公司2024年新项目\", \"公司2024年变革计划\", \"2024年公司策略调整\", \"2024年公司计划更新\", \"2024年公司改革计划\", \"2024年公司变化计划\", \"2024年公司运营改革\", \"2024年公司创新项目\", \"2024年公司转型计划\", \"2024年公司发展战略\", \"2024年公司新方向\", \"2024年公司新策略\", \"2024年公司新计划\", \"2024年公司新目标\", \"2024年公司新方向\", \"2024年公司新理念\", \"2024年公司新规划\", \"2024年公司新举措\", \"2024年公司新政策\", \"2024年公司新项目\", \"2024年公司新计划\", \"2024年公司新目标\", \"2024年公司新方向\", \"2024年公司新策略\", \"2024年公司新计划\", \"2024年公司新目标\", \"2024年公司新方向\", \"2024年公司新理念\", \"2024年公司新规划\", \"2024年公司新举措\", \"2024年公司新政策\", \"2024年公司新项目\", \"2024年公司新计划\", \"2024年公司新目标\", \"2024年公司新方向\", \"2024年公司新策略\", \"2024年公司新计划\", \"2024年公司新目标\", \"2024年公司新方向\", \"2024年公司新理念\", \"2024年公司新规划\", \"2024年公司新举措\", \"2024年公司新政策\", \"2024年公司新项目\", \"2024年公司新计划\", \"2024年公司新目标\", \"2024年公司新方向\", \"2024年公司新策略\", \"2024年公司新计划\", \"2024年公司新目标\", \"2024年公司新方向\", \"2024年公司新理念\", \"2024年公司新规划\", \"2024年公司新举措\", \"2024年公司新政策\", \"2024年公司新项目\", \"2024年公司新计划\", \"2024年公司新目标\", \"2024年公司新方向\", \"2024年公司新策略\", \"2024年公司新计划\", \"2024年公司新目标\", \"2024年公司新方向\", \"2024年公司新理念\", \"2024年公司新规划\", \"2024年公司新举措\", \"2024年公司新政策\", \"2024年公司新项目\", \"2024年公司新计划\", \"2024年公司新目标\", \"2024年公司新方向\", \"2024年公司新策略\", \"2024年公司新计划\", \"2024年公司新目标\", \"2024年公司新方向\", \"2024年公司新理念\", \"2024年公司新规划\", \"2024年公司新举措\", \"2024年公司新政策\", \"2024年公司新项目\", \"2024年公司新计划\", \"2024年公司新目标\", \"2024年公司新方向\", \"2024年公司新策略\", \"2024年公司新计划\", \"2024年公司新目标\", \"2024年公司新方向\", \"2024年公司新理念\", \"2024年公司新规划\", \"2024年公司新举措\", \"2024年公司新政策\", \"2024年公司新项目\", \"2024年公司新计划\", \"2024年公司新目标\", \"2024年公司新方向\", \"2024年公司新策略\", \"2024年公司新计划\", \"2024年公司新目标\", \"2024年公司新方向\", \"2024年公司新理念\", \"2024年公司新规划\", \"2024年公司新举措\", \"2024年公司新政策\", \"2024年公司新项目\", \"2024年公司新计划\", \"2024年公司新目标\", \"2024年公司新方向\", \"2024年公司新策略\", \"2024年公司新计划\", \"2024年公司新目标\", \"2024年公司新方向\", \"2024年公司新理念\", \"2024年公司新规划\", \"2024年公司新举措\", \"2024年公司新政策\", \"2024年公司新项目\", \"2024年公司新计划\", \"2024年公司新目标\", \"2024年公司新方向\", \"2024年公司新策略\", \"2024年公司新计划\", \"2024年公司新目标\", \"2024年公司新方向\", \"2024年公司新理念\", \"2024年公司新规划\", \"2024年公司新举措\", \"2024年公司新政策\", \"2024年公司新项目\", \"2024年公司新计划\", \"2024年公司新目标\", \"2024年公司新方向\", \"2024年公司新策略\", \"2024年公司新计划\", \"2024年公司新目标\", \"2024年公司新方向\", \"2024年公司新理念\", \"2024年公司新规划\", \"2024年公司新举措\", \"2024年公司新政策\", \"2024年公司新项目\", \"2024年公司新计划\", \"2024年公司新目标\", \"2024年公司新方向\", \"2024年公司新策略\", \"2024年公司新计划\", \"2024年公司新目标\", \"2024年公司新方向\", \"2024年公司新理念\", \"2024年公司新规划\", \"2024年公司新举措\", \"2024年公司新政策\", \"2024年公司新项目\", \"2024年公司新计划\", \"2024年公司新目标\", \"2024年公司新方向\", \"2024年公司新策略\", \"2024年公司新计划\", \"2024年公司新目标\", \"2024年公司新方向\", \"2024年公司新理念\", \"2024年公司新规划\", \"2024年公司新举措\", \"2024年公司新政策\", \"2024年公司新项目\", \"2024年公司新计划\"。。。。。。
      },
      "logprobs": null,
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": 303,
    "total_tokens": 12864,
    "completion_tokens": 12561
  }
}`

### 环境信息

`
sys.platform: linux
Python: 3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0,1,2,3,4,5,6,7: Tesla V100-PCIE-32GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.7, V11.7.64
GCC: gcc (GCC) 7.3.0
PyTorch: 2.1.2+cu118
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.1.1 (Git Hash 64f6bcbcbab628e96f33a62c3e975f8535a7bde4)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.8
  - CuDNN 8.7
  - Magma 2.6.1

LMDeploy: 0.5.0+
transformers: 4.37.1
gradio: 3.40.0
fastapi: 0.109.0
pydantic: 2.5.3
triton: 2.1.0

`

**Comment by lvhan028** [comment]
`--rope-scaling-factor` is supposed to be greater than 1.0

**Comment by RangiLyu** [comment]
`rope-scaling-factor` 的推荐值为2.0，可参考模型配置 https://huggingface.co/internlm/internlm2_5-7b-chat/blob/main/config.json#L25

**Comment by datalee** [comment]
比较有意思的是在lmdeploy serve gradio里没出现这个情况
![image](https://github.com/InternLM/InternLM/assets/13651873/1ebe3722-45ef-4f13-9187-35e868034384)

**Comment by AllentDan** [comment]
是有偶发的这种重复输出。设置 `repetition_penalty=1.02` 后就没了好像

**Comment by datalee** [comment]
> 1.02

我这边设置为1.02也比较容易触发

**Comment by AllentDan** [comment]
用默认setting 启server，请求用 1.02

**Comment by datalee** [comment]
> 用默认setting 启server，请求用 1.02

但是我按你的要求重启了一版，发现，如果把温度和top_p调的比较低，基本上会必现上面的问题：
`  "temperature": 0.2,
  "top_p": 0.2,`

**Comment by lvhan028** [comment]
可以试试 transformers 是不是也有类似的问题，如果有的话，那需要在模型层面看看了

**Comment by datalee** [comment]
> 可以试试 transformers 是不是也有类似的问题，如果有的话，那需要在模型层面看看了

用transformers试了下，确实还会存在这个问题，那看来确实是模型训的稍微有点问题

`
In [13]: response, history = model.chat(tokenizer, "请提取问题中的关键词，需要中英文均有，可以适量补充不在问题中但相关的关键词。关键词尽量切分为动词、名词、或形容词等单独的词，不要长词组（目的是更好的匹配检索
    ...: 到语义相关但表述不同的相关资料）。关键词以JSON的格式给出，比如{\"keywords_zh\": [\"关键词1\", \"关键词2\"], \"keywords_en\": [\"keyword 1\", \"keyword 2\"]}\n\nQuestion: 这篇文章的作者是谁？\nKeyword
    ...: s: {\"keywords_zh\": [\"作者\"], \"keywords_en\": [\"author\"]}\n\nQuestion: 解释下图一\nKeywords: {\"keywords_zh\": [\"图一\", \"图 1\"], \"keywords_en\": [\"Figure 1\"]}\n\nQuestion: 核心公式\nKeyw
    ...: ords: {\"keywords_zh\": [\"核心公式\", \"公式\"], \"keywords_en\": [\"core formula\", \"formula\", \"equation\"]}\n\nQuestion: 2024年公司有哪些变革项目吗？\nKeywords:\n", history=[])

In [14]: print(response)
{"keywords_zh": ["2024年", "公司", "变革项目", "变革", "计划", "项目", "公司变革", "公司计划", "公司战略", "公司改革", "公司创新", "公司发展", "公司未来", "公司转型", "公司变革策略", "公司改革措施", "公司发展战略", "公司创新计划", "公司变革目标", "公司变革方向", "公司变革愿景", "公司变革路线图", "公司变革里程碑", "公司变革实施", "公司变革成果", "公司变革评估", "公司变革挑战", "公司变革风险", "公司变革机遇", "公司变革环境", "公司变革趋势", "公司变革影响", "公司变革背景", "公司变革动因", "公司变革动机", "公司变革目的", "公司变革目标群体", "公司变革利益相关者", "公司变革团队", "公司变革管理", "公司变革流程", "公司变革方法", "公司变革工具", "公司变革资源", "公司变革预算", "公司变革时间表", "公司变革评估标准", "公司变革效果", "公司变革反馈", "公司变革调整", "公司变革持续改进", "公司变革绩效", "公司变革绩效评估", "公司变革绩效指标", "公司变革绩效目标", "公司变革绩效考核", "公司变革绩效奖励", "公司变革绩效评估标准", "公司变革绩效评估方法", "公司变革绩效评估工具", "公司变革绩效评估指标", "公司变革绩效评估目标", "公司变革绩效评估考核", "公司变革绩效评估奖励", "公司变革绩效评估标准", "公司变革绩效评估方法", "公司变革绩效评估工具", "公司变革绩效评估指标", "公司变革绩效评估目标", "公司变革绩效评估考核", "公司变革绩效评估奖励", "公司变革绩效评估标准", "公司变革绩效评估方法", "公司变革绩效评估工具", "公司变革绩效评估指标", "公司变革绩效评估目标", "公司变革绩效评估考核", "公司变革绩效评估奖励", "公司变革绩效评估标准", "公司变革绩效评估方法", "公司变革绩效评估工具", "公司变革绩效评估指标", "公司变革绩效评估目标", "公司变革绩效评估考核", "公司变革绩效评估奖励", "公司变革绩效评估标准", "公司变革绩效评估方法", "公司变革绩效评估工具", "公司变革绩效评估指标", "公司变革绩效评估目标", "公司变革绩效评估考核", "公司变革绩效评估奖励", "公司变革绩效评估标准", "公司变革绩效评估方法", "公司变革绩效评估工具", "公司变革绩效评估指标", "公司变革绩效评估目标", "公司变革绩效评估考核", "公司变革绩效评估奖励", "公司变革绩效评估标准", "公司变革绩效评估方法", "公司变革绩效评估工具", "公司变革绩效评估指标", "公司变革绩效评估目标", "公司变革绩效评估考核", "公司变革绩效评估奖励", "公司变革绩效评估标准", "公司变革绩效评估方法", "公司变革绩效评估工具", "公司变革绩效评估指标", "公司变革绩效评估目标", "公司变革绩效评估考核", "公司变革绩效评估奖励", "公司变革绩效评估标准", "公司变革绩效评估方法", "公司变革绩效评估工具", "公司变革绩效评估指标", "公司变革绩效评估目标", "公司变革绩效评估考核", "公司变革绩效评估奖励", "公司变革绩效评估标准", "公司变革绩效评估方法", "公司变革绩效评估工具", "公司变革绩效评估指标", "公司变革绩效评估目标", "公司变革绩效评估考核", "公司变革绩效评估奖励", "公司变革绩效评估标准", "公司变革绩效评估方法", "公司变革绩效评估工具", "公司变革绩效评估指标", "公司变革绩效评估目标", "公司变革绩效评估考核", "公司变革绩效评估奖励", "公司变革绩效评估标准", "公司变革绩效评估方法", "公司变革绩效评估工具", "公司变革绩效评估指标", "公司变革绩效评估目标", "公司变革绩效评估考核", "公司变革绩效评估奖励", "公司变革绩效评估标准", "公司变革绩效评估方法", "公司变革绩效评估工具", "公司变革绩效评估指标", "公司变革绩效评估目标", "公司变革绩效评估考核", "公司变革绩效评估奖励", "公司变革绩效评估标准", "公司变革绩效评估方法", "公司变革绩效评估工具", "公司变革绩效评估指标", "公司变革绩效评估目标", "公司变革绩效评估考核", "公司变革绩效评估奖励", "公司变革绩效评估标准", "公司变革绩效评估方法", "公司变革绩效评估工具", "公司变革绩效评估指标", "公司变革绩效评估目标", "公司变革绩效评估考核", "公司变革绩效评估奖励", "公司

`

**Comment by datalee** [comment]
而且，我还发现一个问题：
多轮特别容易干扰指令，比如上一轮是提关键词的指令，下一轮换个换题，还是错认为是提关键词

**Comment by datalee** [comment]
又发现一个case：
```json
{
  "model": "internlm2_5-7b-chat",
  "messages": [
    {
      "content": "《are you ok》",
      "role": "user"
    }
  ],
  "temperature": 0.3,
  "top_p": 0.3,
  "logprobs": false,
  "top_logprobs": 0,
  "n": 1,
  "max_tokens": 1024,
  "repetition_penalty": 1,
  "session_id": 123456,
	"stream": false
}
``` 

```json
{
	"id": "250",
	"object": "chat.completion",
	"created": 1724746889,
	"model": "internlm2_5-7b-chat",
	"choices": [
		{
			"index": 0,
			"message": {
				"role": "assistant",
				"content": "《Are You OK》是一首由美国歌手Bruno Mars演唱的歌曲，收录在他的第三张录音室专辑《24K Magic》中。这首歌于2017年发布，迅速在全球范围内取得了巨大的成功，不仅在美国Billboard Hot 100榜单上排名第一，还在多个国家的音乐排行榜上名列前茅。\n\n《Are You OK》以其欢快的节奏、朗朗上口的旋律和充满正能量的歌词而受到广泛喜爱。歌曲的歌词鼓励人们面对生活中的挑战和困难，保持积极乐观的态度。Bruno Mars在歌曲中的表现力极强，他的声音温暖而富有感染力，使得这首歌成为了许多人心情低落时的慰藉。\n\n除了Bruno Mars的演唱外，这首歌还邀请了多位知名音乐人参与制作，包括James Fauntleroy、Ray McCullough II、Jeremy Reeves、Phil Lawrence、Chris Stainton、Ray McCullough II、James Prought、Jamal Westbrook、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray McCullough II、James Prought、Jamal Westbrook、Ray"
			},
			"logprobs": null,
			"finish_reason": "length"
		}
	],
	"usage": {
		"prompt_tokens": 107,
		"total_tokens": 1132,
		"completion_tokens": 1025
	}
}
```
