### ISSUE TITLE
关于模型适配国产服务器等硬件的问题

### ISSUE THREAD

**Issue by RyanOvO** [InternLM/InternLM#759]
### 描述问题

请问，internlm系列，尤其是最新的2.5，在国产显卡、GPU服务器等方面的支持情况是怎么样的？

**Comment by gaoyang07** [comment]
您好，现在 InternLM 系列支持使用 [InternEvo](https://github.com/InternLM/InternEvo) 开源框架在国产910B集群进行预训练/微调/RLHF，具体情况请访问 InternEvo 主页

**Comment by RyanOvO** [comment]
好的，已查阅相关文档，请问，你们有评估该方案的性能与效率吗？
