### ISSUE TITLE
[Bug] tokenizer alpaca_data.json 的时候遇到错误aborted

### ISSUE THREAD

**Issue by 2018211801** [InternLM/InternLM#76]
### Describe the bug

你好呀，我想微调咱们的大模型，但是在集群上直接出现了这个错误。这有可能是什么原因导致的呢？
python tools/alpaca_tokenizer.py /mnt/petrelfs/wangxiaochen/workspace/alpaca_data.json /mnt/petrelfs/wangxiaochen/workspace/dataset /mnt/petrelfs/wangxiaochen/workspace/pretrained_models/internlm-chat-7b --split_ratio 0.1

Aborted

### Environment

所有的环境按照说明配好，但是mpfr、mpc还没配置。在集群share区有此文件，却没法编译引用。

**Comment by angelOnly** [comment]
你这个问题，是你挂载的文件无法访问吧，我把文件放在服务器当前目录，不会出现这个错误呀

**Comment by 18065013** [comment]
python tools/alpaca_tokenizer.py /mnt/petrelfs/wangxiaochen/workspace/alpaca_data.json /mnt/petrelfs/wangxiaochen/workspace/dataset /mnt/petrelfs/wangxiaochen/workspace/pretrained_models/internlm-chat-7b --split_ratio 0.1

/mnt/petrelfs/wangxiaochen/workspace/pretrained_models/internlm-chat-7b 这个参数 tokenizer_path = tools/V7_sft.model

参见ci_scripts/data/tokenizer_alpaca.sh
