### ISSUE TITLE
[QA]  7B-4bit量化显存占用21GB多，是正常的吗？

### ISSUE THREAD

**Issue by yaleimeng** [InternLM/InternLM#760]
### Describe the question.

使用的是官方给的四行4bit推理代码，确实非常精简。
使用的GPU是RTX4090，推理时占用GPU21.4GB左右。速度还比较快吧，但感觉并没有降低显存占用。这是正常的吗？
```Python
from lmdeploy import pipeline
pipe = pipeline("internlm/internlm2_5-7b-chat-4bit")
response = pipe(["Hi, pls intro yourself", "Shanghai is"])
print(response)
```

**Comment by lvhan028** [comment]
LMDeploy 的内存分配策略是：把GPU free memory * ratio 分配给 kv cache.
ratio 通过参数 cache_max_entry_count 调节，默认值是 0.8。
当把模型量化为 4bit 后，权重占用的内存会减少到原来权重内存的 1/4。意味着剩余内存就多了。按照上述逻辑，kv cache获得的内存就变多了。
如果想让内存变小，可以把cache_max_entry_count调小一些，比如0.5.

**Comment by yaleimeng** [comment]
多谢解答。
