### ISSUE TITLE
求书生·浦语邀请码

### ISSUE THREAD

**Issue by Hansonwong47** [InternLM/InternLM#766]
### 描述问题

求书生·浦语邀请码,发送邀请码到这个邮箱：wongzhangjz@gmail.com

**Comment by liumy-lay** [comment]
扫码报名，填写邮箱，即可得到邀请码
![51aef636d9580cba5ef80fa3f204f2d](https://github.com/user-attachments/assets/03d520be-2c1d-465b-836a-725b9025d320)

**Comment by Hansonwong47** [comment]
![Uploading Screenshot_20240720_152925_Samsung Internet.jpg…]()

**Comment by Hansonwong47** [comment]
![Screenshot_20240720_152925_Samsung Internet](https://github.com/user-attachments/assets/b9eaee00-47f6-4293-9404-5d6a4b26efb7)

**Comment by Hansonwong47** [comment]
不行呀

**Comment by liumy-lay** [comment]
> 不行呀

你是不是已经注册过了账号，在登录界面以后才输入的这个邀请码，一开始我也是这样。退出登录重新试一下。

**Comment by Hansonwong47** [comment]
![Screenshot_20240720_161159_Samsung Internet](https://github.com/user-attachments/assets/f1fb0bd8-5ff0-4942-953f-f7bf20196087)

**Comment by Hansonwong47** [comment]
沒有呀

**Comment by liumy-lay** [comment]
> 沒有呀

进这个网址https://studio.intern-ai.org.cn/

**Comment by Hansonwong47** [comment]
之後呢

**Comment by liumy-lay** [comment]
> 之後呢

登录，然后应该有一个填写邀请码的地方

**Comment by liumy-lay** [comment]
> ![Screenshot_20240720_152925_Samsung Internet](https://private-user-images.githubusercontent.com/129591155/350672965-b9eaee00-47f6-4293-9404-5d6a4b26efb7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NjM4MjMsIm5iZiI6MTcyMTQ2MzUyMywicGF0aCI6Ii8xMjk1OTExNTUvMzUwNjcyOTY1LWI5ZWFlZTAwLTQ3ZjYtNDI5My05NDA0LTVkNmE0YjI2ZWZiNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMFQwODE4NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YTAzMGU4OGMzYTkwNDYwZjA3ODgwMDhmNGY2MTVlY2UzNTZjYmM0MTZhZDZkYTVkMzI4ZWFmYzgzNzNkZjcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gxVJbpVXO_c1pr2WLypN8Xt_-Zx9GrLpFRP9wXP7QGg)

或者你拷贝邀请码的时候会带有空格，删掉最后的空格

**Comment by Hansonwong47** [comment]
我填完下之後呢

**Comment by liumy-lay** [comment]
你加微信群问一下助教：
https://aicarrier.feishu.cn/wiki/XBO6wpQcSibO1okrChhcBkQjnsf
扫码报名后收到邮件中的二维码加入微信班级群, 并将群昵称改为【问卷星序号-微信昵称】

**Comment by Hansonwong47** [comment]
![85D116F7-BE31-437A-B783-45EDDFB76483](https://github.com/user-attachments/assets/1076c10d-4879-43aa-baec-01fd586b18e9)

**Comment by Hansonwong47** [comment]
还是不行

**Comment by liumy-lay** [comment]
详细看一下你邮箱里收到的邮件，有问题加微信群与助教沟通，如果有了平台账号，邀请码可以忽略。
![image](https://github.com/user-attachments/assets/1e444963-76b1-46b8-a596-b404695637b8)

**Comment by Hansonwong47** [comment]
但為什麼我填了邀請碼還是用不了

**Comment by Hansonwong47** [comment]
你們看用不了

**Comment by Hansonwong47** [comment]
![Uploading 85D116F7-BE31-437A-B783-45EDDFB76483.png…]()

**Comment by Hansonwong47** [comment]
![85D116F7-BE31-437A-B783-45EDDFB76483](https://github.com/user-attachments/assets/fb062591-e78e-4feb-bece-bda3d6a284ad)
