### ISSUE TITLE
[Bug] Encounter errors when using model locally

### ISSUE THREAD

**Issue by HanKaiyang** [InternLM/InternLM#770]
### Describe the bug

```
import torch
from modelscope import AutoModel, AutoTokenizer

torch.set_grad_enabled(False)
model_path = './local_dir'

# init model and tokenizer
model = AutoModel.from_pretrained(model_path, torch_dtype=torch.bfloat16, trust_remote_code=True).cuda().eval()
tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)

query = 'Analyze the given image in a detail manner'
image = ['./tests/panda.jpg']
with torch.autocast(device_type='cuda', dtype=torch.float16):
    response, _ = model.chat(tokenizer, query, image, do_sample=False, num_beams=3, use_meta=True)
print(response)
```
Hi, I was using the code above to test the model locally, but got the error 
```

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [65], in <module>
      5 images.append(image)
      6 image = torch.stack(images)
----> 7 response, _ = model.chat(tokenizer,
      8                          query=query,
      9                          image=image,
     10                          history=[])
     11 print(response)

File /opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py:115, in context_decorator.<locals>.decorate_context(*args, **kwargs)
    112 @functools.wraps(func)
    113 def decorate_context(*args, **kwargs):
    114     with ctx_factory():
--> 115         return func(*args, **kwargs)

File ~/.cache/huggingface/modules/transformers_modules/modeling_internlm_xcomposer2.py:594, in InternLMXComposer2ForCausalLM.chat(self, tokenizer, query, image, hd_num, history, streamer, max_new_tokens, do_sample, num_beams, temperature, top_p, repetition_penalty, infer_mode, use_meta, meta_instruction, **kwargs)
    592     im_mask = torch.zeros(inputs['input_ids'].shape[:2]).cuda().bool()
    593 else:
--> 594     inputs, im_mask, _ = self.interleav_wrap_chat(query, image, history=history, meta_instruction=meta_instruction, hd_num=hd_num)
    595 inputs = {
    596     k: v.to(self.device)
    597     for k, v in inputs.items() if torch.is_tensor(v)
    598 }
    599 # also add end-of-assistant token in eos token id to avoid unnecessary generation

File ~/.cache/huggingface/modules/transformers_modules/modeling_internlm_xcomposer2.py:259, in InternLMXComposer2ForCausalLM.interleav_wrap_chat(self, query, image, history, meta_instruction, max_length, hd_num)
    257 for idx, part in enumerate(parts):
    258     if need_bos or len(part) > 0:
--> 259         part_tokens = self.tokenizer(
    260             part,
    261             return_tensors='pt',
    262             padding='longest',
    263             add_special_tokens=need_bos).to(self.device)
    264         if need_bos:
    265             need_bos = False

TypeError: 'NoneType' object is not callable
```
Also, if I use the code _**TestMMModel**_ from test_hf_model, it will report the two images (panda.jpg and bamboo.jpg) are not the same size when running this line
`image = torch.stack(images)`

The model was downloaded from link below
https://www.modelscope.cn/models/Shanghai_AI_Laboratory/internlm-xcomposer2d5-7b

### Environment

python 3.10.13
torch 2.1.2
cuda 12.2

**Comment by zhulinJulia24** [comment]
> ### Describe the bug
> ```
> import torch
> from modelscope import AutoModel, AutoTokenizer
> 
> torch.set_grad_enabled(False)
> model_path = './local_dir'
> 
> # init model and tokenizer
> model = AutoModel.from_pretrained(model_path, torch_dtype=torch.bfloat16, trust_remote_code=True).cuda().eval()
> tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
> 
> query = 'Analyze the given image in a detail manner'
> image = ['./tests/panda.jpg']
> with torch.autocast(device_type='cuda', dtype=torch.float16):
>     response, _ = model.chat(tokenizer, query, image, do_sample=False, num_beams=3, use_meta=True)
> print(response)
> ```
> 
> Hi, I was using the code above to test the model locally, but got the error
> 
> ```
> 
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> Input In [65], in <module>
>       5 images.append(image)
>       6 image = torch.stack(images)
> ----> 7 response, _ = model.chat(tokenizer,
>       8                          query=query,
>       9                          image=image,
>      10                          history=[])
>      11 print(response)
> 
> File /opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py:115, in context_decorator.<locals>.decorate_context(*args, **kwargs)
>     112 @functools.wraps(func)
>     113 def decorate_context(*args, **kwargs):
>     114     with ctx_factory():
> --> 115         return func(*args, **kwargs)
> 
> File ~/.cache/huggingface/modules/transformers_modules/modeling_internlm_xcomposer2.py:594, in InternLMXComposer2ForCausalLM.chat(self, tokenizer, query, image, hd_num, history, streamer, max_new_tokens, do_sample, num_beams, temperature, top_p, repetition_penalty, infer_mode, use_meta, meta_instruction, **kwargs)
>     592     im_mask = torch.zeros(inputs['input_ids'].shape[:2]).cuda().bool()
>     593 else:
> --> 594     inputs, im_mask, _ = self.interleav_wrap_chat(query, image, history=history, meta_instruction=meta_instruction, hd_num=hd_num)
>     595 inputs = {
>     596     k: v.to(self.device)
>     597     for k, v in inputs.items() if torch.is_tensor(v)
>     598 }
>     599 # also add end-of-assistant token in eos token id to avoid unnecessary generation
> 
> File ~/.cache/huggingface/modules/transformers_modules/modeling_internlm_xcomposer2.py:259, in InternLMXComposer2ForCausalLM.interleav_wrap_chat(self, query, image, history, meta_instruction, max_length, hd_num)
>     257 for idx, part in enumerate(parts):
>     258     if need_bos or len(part) > 0:
> --> 259         part_tokens = self.tokenizer(
>     260             part,
>     261             return_tensors='pt',
>     262             padding='longest',
>     263             add_special_tokens=need_bos).to(self.device)
>     264         if need_bos:
>     265             need_bos = False
> 
> TypeError: 'NoneType' object is not callable
> ```
> 
> Also, if I use the code _**TestMMModel**_ from test_hf_model, it will report the two images (panda.jpg and bamboo.jpg) are not the same size when running this line `image = torch.stack(images)`
> 
> The model was downloaded from link below https://www.modelscope.cn/models/Shanghai_AI_Laboratory/internlm-xcomposer2d5-7b
> 
> ### Environment
> python 3.10.13 torch 2.1.2 cuda 12.2
> 
> ### Other information
> _No response_

can you try demo in https://huggingface.co/internlm/internlm-xcomposer2d5-7b or https://github.com/InternLM/InternLM-XComposer ？

**Comment by HanKaiyang** [comment]
> > ### Describe the bug
> > ```
> > import torch
> > from modelscope import AutoModel, AutoTokenizer
> > 
> > torch.set_grad_enabled(False)
> > model_path = './local_dir'
> > 
> > # init model and tokenizer
> > model = AutoModel.from_pretrained(model_path, torch_dtype=torch.bfloat16, trust_remote_code=True).cuda().eval()
> > tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
> > 
> > query = 'Analyze the given image in a detail manner'
> > image = ['./tests/panda.jpg']
> > with torch.autocast(device_type='cuda', dtype=torch.float16):
> >     response, _ = model.chat(tokenizer, query, image, do_sample=False, num_beams=3, use_meta=True)
> > print(response)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Hi, I was using the code above to test the model locally, but got the error
> > ```
> > 
> > ---------------------------------------------------------------------------
> > TypeError                                 Traceback (most recent call last)
> > Input In [65], in <module>
> >       5 images.append(image)
> >       6 image = torch.stack(images)
> > ----> 7 response, _ = model.chat(tokenizer,
> >       8                          query=query,
> >       9                          image=image,
> >      10                          history=[])
> >      11 print(response)
> > 
> > File /opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py:115, in context_decorator.<locals>.decorate_context(*args, **kwargs)
> >     112 @functools.wraps(func)
> >     113 def decorate_context(*args, **kwargs):
> >     114     with ctx_factory():
> > --> 115         return func(*args, **kwargs)
> > 
> > File ~/.cache/huggingface/modules/transformers_modules/modeling_internlm_xcomposer2.py:594, in InternLMXComposer2ForCausalLM.chat(self, tokenizer, query, image, hd_num, history, streamer, max_new_tokens, do_sample, num_beams, temperature, top_p, repetition_penalty, infer_mode, use_meta, meta_instruction, **kwargs)
> >     592     im_mask = torch.zeros(inputs['input_ids'].shape[:2]).cuda().bool()
> >     593 else:
> > --> 594     inputs, im_mask, _ = self.interleav_wrap_chat(query, image, history=history, meta_instruction=meta_instruction, hd_num=hd_num)
> >     595 inputs = {
> >     596     k: v.to(self.device)
> >     597     for k, v in inputs.items() if torch.is_tensor(v)
> >     598 }
> >     599 # also add end-of-assistant token in eos token id to avoid unnecessary generation
> > 
> > File ~/.cache/huggingface/modules/transformers_modules/modeling_internlm_xcomposer2.py:259, in InternLMXComposer2ForCausalLM.interleav_wrap_chat(self, query, image, history, meta_instruction, max_length, hd_num)
> >     257 for idx, part in enumerate(parts):
> >     258     if need_bos or len(part) > 0:
> > --> 259         part_tokens = self.tokenizer(
> >     260             part,
> >     261             return_tensors='pt',
> >     262             padding='longest',
> >     263             add_special_tokens=need_bos).to(self.device)
> >     264         if need_bos:
> >     265             need_bos = False
> > 
> > TypeError: 'NoneType' object is not callable
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also, if I use the code _**TestMMModel**_ from test_hf_model, it will report the two images (panda.jpg and bamboo.jpg) are not the same size when running this line `image = torch.stack(images)`
> > The model was downloaded from link below https://www.modelscope.cn/models/Shanghai_AI_Laboratory/internlm-xcomposer2d5-7b
> > ### Environment
> > python 3.10.13 torch 2.1.2 cuda 12.2
> > ### Other information
> > _No response_
> 
> can you try demo in https://huggingface.co/internlm/internlm-xcomposer2d5-7b or https://github.com/InternLM/InternLM-XComposer ？

Thank you for your reply, But the first coding paragraph should be the same as the huggingface **_High Resolution Image Understanding_** demo, except I changed the model to my local files. 
I'm not sure if it's the way I use that cause this error.

**Comment by zhulinJulia24** [comment]
@HanKaiyang They have different implementations, you can see the code https://huggingface.co/internlm/internlm-xcomposer2-7b/blob/d7ab428de9dc92ea1df7763bf4723ac76c181da1/modeling_internlm_xcomposer2.py#L477  and https://huggingface.co/internlm/internlm-xcomposer2d5-7b/blob/4aa81f2bbf20a9ddd4137dfe847c142adf07b652/modeling_internlm_xcomposer2.py#L601. The format of parameter image is different.

**Comment by HanKaiyang** [comment]
> @HanKaiyang They have different implementations, you can see the code https://huggingface.co/internlm/internlm-xcomposer2-7b/blob/d7ab428de9dc92ea1df7763bf4723ac76c181da1/modeling_internlm_xcomposer2.py#L477 and https://huggingface.co/internlm/internlm-xcomposer2d5-7b/blob/4aa81f2bbf20a9ddd4137dfe847c142adf07b652/modeling_internlm_xcomposer2.py#L601. The format of parameter image is different.

Hi, I think I figure out the problem. When using `model.chat(tokenizer,...)`, the tokenizer is not attached to the model properly, so that the tokenizer is not callable in function `interleav_wrap_chat`.

The problem is solved by initiated the model tokenizer by adding `model.tokenizer = tokenizer` before using `model.chat`.
```
model_path = './local_dir'
tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
model = AutoModel.from_pretrained(model_path, torch_dtype=torch.bfloat16, trust_remote_code=True).cuda().eval()
model.tokenizer = tokenizer
model.chat(...)
```
Appreciate for you help. 
BG
