### ISSUE TITLE
[QA]  使用convert2llama脚本转换前后的模型推理，输入的token一开始是一致的，之后会不一致，请问这是合理的吗？

### ISSUE THREAD

**Issue by Hukongtao** [InternLM/InternLM#771]
### Describe the question.

首先使用convert2llama脚本进行模型权重转换，
```shell
python3 convert2llama.py --src internlm2-chat-7b --tgt  llama_chat_7b/
```

然后分别使用转换前后的模型进行推理，推理的代码：
```python
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM


interlm_model_name = "./internlm2-chat-7b/"
llama_model_name = "./llama_chat_7b/"

tokenizer = AutoTokenizer.from_pretrained(interlm_model_name, trust_remote_code=True)
# model = AutoModelForCausalLM.from_pretrained(interlm_model_name, torch_dtype=torch.float16, trust_remote_code=True).cuda()
model = AutoModelForCausalLM.from_pretrained(llama_model_name, torch_dtype=torch.float16).cuda()
model = model.eval()

prompts = ["who are you"]
inputs = tokenizer(prompts, padding=True, return_tensors="pt")
input_ids = inputs.input_ids.cuda()
print(input_ids)

generated_results = model.generate(
    input_ids,
    max_new_tokens=128,
    do_sample=False,
    output_scores=True,
    return_dict_in_generate=True,
)
generated_ids = generated_results["sequences"]
generated_ids = generated_ids[:, len(input_ids[0]) :]
output = tokenizer.batch_decode(
    generated_ids,
    skip_special_tokens=True,
)[0]
print(output)
```

转换前后的输出如下：
![image](https://github.com/user-attachments/assets/e74f703b-e0c6-46ab-b454-403dbe544d42)
可以看到一开始的输入的token是一致的，大概几十个token之后会出现输出不一致的情况，想问下这种不一致是合理的吗？

**Comment by Hukongtao** [comment]
在第一次出现`\n`之前出现的token都是一致的

**Comment by MCplayerFromPRC** [comment]
可以把fp16改成fp32试试？`torch_dtype=torch.float32`

**Comment by Hukongtao** [comment]
> 可以把fp16改成fp32试试？`torch_dtype=torch.float32` ![image](https://private-user-images.githubusercontent.com/40713961/356217678-f84a893b-9a46-4423-8fdf-e9de8d4eb99a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxODUyMzMsIm5iZiI6MTcyMzE4NDkzMywicGF0aCI6Ii80MDcxMzk2MS8zNTYyMTc2NzgtZjg0YTg5M2ItOWE0Ni00NDIzLThmZGYtZTlkZThkNGViOTlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDA2Mjg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5ZTJhOGY5NjcwMDc5Y2M0YTM4MzdlYjI3NDc1ODQyNjI1MDJhNjFiNGJlYjQxYWYwYmMyZDZmMmViYThhNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rFf0ZOkD50KnSBVHdC_tw90KEqoFxp22RNOIqkyZDfU)

看下来本质上是InterLM的fp32和fp16之间的diff导致的。转成Llama之后FP32和FP16之间是能对上的。
