### ISSUE TITLE
[QA] internlm2.5的function call的template的来源

### ISSUE THREAD

**Issue by Lam1360** [InternLM/InternLM#776]
### 描述问题

internlm2.5的function call的处理没看到官方有对应的处理逻辑介绍（怎么组装成模型的输入）

**Comment by jinxianwei** [comment]
internlm2.5支持了function call嗎，我用openai的樣例程序，怎麽調整都調整不出來

**Comment by Harold-lkk** [comment]
> ### 描述问题
> internlm2.5的function call的处理没看到官方有对应的处理逻辑介绍（怎么组装成模型的输入）

https://github.com/InternLM/InternLM/blob/main/chat/chat_format.md#function-call

**Comment by Harold-lkk** [comment]
> internlm2.5支持了function call嗎，我用openai的樣例程序，怎麽調整都調整不出來

Puyu API currently does not support function call, but `LMDeploy` supports it right now, see https://lmdeploy.readthedocs.io/en/latest/serving/api_server_tools.html#internlm

**Comment by jinxianwei** [comment]
調通了，感謝
