### ISSUE TITLE
[Bug] 在将internlm转换为llama之后，使用转换后的llama tokenizer对prompt做embedding会超出词表范围

### ISSUE THREAD

**Issue by qiyuxinlin** [InternLM/InternLM#779]
### 描述该错误

在将internlm转换为llama之后，使用转换后的llama tokenizer对prompt做embedding会超出词表范围，这种情况下，我必须调用原internlm的tokenizer

### 环境信息

模型为internlm2_5-7b-chat-1m，与环境无关

### 其他信息

![image](https://github.com/user-attachments/assets/a144c614-71d1-40e1-9993-da4e7ce400de)

**Comment by gaoyang07** [comment]
可以提供具体报错吗？

**Comment by skylake5200** [comment]
> ### 描述该错误
> 在将internlm转换为llama之后，使用转换后的llama tokenizer对prompt做embedding会超出词表范围，这种情况下，我必须调用原internlm的tokenizer
> 
> ### 环境信息
> 模型为internlm2_5-7b-chat-1m，与环境无关
> 
> ### 其他信息
> ![image](https://github.com/user-attachments/assets/a144c614-71d1-40e1-9993-da4e7ce400de)

在加载 Tokenizer 的时候, 需要使用 LlamaTokenizer, 而不能是 AutoTokenizer (会出现超出词表的问题).
