### ISSUE TITLE
[QA] sft 训练数据格式

### ISSUE THREAD

**Issue by yangxin60-tal** [InternLM/InternLM#782]
### Describe the question.

想做sft,请教下训练数据的格式，给个示例说明，非常感谢

**Comment by RangiLyu** [comment]
请参考微调文档：https://github.com/InternLM/InternLM/blob/main/finetune/README_zh-CN.md
我们推荐使用XTuner进行微调，关于XTuner中使用的**微调数据格式**可以参考以下文档：https://xtuner.readthedocs.io/zh-cn/latest/training/custom_sft_dataset.html

**Comment by yangxin60-tal** [comment]
谢谢您的回答
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Tue, Aug 6, 2024 10:56 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [InternLM/InternLM] [QA] sft 训练数据格式 (Issue #782)

&nbsp;



 
请参考微调文档：https://github.com/InternLM/InternLM/blob/main/finetune/README_zh-CN.md
 我们推荐使用XTuner进行微调，关于XTuner中使用的微调数据格式可以参考以下文档：https://xtuner.readthedocs.io/zh-cn/latest/training/custom_sft_dataset.html
