### ISSUE TITLE
[QA] What is the size of the native Context window?

### ISSUE THREAD

**Issue by Invariant0502** [InternLM/InternLM#784]
What is the size of the native Context window?

**Comment by gaoyang07** [comment]
During training: 4k -> 32k -> 256k

**Comment by Invariant0502** [comment]
> During training: 4k -> 32k -> 256k

Does the 20b-chat model have a native window size of 256k?

**Comment by ZwwWayne** [comment]
In fine-tuning, it undergoes 32k, so you can expect it to work within 256K
