### ISSUE TITLE
[QA] Why an OpenAI account is needed for long context demo?

### ISSUE THREAD

**Issue by hitalex** [InternLM/InternLM#789]
### Describe the question.

When I run the demo of long context modeling as in https://github.com/InternLM/InternLM/tree/main/long_context

I have the following issue:

openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

Then I check the script (https://github.com/InternLM/InternLM/blob/main/long_context/doc_chat_demo.py) and am curious that, why the OpenAI API is used instead of the deployed InternLM model?

**Comment by libowen2121** [comment]
Hi @hitalex, thanks for your question! The code is independent of any OpenAI account. We deploy the InternLM model using LMdeploy, which provides a service compatible with the OpenAI API interface in this demo. For more details, please refer to the documentation [here](https://lmdeploy.readthedocs.io/en/latest/multi_modal/api_server_vl.html).
