### ISSUE TITLE
[QA] 多轮对话微调的长度限制

### ISSUE THREAD

**Issue by RyanOvO** [InternLM/InternLM#792]
### 描述问题

model：internlm2.5
size：7B / 20B
场景：多轮对话微调训练

问题：
1. internlm2.5支持多大的多轮对话上下文的微调训练？
2. internlm2.5之前在训练时，训练的上下文是多少K？
3. 如果微调时，多轮对话的长度超过了模型自身训练时的长度，会有怎么样的影响？

**Comment by ZwwWayne** [comment]
For InternLM2.5-7B-Chat, it is 32K, for InternLM2.5-7B-Chat-1M, 256K is a better efficiency and performance trade-off.
