### ISSUE TITLE
[Feature] Ollama vision support

### ISSUE THREAD

**Issue by alexisvisco** [InternLM/InternLM#794]
### Describe the feature

Hello ! I saw the outperforming results this models does in OCR with the demo on hugface, I wonder if it will be possible to add it  to the vision API of ollama ? Only text version is available for now https://ollama.com/internlm/internlm2.5

Thanks you, if not could you explain why I am curious :) 

### Will you implement it?

- [ ] I would like to implement this feature and create a PR!

**Comment by ZwwWayne** [comment]
InternLM 2.5 does not support vision input, while InternLM-Xcomposer and InternVL supports. You may raise issue in their corresponding projects. 
https://github.com/OpenGVLab/InternVL
https://github.com/InternLM/InternLM-XComposer
