### ISSUE TITLE
[QA] Is there a 4 bit awq model for internlm 2_5-20b-chat ?

### ISSUE THREAD

**Issue by soulzzz** [InternLM/InternLM#798]
### Describe the question.

as title

**Comment by lvhan028** [comment]
We'll upload internlm2_5-20b-chat 4bit models to huggingface hub this week

**Comment by lvhan028** [comment]
https://huggingface.co/internlm/internlm2_5-20b-chat-4bit-awq
https://huggingface.co/internlm/internlm2_5-20b-chat-4bit-gptq

**Comment by soulzzz** [comment]
thank u
