### ISSUE TITLE
Two lines of `CommonSenseQA` evaluation results in the README

### ISSUE THREAD

**Issue by Spico197** [InternLM/InternLM#8]
Hi there, thanks for the excellent work! There are two lines of CommonSenseQA evaluation results. Are there any differences between them?
![image](https://github.com/InternLM/InternLM/assets/22840952/4179d5f2-1ecc-48f9-9098-ee4b3e21e8e6)

**Comment by tonysy** [comment]
Thanks. The second line is  duplicated. We have fixed problem
