### ISSUE TITLE
[Feature] license issue for Colossal-AI

### ISSUE THREAD

**Issue by binmakeswell** [InternLM/InternLM#82]
### Describe the feature

Dear InternLM team,

Thanks for your [Acknowledgements](https://github.com/InternLM/InternLM/tree/main#acknowledgements) to [Colossal-AI](https://github.com/hpcaitech/ColossalAI).

It would be appreciated if you could adhere to the open source agreement and cite [Colossal-AI license](https://github.com/hpcaitech/ColossalAI/blob/main/LICENSE#L190-L202) in [your license file](https://github.com/InternLM/InternLM/blob/main/LICENSE).

Thank you very much.

Colossal-AI team

### Will you implement it?

- [ ] I would like to implement this feature and create a PR!

**Comment by sunpengsdu** [comment]
@binmakeswell Hi, Thanks a lot for your message. We have updated the license file.
