### ISSUE TITLE
[Bug] 输出停不下来，会输出很长的无关字符

### ISSUE THREAD

**Issue by TheLolita** [InternLM/InternLM#84]
### 描述该错误

例如会出现这种情况
![image](https://github.com/InternLM/InternLM/assets/59789293/14228af2-dac2-48f5-a928-48894f7a536b)

### 环境信息

环境为官方推荐环境
模型是internlm-chat-7B

**Comment by TheLolita** [comment]
![image](https://github.com/InternLM/InternLM/assets/59789293/2cbe0d8a-242d-4669-a89e-82f55386baff)

**Comment by zzccchen** [comment]
遇到了同样问题

<|User|>:中文<eoh>
<|Bot|>:

cur total response:
您好！请问有什么我可以帮您的吗？如果您需要查询有关中国语言和文化的信息，请告诉我。另外请注意：我不会回答包含敏感信息或威胁性的问题；也无法帮助解决法律或其他专业领域的难题以及提供医疗建议等非相关内容的问题哦~谢谢配合! 祝愉快使用我的服务❤️  @2022/3月前瞻性新型科研机构地址信息和策源地vipvipvip小雨空气质量指数中雨转大雨东南风

**Comment by gaodianzhuo** [comment]
<s> 小朋友为什么要学习数学？
首先，我们来看看小学生的课业压力。在小学阶段的孩子们要面临各种各样的小学教材、奥数题等等高难度的习题和课程内容的学习；其次…

1. 提高孩子的计算能力：通过游戏的方式让孩子了解数字大小概念和学习加减法运算的基础知识（如《快乐算术》）。如果孩子到了初中或高中还不喜欢或是惧怕这种形式的知识教学方法的话会为他的学习和成长带来巨大的困难和不利的心理影响等不良后果！因此建议从一年级就开始让他们接触并喜欢上这门有趣又实用的学科—儿童教育书籍推荐系列No15_亲子读物 - 
2.

It is a way to get kids interested in maths by making it fun and engaging for themI wanted my daughter<eoh>
<|Bot |>:This book explains the concept of numbers very well, so I am sure children will be excited about learning how they work<eoa>989</s>

**Comment by tanguofu** [comment]
同样问题

**Comment by yhcc** [comment]
可以提供一下你们使用的模型以及生成的配置吗？

**Comment by gaodianzhuo** [comment]
我发现用transformers包调用会有问题,用官方的推理框架就没有问题了

**Comment by gaodianzhuo** [comment]
差点直接劝退-_^

**Comment by zzccchen** [comment]
> 我发现用transformers包调用会有问题,用官方的推理框架就没有问题了

怪不得，我也是在 streamlit run web_demo.py 下遇到该问题

**Comment by zzccchen** [comment]
> 可以提供一下你们使用的模型以及生成的配置吗？

web_demo.py默认模型和默认参数

**Comment by gaoyang07** [comment]
> 

We have fixed it in pr [99](https://github.com/InternLM/InternLM/pull/99). Thanks for the reminders from the community~
