### ISSUE TITLE
ModuleNotFoundError: No module named 'packaging'  when install apex 

### ISSUE THREAD

**Issue by kkscilife** [InternLM/InternLM#87]
### Describe the bug

when I install apex, some error occurred: 
ModuleNotFoundError: No module named 'packaging'
  error: subprocess-exited-with-error

### Environment

CUDA: 11.7
python: 3.10

**Comment by kkscilife** [comment]
I resolved this problem by this method:
pip install -v --disable-pip-version-check --no-cache-dir --no-build-isolation --config-settings "--global-option=--cpp_ext" --config-settings "--global-option=--cuda_ext" ./

It's the issue of apex: https://github.com/NVIDIA/apex/issues/1679

**Comment by lezhaotj** [comment]
> I resolved this problem by this method: pip install -v --disable-pip-version-check --no-cache-dir --no-build-isolation --config-settings "--global-option=--cpp_ext" --config-settings "--global-option=--cuda_ext" ./
> 
> It's the issue of apex: [NVIDIA/apex#1679](https://github.com/NVIDIA/apex/issues/1679)

Very helpful，thank you so much！

**Comment by mashengkun** [comment]
but new error:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by SmileDreamer** [comment]
> but new error: TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

Hello! I made the same error as you. May I ask how you solved this error?

**Comment by douyizi** [comment]
> > but new error: TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
> 
> Hello! I made the same error as you. May I ask how you solved this error?

Hi! I made the same error as you.Have you solved this problem now?

**Comment by SmileDreamer** [comment]
谢谢您的来信，我已经收到，并会尽快回复您。祝好！

**Comment by KenWyyyy** [comment]
I hope the author can help resolve this issue at their earliest convenience. Thank you!

**Comment by SmileDreamer** [comment]
谢谢您的来信，我已经收到，并会尽快回复您。祝好！
