### ISSUE TITLE
[Bug] web_demo中torch.cuda.empty_cache()不生效，显存一直上涨，几轮后重复回答问题

### ISSUE THREAD

**Issue by angelOnly** [InternLM/InternLM#90]
### Describe the bug

torch.cuda.empty_cache()在每次聊天后都会调用，但是不生效，显存一直上涨，几轮后重复回答问题

刚开始可以正常回复，几轮过后就不正常了
类似截图这样，一直重复，不能理解对话
![企业微信截图_e1f76ec3-eb1e-4c42-9ef0-c863cfb1e345](https://github.com/InternLM/InternLM/assets/18018532/f398c5de-fc91-4280-b353-651b4047e9a6)

### Environment

Python 3.8.16
streamlit==1.24.0
transformers==4.30.2

**Comment by yhcc** [comment]
可以提供一下使用的模型名称以及对应的生成参数吗？

**Comment by angelOnly** [comment]
模型：internlm-chat-7b, internlm-chat-7b-8k
生成参数：什么意思？
我部署这个模型是用的InternLM首页的web_demo，部署上之后，聊了几轮就会这样，显存一直涨，最后会oom，显存清不掉，会一直涨

**Comment by kztao** [comment]
碰到同样的问题
 
运行web_demo.py , 加载internlm-chat-7b模型, 对话10轮左右，就OOM了
环境是  ubuntu22.04 , 16G显存， python 3.10

**Comment by yhcc** [comment]
已经在PR https://github.com/InternLM/InternLM/pull/133 中得到修复，我暂时就关闭这个issue了，你们可以尝试再试试看，如果问题还没有解决，欢迎再次打开这个issue。
