### ISSUE TITLE
[Feature] 支持无apex、flash-attention的执行模式

### ISSUE THREAD

**Issue by zhangxc11** [InternLM/InternLM#93]
### 描述该功能

目前的仓库有几个复杂的依赖库apex、flash-attention，需要可以在没有这些依赖的条件下，可以fallback执行。
1. 提供无apex、flash-attention条件下的fallback执行模式
2. 支持opencompass评测直接运行
3. 支持pip安装

### 是否希望自己实现该功能？

- [ ] 我希望自己来实现这一功能，并向 InternLM 贡献代码！

**Comment by elijah-hz** [comment]
没人维护这个网站。装了这两个后，原来的训练的环境慢了很多。

**Comment by yingtongxiong** [comment]
1. 目前已支持非apex版本，已合入main分支。
2. 非flash-attention版本已支持了attention、linearParallel算子的去flash化。但还是有部分其他算子，如loss等还在使用flash的版本。
3. 已提供docker镜像，[https://github.com/InternLM/InternLM/pull/220](https://github.com/InternLM/InternLM/pull/220)
