### ISSUE TITLE
[Feature] 上下文缓存一直占用显存不释放，使用torch.cuda.empty_cache()无法释放显存缓存

### ISSUE THREAD

**Issue by angelOnly** [InternLM/InternLM#95]
### Describe the feature

torch.cuda.empty_cache()对其他模型生效，都能释放显存，这个模型无效

### Will you implement it?

希望增加释放显存缓存的功能，在用户手动清除缓存的情况下，希望显存能恢复到刚加载模型的状态

**Comment by yhcc** [comment]
如果持续聊天下去的话，由于上下文越来越长，所以会出现显存增长的问题的。

**Comment by angelOnly** [comment]
我知道你的意思，我是想说，在用户主动清除缓存的情况下，有没有可能能恢复到刚加载模型的状态，现在我清除不了

**Comment by yhcc** [comment]
在这个 https://github.com/InternLM/InternLM/pull/133 PR中我们修复了一下这个问题，麻烦你看看解决问题了吗？
